// src/lib/commercial_grades.ts

export interface CommercialGrade {
  id: string;
  producer: string;
  tradeName: string;
  gradeCode: string;
  polymerFamily: string;
  polymerType: 'Homopolymer' | 'Random Copolymer' | 'Impact Copolymer' | 'Glass Filled' | 'Unfilled' | 'Mineral Filled';
  processMethod: 'Injection Molding' | 'Blow Molding' | 'Film Extrusion' | 'Pipe Extrusion' | 'Raffia / Tapes' | 'Thermoforming';
  density: number; // g/cm³
  mfi: number; // g/10 min
  mfiCondition: string; // e.g. '230°C / 2.16 kg' or '190°C / 2.16 kg'
  tensileStrength: number; // MPa
  flexuralModulus: number; // MPa
  izodImpact: number; // J/m or kJ/m²
  elongationAtBreak: number; // %
  hdt: number; // °C at 0.45 MPa
  vicatSoftening: number; // °C (B50)
  meltTempRange: [number, number]; // [min, max] °C
  moldTempRange: [number, number]; // [min, max] °C
  shrinkage: [number, number]; // % [min, max]
  dryingRecommended: boolean;
  dryingCondition?: string;
  certifications: string[];
  applications: string[];
  description: string;
}

export const COMMERCIAL_GRADES: CommercialGrade[] = [
  // ── POLYPROPYLENE (PP) ──
  {
    id: 'reliance-repol-h110ma',
    producer: 'Reliance Industries',
    tradeName: 'Repol',
    gradeCode: 'H110MA',
    polymerFamily: 'Polypropylene (PP)',
    polymerType: 'Homopolymer',
    processMethod: 'Injection Molding',
    density: 0.90,
    mfi: 11.0,
    mfiCondition: '230°C / 2.16 kg',
    tensileStrength: 35,
    flexuralModulus: 1450,
    izodImpact: 30,
    elongationAtBreak: 100,
    hdt: 102,
    vicatSoftening: 154,
    meltTempRange: [210, 260],
    moldTempRange: [20, 50],
    shrinkage: [1.2, 1.8],
    dryingRecommended: false,
    certifications: ['IS 10910', 'FDA 21 CFR 177.1520', 'RoHS / REACH'],
    applications: ['Houseware', 'Closures', 'Thin-wall packaging', 'Furniture'],
    description: 'High flow homopolymer grade for general purpose injection molding of rigid items with fast cycle times.',
  },
  {
    id: 'iocl-propel-1110mas',
    producer: 'Indian Oil (IOCL)',
    tradeName: 'Propel',
    gradeCode: '1110MAS',
    polymerFamily: 'Polypropylene (PP)',
    polymerType: 'Homopolymer',
    processMethod: 'Injection Molding',
    density: 0.90,
    mfi: 11.5,
    mfiCondition: '230°C / 2.16 kg',
    tensileStrength: 36,
    flexuralModulus: 1500,
    izodImpact: 28,
    elongationAtBreak: 95,
    hdt: 105,
    vicatSoftening: 155,
    meltTempRange: [210, 260],
    moldTempRange: [25, 45],
    shrinkage: [1.2, 1.7],
    dryingRecommended: false,
    certifications: ['IS 10910', 'FDA Food Contact', 'RoHS Compliant'],
    applications: ['Industrial containers', 'Food containers', 'Caps & Closures'],
    description: 'Antistatic nucleated homopolymer grade formulated for clean mold release and excellent surface gloss.',
  },
  {
    id: 'gail-gpolymer-h030sg',
    producer: 'GAIL India',
    tradeName: 'G-Polymer',
    gradeCode: 'H030SG',
    polymerFamily: 'Polypropylene (PP)',
    polymerType: 'Homopolymer',
    processMethod: 'Raffia / Tapes',
    density: 0.90,
    mfi: 3.2,
    mfiCondition: '230°C / 2.16 kg',
    tensileStrength: 34,
    flexuralModulus: 1350,
    izodImpact: 35,
    elongationAtBreak: 150,
    hdt: 95,
    vicatSoftening: 152,
    meltTempRange: [220, 260],
    moldTempRange: [30, 50],
    shrinkage: [1.5, 2.2],
    dryingRecommended: false,
    certifications: ['IS 10910', 'BIS Certified'],
    applications: ['Woven sacks', 'Tarpaulins', 'Ropes', 'Carpet backing'],
    description: 'Standard raffia grade with low water carry-over and high tenacity for high-speed weaving looms.',
  },
  {
    id: 'reliance-repol-b300mn',
    producer: 'Reliance Industries',
    tradeName: 'Repol',
    gradeCode: 'B300MN',
    polymerFamily: 'Polypropylene (PP)',
    polymerType: 'Impact Copolymer',
    processMethod: 'Injection Molding',
    density: 0.90,
    mfi: 30.0,
    mfiCondition: '230°C / 2.16 kg',
    tensileStrength: 25,
    flexuralModulus: 1200,
    izodImpact: 75,
    elongationAtBreak: 50,
    hdt: 90,
    vicatSoftening: 148,
    meltTempRange: [200, 240],
    moldTempRange: [20, 40],
    shrinkage: [1.2, 1.6],
    dryingRecommended: false,
    certifications: ['Automotive OEM Approved', 'RoHS'],
    applications: ['Battery cases', 'Automotive trims', 'Appliance parts', 'Thin-wall containers'],
    description: 'Ultra-high flow impact block copolymer with superior cold-temperature impact balance.',
  },
  {
    id: 'iocl-propel-2300mn',
    producer: 'Indian Oil (IOCL)',
    tradeName: 'Propel',
    gradeCode: '2300MN',
    polymerFamily: 'Polypropylene (PP)',
    polymerType: 'Impact Copolymer',
    processMethod: 'Injection Molding',
    density: 0.90,
    mfi: 30.0,
    mfiCondition: '230°C / 2.16 kg',
    tensileStrength: 26,
    flexuralModulus: 1250,
    izodImpact: 70,
    elongationAtBreak: 60,
    hdt: 92,
    vicatSoftening: 149,
    meltTempRange: [200, 245],
    moldTempRange: [20, 45],
    shrinkage: [1.1, 1.5],
    dryingRecommended: false,
    certifications: ['IS 10910', 'Automotive Spec'],
    applications: ['Industrial crates', 'Battery containers', 'Luggage components'],
    description: 'Controlled rheology impact copolymer exhibiting fast injection cycle times and high weld-line strength.',
  },

  // ── POLYETHYLENE (HDPE / LLDPE / LDPE) ──
  {
    id: 'reliance-relene-b56003',
    producer: 'Reliance Industries',
    tradeName: 'Relene',
    gradeCode: 'B56003',
    polymerFamily: 'Polyethylene (HDPE)',
    polymerType: 'Homopolymer',
    processMethod: 'Blow Molding',
    density: 0.956,
    mfi: 0.33,
    mfiCondition: '190°C / 2.16 kg',
    tensileStrength: 28,
    flexuralModulus: 1100,
    izodImpact: 90,
    elongationAtBreak: 600,
    hdt: 75,
    vicatSoftening: 126,
    meltTempRange: [180, 220],
    moldTempRange: [15, 30],
    shrinkage: [2.0, 3.5],
    dryingRecommended: false,
    certifications: ['IS 10146', 'FDA 177.1520', 'UN Packaging Certified'],
    applications: ['Lube oil bottles', 'Detergent containers', 'Chemical jerry cans (up to 5L)'],
    description: 'Bimodal blow molding grade with outstanding Environmental Stress Crack Resistance (ESCR) and rigidity.',
  },
  {
    id: 'iocl-propel-003db52',
    producer: 'Indian Oil (IOCL)',
    tradeName: 'Propel',
    gradeCode: '003DB52',
    polymerFamily: 'Polyethylene (HDPE)',
    polymerType: 'Homopolymer',
    processMethod: 'Blow Molding',
    density: 0.952,
    mfi: 0.30,
    mfiCondition: '190°C / 2.16 kg',
    tensileStrength: 26,
    flexuralModulus: 1050,
    izodImpact: 95,
    elongationAtBreak: 650,
    hdt: 73,
    vicatSoftening: 124,
    meltTempRange: [180, 215],
    moldTempRange: [15, 25],
    shrinkage: [2.0, 3.2],
    dryingRecommended: false,
    certifications: ['IS 10146', 'FDA Food Contact'],
    applications: ['Milk bottles', 'Edible oil containers', 'Cosmetic bottles'],
    description: 'Excellent parison melt strength and high top-load crush strength for blow-molded containers.',
  },
  {
    id: 'reliance-relene-p5402',
    producer: 'Reliance Industries',
    tradeName: 'Relene',
    gradeCode: 'P5402 (PE100)',
    polymerFamily: 'Polyethylene (HDPE)',
    polymerType: 'Homopolymer',
    processMethod: 'Pipe Extrusion',
    density: 0.954,
    mfi: 0.25,
    mfiCondition: '190°C / 5.0 kg',
    tensileStrength: 24,
    flexuralModulus: 1000,
    izodImpact: 140,
    elongationAtBreak: 700,
    hdt: 70,
    vicatSoftening: 122,
    meltTempRange: [190, 230],
    moldTempRange: [20, 40],
    shrinkage: [1.8, 3.0],
    dryingRecommended: false,
    certifications: ['IS 4984 (PE100)', 'ISO 9080 MRS 10 MPa', 'WRAS Approved'],
    applications: ['Potable water pressure pipes', 'Gas distribution pipelines', 'Industrial effluent conduits'],
    description: 'Carbon-black compounded PE100 pipe resin with 50+ year design lifetime and exceptional slow crack growth resistance.',
  },
  {
    id: 'reliance-relene-20fs010',
    producer: 'Reliance Industries',
    tradeName: 'Relene',
    gradeCode: '20FS010',
    polymerFamily: 'Polyethylene (LLDPE)',
    polymerType: 'Homopolymer',
    processMethod: 'Film Extrusion',
    density: 0.920,
    mfi: 1.0,
    mfiCondition: '190°C / 2.16 kg',
    tensileStrength: 32,
    flexuralModulus: 250,
    izodImpact: 180,
    elongationAtBreak: 800,
    hdt: 45,
    vicatSoftening: 98,
    meltTempRange: [190, 230],
    moldTempRange: [20, 30],
    shrinkage: [2.5, 4.5],
    dryingRecommended: false,
    certifications: ['IS 10146', 'FDA 21 CFR'],
    applications: ['Agricultural films', 'Liquid packaging pouches', 'Stretch wrap', 'Heavy-duty sacks'],
    description: 'Hexene (C6) copolymer LLDPE film grade combining exceptional dart drop impact and puncture toughness.',
  },
  {
    id: 'iocl-propel-1180fs',
    producer: 'Indian Oil (IOCL)',
    tradeName: 'Propel',
    gradeCode: '1180FS',
    polymerFamily: 'Polyethylene (LLDPE)',
    polymerType: 'Homopolymer',
    processMethod: 'Film Extrusion',
    density: 0.918,
    mfi: 1.0,
    mfiCondition: '190°C / 2.16 kg',
    tensileStrength: 30,
    flexuralModulus: 220,
    izodImpact: 170,
    elongationAtBreak: 750,
    hdt: 43,
    vicatSoftening: 96,
    meltTempRange: [190, 225],
    moldTempRange: [20, 30],
    shrinkage: [2.2, 4.0],
    dryingRecommended: false,
    certifications: ['IS 10146', 'RoHS'],
    applications: ['General purpose packaging', 'Carrier bags', 'Co-extruded barrier liners'],
    description: 'Butene (C4) blown film resin with excellent optical properties and easy bubble stability.',
  },

  // ── ENGINEERING THERMOPLASTICS (PC / ABS / PA6 / POM / PBT) ──
  {
    id: 'covestro-makrolon-2805',
    producer: 'Covestro',
    tradeName: 'Makrolon',
    gradeCode: '2805',
    polymerFamily: 'Polycarbonate (PC)',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.20,
    mfi: 9.5,
    mfiCondition: '300°C / 1.2 kg',
    tensileStrength: 65,
    flexuralModulus: 2350,
    izodImpact: 750,
    elongationAtBreak: 110,
    hdt: 142,
    vicatSoftening: 145,
    meltTempRange: [280, 320],
    moldTempRange: [80, 110],
    shrinkage: [0.5, 0.7],
    dryingRecommended: true,
    dryingCondition: '120°C for 3–4 hrs (<0.02% moisture)',
    certifications: ['UL94 V-2', 'FDA 21 CFR 177.1580', 'ISO 10993 Biocompatible'],
    applications: ['Automotive lighting lenses', 'Safety goggles', 'Medical dialyzers', 'Electrical enclosures'],
    description: 'Medium viscosity, high impact optical polycarbonate with outstanding clarity (89% transmittance).',
  },
  {
    id: 'sabic-lexan-141r',
    producer: 'SABIC',
    tradeName: 'Lexan',
    gradeCode: '141R',
    polymerFamily: 'Polycarbonate (PC)',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.20,
    mfi: 10.5,
    mfiCondition: '300°C / 1.2 kg',
    tensileStrength: 63,
    flexuralModulus: 2300,
    izodImpact: 700,
    elongationAtBreak: 120,
    hdt: 138,
    vicatSoftening: 143,
    meltTempRange: [280, 315],
    moldTempRange: [70, 100],
    shrinkage: [0.5, 0.7],
    dryingRecommended: true,
    dryingCondition: '120°C for 3–4 hrs',
    certifications: ['UL94 V-2', 'RoHS / REACH', 'FDA Approved'],
    applications: ['Electrical connectors', 'Consumer electronics housings', 'LED covers'],
    description: 'Internal mold release agent added for easier ejection of complex, deep-draw molded parts.',
  },
  {
    id: 'ineos-absolac-120',
    producer: 'INEOS Styrolution',
    tradeName: 'Absolac',
    gradeCode: '120',
    polymerFamily: 'ABS Resin',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.04,
    mfi: 22.0,
    mfiCondition: '220°C / 10 kg',
    tensileStrength: 45,
    flexuralModulus: 2200,
    izodImpact: 220,
    elongationAtBreak: 35,
    hdt: 88,
    vicatSoftening: 98,
    meltTempRange: [210, 250],
    moldTempRange: [40, 70],
    shrinkage: [0.4, 0.7],
    dryingRecommended: true,
    dryingCondition: '80°C for 2–3 hrs (<0.05% moisture)',
    certifications: ['UL94 HB', 'BIS Certified', 'RoHS'],
    applications: ['Mixer grinder bodies', 'TV front bezels', 'Washing machine panels', 'Automotive mirror housings'],
    description: 'High-gloss, medium-impact ABS resin tailored for home appliances and consumer electronics.',
  },
  {
    id: 'basf-ultramid-b3s',
    producer: 'BASF',
    tradeName: 'Ultramid',
    gradeCode: 'B3S (PA6)',
    polymerFamily: 'Polyamide / Nylon (PA6)',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.13,
    mfi: 140.0,
    mfiCondition: '275°C / 5 kg (MVR)',
    tensileStrength: 80,
    flexuralModulus: 2800,
    izodImpact: 55,
    elongationAtBreak: 50,
    hdt: 65,
    vicatSoftening: 200,
    meltTempRange: [240, 275],
    moldTempRange: [40, 80],
    shrinkage: [0.7, 1.4],
    dryingRecommended: true,
    dryingCondition: '80°C for 4 hrs in desiccant dryer (<0.15% moisture)',
    certifications: ['UL94 V-2', 'Automotive OEM Spec'],
    applications: ['Cable ties', 'Bearings', 'Fasteners', 'Automotive fuel clips', 'Plugs'],
    description: 'Easy-flowing, rapidly solidifying PA6 grade engineered for thin-walled molding and fast cycle times.',
  },
  {
    id: 'dupont-zytel-73g30l',
    producer: 'DuPont / Celanese',
    tradeName: 'Zytel',
    gradeCode: '73G30L (PA6-GF30)',
    polymerFamily: 'Polyamide / Nylon (PA6)',
    polymerType: 'Glass Filled',
    processMethod: 'Injection Molding',
    density: 1.36,
    mfi: 35.0,
    mfiCondition: '275°C / 5 kg',
    tensileStrength: 175,
    flexuralModulus: 8500,
    izodImpact: 110,
    elongationAtBreak: 3.5,
    hdt: 205,
    vicatSoftening: 215,
    meltTempRange: [260, 290],
    moldTempRange: [70, 100],
    shrinkage: [0.2, 0.6],
    dryingRecommended: true,
    dryingCondition: '80°C for 4 hrs (<0.1% moisture)',
    certifications: ['UL94 HB', 'Automotive Under-the-Hood Certified'],
    applications: ['Engine intake manifolds', 'Power tool housings', 'Pump impellers', 'Pedal boxes'],
    description: '30% glass-fiber reinforced PA6 offering exceptional structural rigidity, creep resistance, and elevated HDT.',
  },
  {
    id: 'celanese-hostaform-c9021',
    producer: 'Celanese',
    tradeName: 'Hostaform',
    gradeCode: 'C9021 (POM)',
    polymerFamily: 'Polyacetal (POM)',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.41,
    mfi: 9.0,
    mfiCondition: '190°C / 2.16 kg',
    tensileStrength: 65,
    flexuralModulus: 2800,
    izodImpact: 60,
    elongationAtBreak: 30,
    hdt: 110,
    vicatSoftening: 160,
    meltTempRange: [190, 210],
    moldTempRange: [80, 110],
    shrinkage: [1.8, 2.2],
    dryingRecommended: true,
    dryingCondition: '100°C for 2–3 hrs',
    certifications: ['FDA 21 CFR 177.2470', 'NSF 61 Potable Water', 'UL94 HB'],
    applications: ['Precision gears', 'Valve spools', 'Snap-fit buckles', 'Conveyor rollers', 'Sanitary fittings'],
    description: 'Standard acetal copolymer with self-lubricating surface, low friction coefficient, and dimensional stability.',
  },

  // ── SPECIALTY & HIGH PERFORMANCE POLYMERS ──
  {
    id: 'victrex-peek-450g',
    producer: 'Victrex',
    tradeName: 'Victrex PEEK',
    gradeCode: '450G',
    polymerFamily: 'PEEK (Polyetheretherketone)',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.30,
    mfi: 3.5,
    mfiCondition: '400°C / 2.16 kg',
    tensileStrength: 100,
    flexuralModulus: 4100,
    izodImpact: 75,
    elongationAtBreak: 45,
    hdt: 160,
    vicatSoftening: 340,
    meltTempRange: [370, 400],
    moldTempRange: [160, 200],
    shrinkage: [1.0, 1.4],
    dryingRecommended: true,
    dryingCondition: '150°C for 3–4 hrs (<0.02% moisture)',
    certifications: ['UL94 V-0 (1.5mm)', 'FAR 25.853 Aerospace Flame/Smoke', 'ISO 10993'],
    applications: ['Aerospace brackets', 'Oil & gas backup rings', 'Semiconductor wafer carriers', 'Medical spinal cages'],
    description: 'Standard viscosity unreinforced PEEK offering unmatched chemical resistance, 260°C continuous service, and high fatigue endurance.',
  },
  {
    id: 'natureworks-ingeo-4043d',
    producer: 'NatureWorks',
    tradeName: 'Ingeo',
    gradeCode: '4043D (PLA)',
    polymerFamily: 'Bioplastics (PLA)',
    polymerType: 'Unfilled',
    processMethod: 'Film Extrusion',
    density: 1.24,
    mfi: 6.0,
    mfiCondition: '210°C / 2.16 kg',
    tensileStrength: 60,
    flexuralModulus: 3600,
    izodImpact: 25,
    elongationAtBreak: 6.0,
    hdt: 55,
    vicatSoftening: 60,
    meltTempRange: [190, 215],
    moldTempRange: [20, 35],
    shrinkage: [0.3, 0.5],
    dryingRecommended: true,
    dryingCondition: '80°C for 4 hrs (<0.01% moisture)',
    certifications: ['ASTM D6400 / EN 13432 Compostable', 'FDA Food Contact', 'Bio-based 100%'],
    applications: ['3D printing filament', 'Clear thermoformed clamshells', 'Cold drink cups', 'Fresh food trays'],
    description: 'High molecular weight bio-based PLA designed for clear thermoforming sheet and standard 1.75mm/2.85mm 3D printing filament.',
  },
  {
    id: 'covestro-desmopan-385s',
    producer: 'Covestro',
    tradeName: 'Desmopan',
    gradeCode: '385S (TPU)',
    polymerFamily: 'Thermoplastic Polyurethane (TPU)',
    polymerType: 'Unfilled',
    processMethod: 'Injection Molding',
    density: 1.20,
    mfi: 18.0,
    mfiCondition: '215°C / 10 kg',
    tensileStrength: 42,
    flexuralModulus: 95,
    izodImpact: 350,
    elongationAtBreak: 550,
    hdt: 45,
    vicatSoftening: 85,
    meltTempRange: [205, 230],
    moldTempRange: [20, 40],
    shrinkage: [0.8, 1.2],
    dryingRecommended: true,
    dryingCondition: '100°C for 3 hrs (<0.02% moisture)',
    certifications: ['RoHS / REACH', 'UL94 HB'],
    applications: ['Footwear soles', 'Gasket seals', 'Overmolding grip handles', 'Cable jackets', 'Pneumatic tubing'],
    description: 'Ester-based TPU with 85 Shore A hardness, superior abrasion resistance, elastic recovery, and oil grease resistance.',
  }
];
