// src/lib/polymer-glossary.ts
export const polymerGlossary: Record<string, string> = {
  'rheology': 'The study of flow and deformation of materials. In polymers, it describes how molten plastic flows through molds and dies.',
  'glass transition': 'The temperature at which an amorphous polymer transitions from a hard, glassy state to a rubbery, flexible state. Denoted as Tg.',
  'viscoelasticity': 'The property of materials that exhibit both viscous (liquid-like) and elastic (solid-like) behavior when deformed.',
  'extrusion': 'A continuous process where molten polymer is forced through a die to create shapes like pipes, films, and sheets.',
  'polymerization': 'The chemical process of linking monomers together to form long polymer chains. Types include addition and condensation polymerization.',
  'molecular weight': 'The average mass of polymer chains in a sample. Higher molecular weight generally means stronger, tougher materials.',
  'crystallinity': 'The degree of structural order in a polymer. Higher crystallinity increases strength and stiffness but reduces transparency.',
  'plasticizer': 'Additives that increase the flexibility and workability of plastics by reducing intermolecular forces between polymer chains.',
  'vulcanization': 'The chemical process of crosslinking rubber molecules to increase strength, elasticity, and durability.',
  'melt flow index': 'A measure of the ease of flow of molten polymer. Higher MFI means easier flow but lower mechanical properties.',
  'thermoplastic': 'A polymer that can be repeatedly melted and solidified without significant degradation.',
  'thermoset': 'A polymer that undergoes irreversible chemical crosslinking during curing, becoming permanently solid.',
  'polymer chain': 'A long chain of repeating monomer units connected by covalent bonds. The backbone of all plastics.',
  'monomer': 'A small molecule that can be chemically bonded to other monomers to form a polymer chain.',
  'copolymer': 'A polymer made from two or more different types of monomers.',
  'blend': 'A mixture of two or more polymers to achieve a combination of properties.',
  'composite': 'A material made from a polymer matrix reinforced with fibers, fillers, or other materials.',
  'biodegradable': 'A material that can be broken down by microorganisms into natural substances like water, CO2, and biomass.',
  'bioplastic': 'A plastic derived from renewable biomass sources, such as corn starch or sugarcane.',
  'compounding': 'The process of mixing polymers with additives, fillers, and reinforcements to achieve desired properties.',
  'elastomer': 'A polymer with viscoelasticity (having both viscosity and elasticity) and very weak intermolecular forces, generally having low Young\'s modulus and high failure strain.',
  'crosslinking': 'The formation of chemical bonds that link one polymer chain to another. Crosslinking increases strength and thermal resistance.',
  'amorphous': 'Polymers in which the molecular chains are disordered and tangled, with no crystalline structure (e.g., Polystyrene, PMMA).',
  'degradation': 'The deterioration of the polymer\'s physical or chemical properties due to exposure to heat, light, chemicals, or oxygen.',
  'creep': 'The slow, progressive deformation of a polymer material over time when subjected to a constant load or stress.',
  'tensile strength': 'The maximum stress that a material can withstand while being stretched or pulled before breaking.',
  'flexural modulus': 'A measure of a material\'s stiffness or resistance to bending when subjected to flexural loading.',
  'impact strength': 'The ability of a polymer to withstand a sudden high-speed impact without fracturing.',
  'thermal conductivity': 'The rate at which heat passes through a polymer material. Polymers generally have low thermal conductivity (good insulators).',
  'hdts': 'Heat Deflection Temperature. The temperature at which a polymer deforms under a specified load.',
  'cure time': 'The time required for a thermosetting polymer to undergo chemical crosslinking and fully solidify.',
  'die swell': 'The expansion of a polymer melt as it emerges from an extrusion die due to elastic memory recovery.',
  'shear rate': 'The rate at which a progressive shear deformation is applied to a polymer fluid.',
  'viscosity': 'A fluid\'s resistance to flow. For polymers, viscosity depends heavily on temperature, shear rate, and molecular weight.',
  'non-newtonian': 'Fluids whose viscosity changes under shear stress. Polymer melts are typically shear-thinning (pseudoplastic) non-Newtonian fluids.',
  'gate': 'The small opening through which molten plastic enters an injection mold cavity.',
  'runner': 'Channels in an injection mold that direct molten plastic from the sprue to the gates.',
  'sprue': 'The main channel through which molten plastic enters an injection mold from the nozzle.',
  'weld line': 'A line formed where two flow fronts of molten polymer meet and fail to weld completely, creating a mechanical weak point.',
  'sink mark': 'A depression in the surface of an injection molded part caused by local shrinkage during cooling, typically opposite thick ribs.',
  'warpage': 'Dimensional distortion in a molded plastic part caused by non-uniform cooling or differential shrinkage.',
  'copolymerization': 'The synthesis of a polymer using more than one type of monomer.',
  'polycondensation': 'A polymerization reaction that releases a small byproduct molecule like water or alcohol.',
  'tackiness': 'The stickiness of an uncured rubber or elastomer compound.',
  'filler': 'Inert substances added to a polymer to increase bulk, reduce cost, or improve specific properties like stiffness (e.g., talc, glass beads).',
  'stabilizer': 'Additives that prevent degradation of polymers by heat, light, oxygen, or ozone.',
  'shrinkage': 'The reduction in volume of a plastic part as it cools from melt to solid state.',
  'compatibilizer': 'A chemical agent added to immiscible polymer blends to stabilize the interface and improve mechanical properties.',
  'dielectric constant': 'The ratio of the permittivity of a polymer material to the permittivity of vacuum; measures the ability of a plastic to store electrical energy.',
  'monodisperse': 'A polymer sample in which all polymer chains have the exact same molecular weight (typically synthesized via living polymerization).'
};
