export interface Polymer3DModelDetails {
  id: string
  name: string
  abbreviation: string
  category: 'Molecule' | 'Product' | 'Machine' | 'Process'
  model_type: string
  iupacName?: string
  casNumber?: string
  formula?: string
  cru?: string // Constitutional Repeating Unit
  monomer?: string
  polymerizationType?: string
  classification?: string
  functionalGroup?: string
  howFormed: string
  tg?: string
  tm?: string
  density?: string
  tensileStrength?: string
  indianBrands?: string[]
  topApplications: string[]
  curriculumLessonUrl: string
  aiPrompt: string
}

export const POLYMER_3D_KNOWLEDGE: Record<string, Polymer3DModelDetails> = {
  // ─── 30 MOLECULES ──────────────────────────────────────────────────────────
  m01: {
    id: 'm01',
    name: 'Polyethylene (PE)',
    abbreviation: 'PE / HDPE / LDPE',
    category: 'Molecule',
    model_type: 'molecule_polyethylene',
    iupacName: 'Poly(ethene-1,2-diyl) / Poly(methylene)',
    casNumber: '9002-88-4',
    formula: '(C₂H₄)ₙ',
    cru: '–[CH₂–CH₂]ₙ–',
    monomer: 'Ethylene (Ethene), CH₂=CH₂',
    polymerizationType: 'Addition (Chain-Growth) via Ziegler-Natta / Metallocene / Free-Radical',
    classification: 'Thermoplastic, Semi-Crystalline (50–80%), Commodity Polyolefin',
    functionalGroup: 'Aliphatic Saturated Hydrocarbon (–C–C– Backbone)',
    howFormed: 'Ethylene gas monomers undergo catalytic coordination polymerization over Ziegler-Natta (TiCl₄/AlEt₃) or metallocene catalysts, opening the C=C double bond without byproducts to form high-molecular-weight linear carbon chains.',
    tg: '–120°C to –100°C',
    tm: '125°C to 135°C (HDPE) / 105°C to 115°C (LDPE)',
    density: '0.915 – 0.965 g/cm³',
    tensileStrength: '20 – 35 MPa',
    indianBrands: ['Reliance Relene', 'IOCL Propel HDPE', 'GAIL G-Polymer', 'OPAL HDPE'],
    topApplications: ['High-pressure water pipes (PE-100)', 'Blow-molded milk crates & containers', 'Packaging films & geomembranes'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain the polymerization mechanism of Polyethylene (PE), comparing Ziegler-Natta coordination kinetics vs free radical high-pressure LDPE synthesis.'
  },
  m02: {
    id: 'm02',
    name: 'Polypropylene (PP)',
    abbreviation: 'PP / iPP',
    category: 'Molecule',
    model_type: 'molecule_polypropylene',
    iupacName: 'Poly(propene-1,2-diyl) / Poly(1-methylethylene)',
    casNumber: '9003-07-0',
    formula: '(C₃H₆)ₙ',
    cru: '–[CH₂–CH(CH₃)]ₙ–',
    monomer: 'Propylene (Propene), CH₂=CH–CH₃',
    polymerizationType: 'Stereospecific Coordination Addition via 4th-Gen Ziegler-Natta / Kaminsky Catalysts',
    classification: 'Thermoplastic, Highly Isotactic Semi-Crystalline (60–70%)',
    functionalGroup: 'Aliphatic Hydrocarbon with Pendant Methyl (–CH₃) Group',
    howFormed: 'Propylene monomers polymerize stereospecifically in the presence of titanium-magnesium supported coordination catalysts. The asymmetric C=C bond inserts with head-to-tail stereoregularity, yielding isotactic helical chains.',
    tg: '–10°C to 0°C',
    tm: '160°C to 168°C',
    density: '0.900 – 0.910 g/cm³ (Lightest commodity plastic)',
    tensileStrength: '30 – 42 MPa',
    indianBrands: ['Reliance Repol', 'IOCL Propel PP', 'GAIL PP', 'HPCL-Mittal Polypropylene'],
    topApplications: ['Automotive bumpers & battery casings', 'Woven raffia bags (cement/grain sacks)', 'Living hinges & microwave-safe containers'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain how isotactic polypropylene achieves its high melting point of 165°C and why living hinges in PP do not fatigue fail.'
  },
  m03: {
    id: 'm03',
    name: 'Polyvinyl Chloride (PVC)',
    abbreviation: 'PVC / uPVC / CPVC',
    category: 'Molecule',
    model_type: 'molecule_pvc',
    iupacName: 'Poly(1-chloroethylene)',
    casNumber: '9002-86-2',
    formula: '(C₂H₃Cl)ₙ',
    cru: '–[CH₂–CH(Cl)]ₙ–',
    monomer: 'Vinyl Chloride Monomer (VCM), CH₂=CH–Cl',
    polymerizationType: 'Free-Radical Suspension / Emulsion Addition Polymerization',
    classification: 'Thermoplastic, Predominantly Amorphous (~10% Syndiotactic Crystallinity)',
    functionalGroup: 'Chlorinated Hydrocarbon Backbone (Carbon-Chlorine Dipole)',
    howFormed: 'Vinyl chloride gas droplets suspended in water are initiated by organic peroxides at 50–65°C. Free radicals propagate through head-to-tail monomer addition, forming chains that precipitate as porous grains.',
    tg: '80°C to 85°C',
    tm: '212°C (Decomposes before reaching theoretical melt)',
    density: '1.380 – 1.450 g/cm³',
    tensileStrength: '45 – 65 MPa',
    indianBrands: ['Reliance Reon', 'Chemplast Sanmar', 'DCW PVC', 'Finolex'],
    topApplications: ['Rigid potable & agricultural pressure pipes (uPVC)', 'Window profiles & electrical conduits', 'Flexible cable insulation & blood bags (plasticized)'],
    curriculumLessonUrl: '/subjects/polymer-processing',
    aiPrompt: 'Explain why PVC requires thermal stabilizers (e.g. Ca-Zn, Tin) during twin-screw extrusion to prevent dehydrochlorination (HCl elimination).'
  },
  m04: {
    id: 'm04',
    name: 'Nylon 6,6 (Polyamide 66)',
    abbreviation: 'PA66',
    category: 'Molecule',
    model_type: 'molecule_nylon',
    iupacName: 'Poly(hexamethylene adipamide) / Poly(iminoadipoyliminohexane-1,6-diyl)',
    casNumber: '32131-17-2',
    formula: '(C₁₂H₂₂N₂O₂)ₙ',
    cru: '–[NH–(CH₂)₆–NH–CO–(CH₂)₄–CO]ₙ–',
    monomer: 'Hexamethylenediamine + Adipic Acid (Stoichiometric 1:1 Salt)',
    polymerizationType: 'Step-Growth Melt Polycondensation (Condensation with H₂O elimination)',
    classification: 'Engineering Thermoplastic, Highly Crystalline with Interchain H-Bonding',
    functionalGroup: 'Secondary Amide Linkage (–CO–NH–)',
    howFormed: 'Hexamethylenediamine reacts with adipic acid to form nylon salt (AH salt). When heated under high pressure in an autoclave followed by vacuum distillation, water of condensation is continuously removed to drive high molecular weight conversion via Le Chatelier’s principle.',
    tg: '50°C to 60°C',
    tm: '255°C to 265°C',
    density: '1.140 – 1.150 g/cm³',
    tensileStrength: '75 – 90 MPa (Dry) / 175 MPa (30% Glass Filled)',
    indianBrands: ['DuPont Zytel', 'SRF Tufnyl 66', 'BASF Ultramid A', 'DOMO Domamid'],
    topApplications: ['Automotive radiator end tanks & fuel rails', 'Heavy-duty industrial gears & sliding bearings', 'High-tenacity tire cord fibers & cable ties'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Derive the Carothers equation for Nylon 66 stoichiometry and explain how 1% excess diamine controls the molecular weight ceiling.'
  },
  m05: {
    id: 'm05',
    name: 'Polystyrene (PS)',
    abbreviation: 'PS / GPPS / HIPS',
    category: 'Molecule',
    model_type: 'molecule_polystyrene',
    iupacName: 'Poly(1-phenylethene-1,2-diyl) / Poly(1-phenylethylene)',
    casNumber: '9003-53-6',
    formula: '(C₈H₈)ₙ',
    cru: '–[CH₂–CH(C₆H₅)]ₙ–',
    monomer: 'Styrene Monomer, C₆H₅–CH=CH₂',
    polymerizationType: 'Free-Radical Bulk or Suspension Addition Polymerization',
    classification: 'Thermoplastic, Completely Amorphous (Atactic), Glassy & Brittle',
    functionalGroup: 'Aromatic Pendant Phenyl Ring on Aliphatic Chain',
    howFormed: 'Styrene monomer is thermally or catalytically polymerized via free radical initiation. Bulk continuous polymerization inside multi-zone plug-flow towers yields crystal-clear, rigid atactic chains.',
    tg: '95°C to 105°C',
    tm: 'Amorphous (Softens at ~100°C; No sharp crystalline Tm)',
    density: '1.040 – 1.060 g/cm³',
    tensileStrength: '35 – 50 MPa',
    indianBrands: ['Supreme Petrochem GPPS/HIPS', 'LG Polymers', 'INPEX Polystyrene'],
    topApplications: ['Petri dishes & crystal jewel cases (GPPS)', 'Refrigerator inner door liners (HIPS)', 'Expanded EPS thermal insulation packaging'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain why GPPS is optically transparent with high refractive index but susceptible to environmental stress cracking in fats and oils.'
  },
  m06: {
    id: 'm06',
    name: 'Polycarbonate (PC)',
    abbreviation: 'PC / BPA-PC',
    category: 'Molecule',
    model_type: 'molecule_polycarbonate',
    iupacName: 'Poly(oxycarbonyloxy-1,4-phenyleneisopropylidene-1,4-phenylene)',
    casNumber: '25037-45-0',
    formula: '(C₁₆H₁₄O₃)ₙ',
    cru: '–[O–C₆H₄–C(CH₃)₂–C₆H₄–O–CO]ₙ–',
    monomer: 'Bisphenol-A (BPA) + Phosgene (or Diphenyl Carbonate melt)',
    polymerizationType: 'Interfacial Polycondensation or Melt Transesterification',
    classification: 'Engineering Thermoplastic, Amorphous High-Impact Glass',
    functionalGroup: 'Carbonate Ester Linkage (–O–CO–O–) with Rigid Aromatic Spacers',
    howFormed: 'Disodium salt of Bisphenol-A in aqueous phase reacts across an organic solvent interface (methylene chloride) with phosgene in the presence of amine catalysts, releasing NaCl and building high-toughness chains.',
    tg: '145°C to 150°C',
    tm: 'Amorphous (High heat resistance up to 135°C under load)',
    density: '1.200 – 1.220 g/cm³',
    tensileStrength: '60 – 75 MPa',
    indianBrands: ['Covestro Makrolon', 'SABIC Lexan', 'Trinseo Calibre'],
    topApplications: ['Bulletproof security glazing & riot shields', 'Automotive headlamp polycarbonate lenses', 'Optical discs (CD/DVD), safety helmets, incubator walls'],
    curriculumLessonUrl: '/subjects/polymer-testing',
    aiPrompt: 'Explain the high ductility and Izod impact strength (>600 J/m) of Polycarbonate despite being completely amorphous below its Tg of 145°C.'
  },
  m07: {
    id: 'm07',
    name: 'Polyethylene Terephthalate (PET)',
    abbreviation: 'PET / PETE / Polyester',
    category: 'Molecule',
    model_type: 'molecule_pet',
    iupacName: 'Poly(oxyethyleneoxyterephthaloyl) / Poly(ethylene benzene-1,4-dicarboxylate)',
    casNumber: '25038-59-9',
    formula: '(C₁₀H₈O₄)ₙ',
    cru: '–[CO–C₆H₄–CO–O–(CH₂)₂–O]ₙ–',
    monomer: 'Purified Terephthalic Acid (PTA) + Monoethylene Glycol (MEG)',
    polymerizationType: 'Melt Phase Esterification followed by Solid-State Polymerization (SSP)',
    classification: 'Thermoplastic, Semi-Crystalline (30–50%), High-Barrier Polyester',
    functionalGroup: 'Aromatic Ester Linkage (–Ar–COO–Alkyl–)',
    howFormed: 'PTA and MEG react at 240–260°C under antimony trioxide catalysis to form BHET oligomers. Transesterification under high vacuum removes excess ethylene glycol. Solid-state polymerization (SSP) then lifts Intrinsic Viscosity (IV) to 0.80–0.84 dL/g for bottle preforms.',
    tg: '70°C to 80°C',
    tm: '250°C to 260°C',
    density: '1.340 – 1.390 g/cm³',
    tensileStrength: '55 – 80 MPa (Unoriented) / >200 MPa (Biaxially Oriented BOPET)',
    indianBrands: ['Reliance Relpet', 'Dhunseri Aspet', 'JBF Industries PET', 'Ester Industries'],
    topApplications: ['Carbonated soft drink & mineral water bottles (ISBM)', 'Biaxially oriented packaging films (BOPET)', 'Polyester staple fiber (textiles & technical yarns)'],
    curriculumLessonUrl: '/subjects/polymer-processing',
    aiPrompt: 'Detail how Solid-State Polymerization (SSP) increases the Intrinsic Viscosity (IV) of PET bottle chips from 0.60 to 0.84 dL/g.'
  },
  m08: {
    id: 'm08',
    name: 'Polytetrafluoroethylene (PTFE)',
    abbreviation: 'PTFE / Teflon',
    category: 'Molecule',
    model_type: 'molecule_ptfe',
    iupacName: 'Poly(difluoromethylene)',
    casNumber: '9002-84-0',
    formula: '(C₂F₄)ₙ',
    cru: '–[CF₂–CF₂]ₙ–',
    monomer: 'Tetrafluoroethylene (TFE), CF₂=CF₂',
    polymerizationType: 'High-Pressure Free-Radical Aqueous Emulsion / Suspension Addition',
    classification: 'High-Performance Fluoropolymer, Extremely High Crystallinity (>90%)',
    functionalGroup: 'Fully Fluorinated Saturated Carbon Backbone (C–F bond energy: 485 kJ/mol)',
    howFormed: 'TFE gas is polymerized in demineralized water under persulfate redox initiators at 40–80°C. The dense shield of fluorine atoms around the carbon backbone imparts universal chemical inertness and extreme thermal resistance.',
    tg: '–110°C / 130°C',
    tm: '327°C (Extreme melt viscosity: ~10¹¹ Pa·s, non-melt-processable)',
    density: '2.140 – 2.200 g/cm³ (Heaviest engineering plastic)',
    tensileStrength: '20 – 35 MPa (High elongation 300%)',
    indianBrands: ['Gujarat Fluorochemicals (Inoflon)', 'Chemours Teflon', 'Daikin Polyflon'],
    topApplications: ['Chemical processing flange gaskets & valve seats', 'Non-stick industrial cookware coatings', 'Semiconductor ultra-pure fluid tubing & sliding pads'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain why PTFE cannot be processed on standard injection molding machines and must be fabricated via cold powder compaction and sintering.'
  },
  m09: {
    id: 'm09',
    name: 'Polyether Ether Ketone (PEEK)',
    abbreviation: 'PEEK',
    category: 'Molecule',
    model_type: 'molecule_peek',
    iupacName: 'Poly(oxy-1,4-phenyleneoxy-1,4-phenylenecarbonyl-1,4-phenylene)',
    casNumber: '29658-26-2',
    formula: '(C₁₉H₁₂O₃)ₙ',
    cru: '–[O–C₆H₄–O–C₆H₄–CO–C₆H₄]ₙ–',
    monomer: '4,4′-Difluorobenzophenone + Hydroquinone (Diphenolate salt)',
    polymerizationType: 'Step-Growth Nucleophilic Aromatic Substitution (SNAr) in Diphenyl Sulfone',
    classification: 'Ultra-High Performance Engineering Polymer, Semi-Crystalline (30–35%)',
    functionalGroup: 'Aromatic Ether Linkages (–Ar–O–Ar–) and Carbonyl Ketone Bridge (–Ar–CO–Ar–)',
    howFormed: 'Hydroquinone and difluorobenzophenone react in high-boiling polar solvent (diphenyl sulfone) at 300–320°C in the presence of anhydrous potassium carbonate, driving step-growth nucleophilic substitution with KF elimination.',
    tg: '143°C',
    tm: '343°C (Continuous service temperature: 250°C)',
    density: '1.300 – 1.320 g/cm³',
    tensileStrength: '95 – 105 MPa (Unfilled) / 190 MPa (Carbon-Fiber Reinforced)',
    indianBrands: ['Victrex PEEK', 'Solvay KetaSpire', 'Evonik VESTAKEEP'],
    topApplications: ['Aerospace brackets & engine nacelle components', 'Spinal fusion cages & orthopedic biocompatible implants', 'Oil & gas downhole electrical connectors & valve seals'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Analyze the chemical resistance of PEEK in aggressive solvent environments (hydrocarbons, steam, acids) and its exceptional gamma-ray sterilization stability.'
  },
  m10: {
    id: 'm10',
    name: 'Polyurethane (PU / PUR)',
    abbreviation: 'PU / TPU',
    category: 'Molecule',
    model_type: 'molecule_polyurethane',
    iupacName: 'Poly(carbamic ester)',
    casNumber: '9009-54-5',
    formula: '(C₁₅H₂₂N₂O₅)ₙ',
    cru: '–[O–R–O–CO–NH–R′–NH–CO]ₙ–',
    monomer: 'Diisocyanate (MDI/TDI) + Polyol (Polyether/Polyester diol) + Chain Extender (BDO)',
    polymerizationType: 'Step-Growth Addition (Polyaddition without small molecule byproduct)',
    classification: 'Thermoset or Thermoplastic Elastomer (Block Copolymer: Hard & Soft Domains)',
    functionalGroup: 'Urethane Linkage (–NH–COO–)',
    howFormed: 'The electrophilic carbon of an isocyanate group (–N=C=O) reacts with the nucleophilic hydroxyl (–OH) of a polyol via hydrogen transfer, forming urethane linkages without eliminating water or volatile byproducts.',
    tg: '–50°C (Soft segment) / +100°C (Hard segment)',
    tm: '180°C to 220°C (TPU melting range)',
    density: '0.030 g/cm³ (Flexible foam) to 1.250 g/cm³ (Solid elastomer)',
    tensileStrength: '25 – 60 MPa',
    indianBrands: ['Covestro Desmodur/Baydur', 'BASF Lupranat/Elastollan', 'Dow Voranol'],
    topApplications: ['Automotive seating foam & instrument panels', 'High-abrasion athletic shoe outsoles (TPU)', 'Thermal insulation panels in refrigerators & building envelopes'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain how the stoichiometry of MDI diisocyanate, polyether polyol, and butane-1,4-diol chain extender governs microphase separation in TPU.'
  },
  m11: {
    id: 'm11',
    name: 'Polylactic Acid (PLA)',
    abbreviation: 'PLA / PLLA',
    category: 'Molecule',
    model_type: 'molecule_pla',
    iupacName: 'Poly(2-hydroxypropanoic acid) / Poly(lactic acid)',
    casNumber: '26100-51-6',
    formula: '(C₃H₄O₂)ₙ',
    cru: '–[CH(CH₃)–CO–O]ₙ–',
    monomer: 'L-Lactide (Cyclic dimer from fermented corn starch / sugarcane)',
    polymerizationType: 'Ring-Opening Polymerization (ROP) catalyzed by Stannous Octoate',
    classification: 'Biodegradable Aliphatic Polyester, Bio-based Thermoplastic',
    functionalGroup: 'Aliphatic Ester Linkage (–CH(CH₃)–COO–)',
    howFormed: 'Lactic acid obtained from carbohydrate bacterial fermentation is dimerized into cyclic lactide. High-purity L-lactide undergoes coordination-insertion ring-opening polymerization catalyzed by tin(II) octoate to yield high-molecular-weight Poly(L-lactic acid).',
    tg: '55°C to 65°C',
    tm: '155°C to 175°C',
    density: '1.240 – 1.260 g/cm³',
    tensileStrength: '50 – 65 MPa',
    indianBrands: ['NatureWorks Ingeo', 'Total Corbion Luminy', 'Ecoware India'],
    topApplications: ['FDM desktop 3D printing filament', 'Compostable cold beverage cups & food packaging', 'Absorbable surgical sutures & bone fixation pins'],
    curriculumLessonUrl: '/subjects/sustainable-plastics',
    aiPrompt: 'Explain the industrial composting degradation mechanism of PLA at 58°C via abiotic ester hydrolysis followed by microbial bio-assimilation.'
  },
  m12: {
    id: 'm12',
    name: 'Polyhydroxyalkanoate (PHA / PHB)',
    abbreviation: 'PHA / PHB / PHBV',
    category: 'Molecule',
    model_type: 'molecule_pha',
    iupacName: 'Poly(3-hydroxybutanoate)',
    casNumber: '26063-00-3',
    formula: '(C₄H₆O₂)ₙ',
    cru: '–[CH(CH₃)–CH₂–CO–O]ₙ–',
    monomer: '3-Hydroxybutyric acid (Biosynthesized by bacteria via acetyl-CoA)',
    polymerizationType: 'In-Vivo Microbial Biosynthesis (Enzymatic Polycondensation via PHA Synthase)',
    classification: '100% Bio-Based, Marine & Soil Degradable Aliphatic Polyester',
    functionalGroup: 'Aliphatic Linear Ester (–CH(R)–CH₂–COO–)',
    howFormed: 'Bacteria (such as Cupriavidus necator) accumulate PHA granules inside their cytoplasm as an energy storage reserve under nutrient-limited (nitrogen/phosphorus) conditions with excess carbon feed. The polymer is extracted and purified solvent-free.',
    tg: '2°C to 5°C',
    tm: '170°C to 180°C',
    density: '1.250 g/cm³',
    tensileStrength: '35 – 45 MPa',
    indianBrands: ['Danimer Scientific Nodax', 'TianAn Biopolymer Enmat', 'Kaneka Green Planet'],
    topApplications: ['Marine-biodegradable agricultural mulch films', 'Single-use marine-safe straws & coatings', 'Slow-release drug delivery capsules'],
    curriculumLessonUrl: '/subjects/sustainable-plastics',
    aiPrompt: 'Compare the enzymatic biodegradation of PHA in natural seawater versus ambient soil and describe the role of extracellular PHA depolymerases.'
  },
  m13: {
    id: 'm13',
    name: 'Acrylonitrile Butadiene Styrene (ABS)',
    abbreviation: 'ABS',
    category: 'Molecule',
    model_type: 'molecule_abs',
    iupacName: 'Poly(acrylonitrile-co-butadiene-co-styrene)',
    casNumber: '9003-56-9',
    formula: '(C₈H₈)ₓ·(C₄H₆)ᵧ·(C₃H₃N)ᵤ',
    cru: 'Terpolymer blend of SAN matrix grafted onto Polybutadiene rubber cores',
    monomer: 'Acrylonitrile (15–35%) + 1,3-Butadiene (5–30%) + Styrene (40–60%)',
    polymerizationType: 'Emulsion / Continuous Mass Graft Copolymerization',
    classification: 'Engineering Thermoplastic, Multiphase Rubber-Toughened Terpolymer',
    functionalGroup: 'Nitrile (–C≡N), Conjugated Diene (–C=C–), and Phenyl Aromatic Rings',
    howFormed: 'Polybutadiene rubber latex particles are prepared by emulsion polymerization. Styrene and acrylonitrile monomers are then added with peroxide initiators, grafting SAN copolymer chains onto the rubber surface while polymerizing the continuous SAN matrix.',
    tg: '105°C',
    tm: 'Amorphous (No crystalline Tm; Processed at 220–250°C)',
    density: '1.030 – 1.060 g/cm³',
    tensileStrength: '40 – 55 MPa',
    indianBrands: ['INEOS Styrolution Absolac', 'Supreme ABS', 'LG Chem ABS', 'SABIC Cycolac'],
    topApplications: ['Automotive radiator grilles & interior bezels', 'Consumer electronics & laptop housings', 'LEGO building bricks & safety helmet shells (IS 4151)'],
    curriculumLessonUrl: '/subjects/polymer-testing',
    aiPrompt: 'Explain the craze-initiation and shear-yielding toughening mechanism of polybutadiene rubber domains in an ABS matrix.'
  },
  m14: {
    id: 'm14',
    name: 'Polymethyl Methacrylate (PMMA)',
    abbreviation: 'PMMA / Acrylic',
    category: 'Molecule',
    model_type: 'molecule_pmma',
    iupacName: 'Poly(methyl 2-methylpropenoate) / Poly(methyl methacrylate)',
    casNumber: '9011-14-7',
    formula: '(C₅H₈O₂)ₙ',
    cru: '–[CH₂–C(CH₃)(COOCH₃)]ₙ–',
    monomer: 'Methyl Methacrylate (MMA), CH₂=C(CH₃)COOCH₃',
    polymerizationType: 'Free-Radical Bulk Cast or Suspension Addition Polymerization',
    classification: 'Thermoplastic, Completely Amorphous Glass, 92% Light Transmission',
    functionalGroup: 'Methacrylate Ester Linkage (–COOCH₃ with α-Methyl Branch)',
    howFormed: 'MMA liquid monomer is mixed with AIBN or benzoyl peroxide initiator in glass cell molds (for cast acrylic sheet) or continuous bulk reactors, polymerizing into optically pure, UV-resistant glassy chains.',
    tg: '105°C',
    tm: 'Amorphous (Softens at ~105°C; Maximum clarity index)',
    density: '1.180 – 1.200 g/cm³',
    tensileStrength: '65 – 75 MPa',
    indianBrands: ['Röhm Plexiglas', 'Arkema Altuglas', 'Sumitomo Sumipex', 'Mitsubishi Acrylite'],
    topApplications: ['Automotive tail-lamp lenses & light-guides', 'Commercial illuminated signboards & display panels', 'Aircraft canopies & aquarium observation windows'],
    curriculumLessonUrl: '/subjects/polymer-testing',
    aiPrompt: 'Explain why PMMA possesses superior UV solar resistance compared to polycarbonate and does not yellow outdoors without UV stabilizers.'
  },
  m15: {
    id: 'm15',
    name: 'Polyoxymethylene (POM / Acetal)',
    abbreviation: 'POM / Polyacetal / Delrin',
    category: 'Molecule',
    model_type: 'molecule_pom',
    iupacName: 'Poly(oxymethylene) / Poly(formaldehyde)',
    casNumber: '9002-81-7',
    formula: '(CH₂O)ₙ',
    cru: '–[CH₂–O]ₙ–',
    monomer: 'Anhydrous Formaldehyde (Homopolymer) or Trioxane + Dioxolane (Copolymer)',
    polymerizationType: 'Anionic / Cationic Coordination Ring-Opening Addition Polymerization',
    classification: 'Engineering Thermoplastic, Highly Crystalline (75–85%), Self-Lubricating',
    functionalGroup: 'Polyether / Acetal Backbone (–C–O–C– Repeating Units)',
    howFormed: 'Purified anhydrous formaldehyde is polymerized with tertiary amine catalysts and end-capped with acetic anhydride (homopolymer), or trioxane is copolymerized with cyclic ethers (copolymer) to prevent thermal unzipping.',
    tg: '–60°C',
    tm: '175°C (Homopolymer) / 165°C (Copolymer)',
    density: '1.410 – 1.425 g/cm³',
    tensileStrength: '65 – 75 MPa',
    indianBrands: ['DuPont Delrin', 'Celanese Hostaform', 'Mitsubishi Iupital', 'Polyplastics Duracon'],
    topApplications: ['Precision mechanical gears & watch escapements', 'Automotive fuel pump modules & sender units', 'Conveyor belt drive links & zipper teeth'],
    curriculumLessonUrl: '/subjects/polymer-processing',
    aiPrompt: 'Explain the mechanism of thermal formaldehyde unzipping in uncapped POM and how cyclic ether comonomers halt degradation.'
  },
  m16: {
    id: 'm16',
    name: 'Nylon 6 (Polyamide 6)',
    abbreviation: 'PA6',
    category: 'Molecule',
    model_type: 'molecule_pa6',
    iupacName: 'Poly(hexano-6-lactam) / Poly(imino(1-oxohexane-1,6-diyl))',
    casNumber: '25038-54-4',
    formula: '(C₆H₁₁NO)ₙ',
    cru: '–[NH–(CH₂)₅–CO]ₙ–',
    monomer: 'ε-Caprolactam',
    polymerizationType: 'Hydrolytic Ring-Opening Polymerization (ROP)',
    classification: 'Engineering Thermoplastic, Semi-Crystalline (40–50%), High Impact Toughness',
    functionalGroup: 'Aliphatic Amide Linkage (–CO–NH–)',
    howFormed: 'Caprolactam is heated to 250–270°C with 2–5% water in a continuous VK tube reactor. Hydrolysis opens the ring into aminocaproic acid, which initiates rapid step-growth ring-opening chain propagation.',
    tg: '45°C to 50°C',
    tm: '215°C to 225°C',
    density: '1.130 – 1.140 g/cm³',
    tensileStrength: '70 – 85 MPa',
    indianBrands: ['SRF Tufnyl', 'BASF Ultramid B', 'DOMO Domamid 6', 'Gujarat State Fertilizers (GSFC)'],
    topApplications: ['Power tool housings & industrial fan blades', 'Monofilament fishing nets & industrial cords', 'Automotive engine acoustic covers'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Compare Nylon 6 vs Nylon 66 in terms of crystalline packing, melting temperature (220°C vs 260°C), and water absorption.'
  },
  m17: {
    id: 'm17',
    name: 'Polybutylene Terephthalate (PBT)',
    abbreviation: 'PBT',
    category: 'Molecule',
    model_type: 'molecule_pbt',
    iupacName: 'Poly(oxybutane-1,4-diyloxyterephthaloyl)',
    casNumber: '26062-94-2',
    formula: '(C₁₂H₁₂O₄)ₙ',
    cru: '–[CO–C₆H₄–CO–O–(CH₂)₄–O]ₙ–',
    monomer: '1,4-Butanediol (BDO) + Dimethyl Terephthalate (DMT) / PTA',
    polymerizationType: 'Melt Transesterification Polycondensation',
    classification: 'Engineering Thermoplastic, Fast-Crystallizing Polyester',
    functionalGroup: 'Aromatic Polyester with 4-Carbon Flexible Tetramethylene Spacer',
    howFormed: 'BDO and DMT undergo transesterification catalyzed by tetrabutyl titanate at 160–240°C with methanol removal, followed by vacuum polycondensation. The 4-carbon spacer allows rapid mold crystallization.',
    tg: '45°C to 55°C',
    tm: '223°C to 228°C',
    density: '1.310 – 1.350 g/cm³',
    tensileStrength: '55 – 65 MPa (Unfilled) / 140 MPa (30% Glass Filled)',
    indianBrands: ['SABIC Valox', 'BASF Ultradur', 'Celanese Celanex', 'DuPont Crastin'],
    topApplications: ['Automotive sensor connectors & distributor caps', 'Electronic keyboard keycaps & socket housings', 'Appliance handles & ignition components'],
    curriculumLessonUrl: '/subjects/polymer-processing',
    aiPrompt: 'Explain why PBT is preferred over PET for fast-cycle precision injection molding of automotive electrical connectors.'
  },
  m18: {
    id: 'm18',
    name: 'Polysulfone (PSU)',
    abbreviation: 'PSU',
    category: 'Molecule',
    model_type: 'molecule_psu',
    iupacName: 'Poly(oxy-1,4-phenylenesulfonyl-1,4-phenyleneoxy-1,4-phenyleneisopropylidene-1,4-phenylene)',
    casNumber: '25135-51-7',
    formula: '(C₂₇H₂₂O₄S)ₙ',
    cru: '–[C₆H₄–C(CH₃)₂–C₆H₄–O–C₆H₄–SO₂–C₆H₄–O]ₙ–',
    monomer: 'Bisphenol-A + 4,4′-Dichlorodiphenyl Sulfone',
    polymerizationType: 'Nucleophilic Aromatic Step-Growth Polycondensation',
    classification: 'High-Temperature Amorphous Engineering Polymer, Autoclave-Sterilizable',
    functionalGroup: 'Sulfonyl Linkage (–SO₂–) & Ether Bonds between Phenyl Rings',
    howFormed: 'Disodium bisphenolate reacts with 4,4′-dichlorodiphenyl sulfone in dimethyl sulfoxide (DMSO) at 160–180°C. The strongly electron-withdrawing sulfone group activates the aromatic chlorines for nucleophilic displacement.',
    tg: '185°C to 190°C',
    tm: 'Amorphous (Heat deflection temperature: 174°C)',
    density: '1.240 – 1.250 g/cm³',
    tensileStrength: '70 – 80 MPa',
    indianBrands: ['Solvay Udel', 'BASF Ultrason S'],
    topApplications: ['Autoclavable surgical instrument trays', 'Dialysis filtration membrane modules', 'Aircraft cabin beverage service carts & plumbing fittings'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain the resonance stabilization of the sulfone group in PSU and why it withstands repeated 134°C steam autoclave sterilization.'
  },
  m19: {
    id: 'm19',
    name: 'Polyetherimide (PEI / Ultem)',
    abbreviation: 'PEI / Ultem',
    category: 'Molecule',
    model_type: 'molecule_pei',
    iupacName: 'Poly(2-(4-(4-(4-(1,3-dioxo-1,3-dihydro-2H-isoindol-2-yl)phenoxy)phenyl)propan-2-yl)isoindoline-1,3-dione)',
    casNumber: '61128-46-9',
    formula: '(C₃₇H₂₄N₂O₆)ₙ',
    cru: 'Polyimide backbone with flexible ether linkages and Bisphenol-A spacers',
    monomer: 'Bisphenol-A Dianhydride (BPADA) + m-Phenylenediamine (m-PDA)',
    polymerizationType: 'Two-Stage Polycondensation (Polyamide acid intermediate followed by imidization)',
    classification: 'High-Temperature Amorphous Polyetherimide, Inherently Flame Retardant (LOI: 47%)',
    functionalGroup: 'Cyclic Imide Rings (–CO–N–CO–) and Ether Linkages (–O–)',
    howFormed: 'BPADA reacts with m-PDA in high-boiling solvent at 150–180°C to generate polyamic acid, which is thermally cyclized (dehydrated) at 250–300°C to lock in rigid planar imide rings.',
    tg: '217°C',
    tm: 'Amorphous (Continuous service at 170°C, UL94 V-0 at 0.4 mm)',
    density: '1.270 – 1.280 g/cm³',
    tensileStrength: '105 – 115 MPa',
    indianBrands: ['SABIC Ultem 1000 / 2300'],
    topApplications: ['Aircraft interior air/fuel ducting (FAA FAR 25.853 compliant)', 'High-temperature burn-in semiconductor sockets', 'High-temp FDM 3D printing filaments for aerospace'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain why Ultem PEI has an inherently high Limiting Oxygen Index (LOI 47%) and passes stringent aerospace smoke-toxicity tests without halogenated flame retardants.'
  },
  m20: {
    id: 'm20',
    name: 'Liquid Crystal Polymer (LCP)',
    abbreviation: 'LCP',
    category: 'Molecule',
    model_type: 'molecule_lcp',
    iupacName: 'Poly(4-hydroxybenzoate-co-6-hydroxy-2-naphthoate)',
    casNumber: '70679-91-1',
    formula: '(C₁₄H₁₀O₄)ₙ',
    cru: 'Aromatic polyester rigid-rod copolymer of HBA and HNA',
    monomer: '4-Hydroxybenzoic Acid (HBA) + 6-Hydroxy-2-naphthoic Acid (HNA)',
    polymerizationType: 'Melt Acidolysis Polycondensation with Acetic Acid Elimination',
    classification: 'Thermotropic Liquid Crystalline Polyester, Zero Shrinkage in Flow Direction',
    functionalGroup: 'Rigid Mesogenic Aromatic Ester Linkages (Nematic Liquid Crystal Phase)',
    howFormed: 'Acetylated HBA and HNA monomers are melt-polymerized at 300–350°C. In the melt, rigid aromatic rods spontaneously align into nematic domains, providing ultra-low melt viscosity for filling 0.1 mm wall thicknesses.',
    tg: '110°C to 130°C',
    tm: '280°C to 350°C',
    density: '1.400 – 1.620 g/cm³',
    tensileStrength: '130 – 180 MPa',
    indianBrands: ['Celanese Vectra', 'Solvay Xydar', 'Sumitomo Sumikasuper'],
    topApplications: ['5G smartphone high-frequency micro-connectors', 'SMT surface-mount electronics sockets withstanding 260°C reflow soldering', 'Fiber optic splice sleeves'],
    curriculumLessonUrl: '/subjects/polymer-processing',
    aiPrompt: 'Explain how the nematic molecular alignment of LCP in the melt enables injection molding of 0.15 mm ultra-thin walls without weld-line weakness.'
  },
  m21: {
    id: 'm21',
    name: 'Epoxy Resin (DGEBA)',
    abbreviation: 'Epoxy / DGEBA',
    category: 'Molecule',
    model_type: 'molecule_epoxy',
    iupacName: 'Diglycidyl ether of bisphenol-A',
    casNumber: '25068-38-6',
    formula: '(C₂₁H₂₄O₄)ₙ',
    cru: 'Crosslinked 3D network formed with polyamines or anhydrides',
    monomer: 'Bisphenol-A + Epichlorohydrin (crosslinked with TETA/DETA)',
    polymerizationType: 'Step-Growth Ring-Opening Crosslinking Addition (Thermosetting Cure)',
    classification: 'Thermoset Resin, High-Modulus Structural Composite Matrix',
    functionalGroup: 'Terminal Epoxide (Oxirane) Rings & Secondary Hydroxyls (–OH)',
    howFormed: 'Bisphenol-A reacts with epichlorohydrin in base to synthesize DGEBA prepolymer. When mixed with an amine hardener, active amine hydrogens open the strained three-membered oxirane rings, generating an infusible 3D crosslinked network.',
    tg: '120°C to 180°C (Post-cured)',
    tm: 'Thermoset (Infusible; Decomposes above 300°C)',
    density: '1.150 – 1.250 g/cm³',
    tensileStrength: '60 – 90 MPa (Neat) / >1200 MPa (Carbon Fiber Prepreg)',
    indianBrands: ['Huntsman Araldite', 'Aditya Birla Chemicals (Epochem)', 'Atul Ltd (Lapox)'],
    topApplications: ['Wind turbine rotor blades & aerospace CFRP composites', 'High-voltage transformer potting & PCB laminates (FR-4)', 'Heavy-duty structural industrial adhesives & protective coatings'],
    curriculumLessonUrl: '/subjects/polymer-composites',
    aiPrompt: 'Detail the stoichiometry of the oxirane-amine curing reaction and calculate the Amine Hydrogen Equivalent Weight (AHEW) needed for 100g of DGEBA.'
  },
  m22: {
    id: 'm22',
    name: 'Bakelite (Phenol-Formaldehyde)',
    abbreviation: 'PF / Novolac / Resole',
    category: 'Molecule',
    model_type: 'molecule_bakelite',
    iupacName: 'Poly(phenol-co-formaldehyde)',
    casNumber: '9003-35-4',
    formula: '(C⇇H₆O)ₙ',
    cru: '3D methylene-bridged phenolic resin network',
    monomer: 'Phenol + Formaldehyde (with Hexamethylenetetramine curing agent)',
    polymerizationType: 'Step-Growth Polycondensation (First fully synthetic plastic, 1907)',
    classification: 'Thermosetting Phenolic Resin, Exceptional Dielectric & Thermal Stability',
    functionalGroup: 'Methylene (–CH₂–) Bridges connecting Hydroxyphenyl Rings',
    howFormed: 'Phenol reacts with formaldehyde under acid catalysis (Novolac) or alkaline catalysis (Resole). In compression mold tooling at 160°C under 20 MPa, methylene bridges link ortho- and para-positions into a rigid 3D infusible grid.',
    tg: '>200°C',
    tm: 'Thermoset (Non-melting; chars at >300°C)',
    density: '1.350 – 1.450 g/cm³',
    tensileStrength: '40 – 60 MPa',
    indianBrands: ['Bakelite Hylam India', 'Sundeep Formulations', 'Tipco Phenolics'],
    topApplications: ['Electrical switchgear, sockets & commutators', 'Automotive brake drum linings & clutch friction pads', 'Heavy electrical insulator boards & cookware handles'],
    curriculumLessonUrl: '/subjects/history',
    aiPrompt: 'Explain Leo Baekeland’s heat-and-pressure Bakelizer breakthrough in 1907 that prevented gas bubble voids in phenolic resin compression molding.'
  },
  m23: {
    id: 'm23',
    name: 'Polydimethylsiloxane (Silicone / PDMS)',
    abbreviation: 'PDMS / Silicone / LSR',
    category: 'Molecule',
    model_type: 'molecule_silicone',
    iupacName: 'Poly(dimethylsiloxane)',
    casNumber: '63148-62-9',
    formula: '((CH₃)₂SiO)ₙ',
    cru: '–[Si(CH₃)₂–O]ₙ–',
    monomer: 'Dimethyldichlorosilane, (CH₃)₂SiCl₂',
    polymerizationType: 'Hydrolysis followed by Ring-Opening Polymerization of D4 Cyclic Siloxanes',
    classification: 'Inorganic-Organic Hybrid Polymer, High-Flexibility Silicone Elastomer',
    functionalGroup: 'Inorganic Siloxane Backbone (–Si–O–Si–, 143° bond angle) with Methyl Groups',
    howFormed: 'Dimethyldichlorosilane is hydrolyzed with water to produce cyclic tetramers (D4), which undergo anionic ring-opening polymerization with KOH catalyst and platinum-catalyzed vinyl hydrosilylation crosslinking.',
    tg: '–125°C (Lowest Tg of any commercial elastomer)',
    tm: '–40°C (Remains completely flexible from –60°C to +250°C)',
    density: '0.965 – 1.150 g/cm³',
    tensileStrength: '5 – 12 MPa (High elongation >600%)',
    indianBrands: ['Dow Corning / DOWSIL', 'Wacker Silicones India', 'Momentive Performance Materials'],
    topApplications: ['Medical-grade implants, catheters & infant feeding teats', 'High-temperature automotive gaskets & spark plug boots', 'Architectural structural glazing silicone sealants'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain why the extreme torsional flexibility of the Si-O-Si bond (143° angle) gives PDMS a glass transition temperature of –125°C.'
  },
  m24: {
    id: 'm24',
    name: 'Natural Rubber (cis-1,4-Polyisoprene)',
    abbreviation: 'NR',
    category: 'Molecule',
    model_type: 'molecule_rubber',
    iupacName: 'cis-1,4-Polyisoprene',
    casNumber: '9003-31-0',
    formula: '(C₅H₈)ₙ',
    cru: '–[CH₂–C(CH₃)=CH–CH₂]ₙ–',
    monomer: 'Isoprene (2-Methyl-1,3-butadiene, biosynthesized in Hevea brasiliensis latex)',
    polymerizationType: 'Natural Biosynthesis followed by Sulfur Vulcanization Crosslinking',
    classification: 'Elastomer / Polyene Rubber, Strain-Induced Crystallizing',
    functionalGroup: 'Unsaturated Alkene Double Bonds in cis Configuration',
    howFormed: 'Tapped from the Hevea brasiliensis tree, natural polyisoprene is compounded with zinc oxide, stearic acid, accelerators, and sulfur, then cured at 140–160°C. Sulfur bridges crosslink allylic positions to eliminate plastic flow and create high elastic recovery.',
    tg: '–70°C',
    tm: '28°C (Unvulcanized; Vulcanized is thermoset elastomer)',
    density: '0.920 – 0.940 g/cm³',
    tensileStrength: '20 – 30 MPa (Unfilled, high green strength)',
    indianBrands: ['Indian Rubber Board ISNR grades (ISNR-5, ISNR-20)', 'Apeejay Rubber', 'MRF Rubber'],
    topApplications: ['Heavy truck & aircraft landing gear tire treads', 'Anti-vibration engine mounts & bridge seismic bearings', 'Surgical latex gloves & high-elasticity condoms'],
    curriculumLessonUrl: '/subjects/rubber-technology',
    aiPrompt: 'Detail Charles Goodyear’s sulfur vulcanization reaction mechanism and explain mono-, di-, and polysulfidic crosslink distribution in NR.'
  },
  m25: {
    id: 'm25',
    name: 'Styrene-Butadiene Rubber (SBR)',
    abbreviation: 'SBR / E-SBR / S-SBR',
    category: 'Molecule',
    model_type: 'molecule_sbr',
    iupacName: 'Poly(styrene-co-butadiene)',
    casNumber: '9003-55-8',
    formula: '(C₈H₈)ₓ·(C₄H₆)ᵧ',
    cru: 'Random copolymer of 25% Styrene and 75% 1,3-Butadiene',
    monomer: 'Styrene (23.5%) + 1,3-Butadiene (76.5%)',
    polymerizationType: 'Cold Emulsion (E-SBR at 5°C) or Anionic Solution Polymerization (S-SBR)',
    classification: 'Synthetic General-Purpose Elastomer, High Abrasion Resistance',
    functionalGroup: 'Aromatic Phenyl Rings + Residual 1,4-trans and 1,2-vinyl Double Bonds',
    howFormed: 'Emulsion polymerization at 5°C using redox initiators produces high molecular weight random chains. Solution polymerization with butyl lithium gives precise control over vinyl content for low rolling-resistance tire treads.',
    tg: '–55°C to –50°C',
    tm: 'Amorphous Synthetic Rubber',
    density: '0.940 – 0.960 g/cm³',
    tensileStrength: '15 – 25 MPa (Carbon black reinforced)',
    indianBrands: ['Indian Synthetic Rubber Pvt Ltd (ISRPL Panipat)', 'Reliance SBR', 'RIL Synthetic Elastomers'],
    topApplications: ['Passenger car tire treads & conveyor belting', 'Shoe soles & footwear components', 'Rubber hoses & molded industrial mechanical seals'],
    curriculumLessonUrl: '/subjects/rubber-technology',
    aiPrompt: 'Compare Solution SBR (S-SBR) vs Emulsion SBR (E-SBR) in silica-compounded green tire treads for rolling resistance and wet skid traction.'
  },
  m26: {
    id: 'm26',
    name: 'Ethylene Propylene Diene Monomer (EPDM)',
    abbreviation: 'EPDM',
    category: 'Molecule',
    model_type: 'molecule_epdm',
    iupacName: 'Poly(ethylene-co-propylene-co-ethylidene norbornene)',
    casNumber: '25038-36-2',
    formula: '(C₂H₄)ₓ·(C₃H₆)ᵧ·(C₉H₁₂)ᵤ',
    cru: 'Saturated polyolefin backbone with pendant unsaturated diene crosslinking sites',
    monomer: 'Ethylene (45–75%) + Propylene (20–50%) + ENB / DCPD (3–10%)',
    polymerizationType: 'Ziegler-Natta / Metallocene Solution or Suspension Copolymerization',
    classification: 'Specialty Weather-Resistant Elastomer, Saturated Backbone',
    functionalGroup: 'Saturated Hydrocarbon Backbone with Non-Conjugated Diene Pendants',
    howFormed: 'Ethylene, propylene, and ethylidene norbornene are copolymerized with vanadium or metallocene catalysts. Because the double bond is restricted to the pendant ring, the main chain is fully saturated and impervious to ozone and UV degradation.',
    tg: '–54°C',
    tm: 'Semi-crystalline below 40°C depending on ethylene content',
    density: '0.860 – 0.880 g/cm³ (Lowest density commercial elastomer)',
    tensileStrength: '10 – 20 MPa (Reinforced)',
    indianBrands: ['Arlanxeo Keltan', 'Dow NORDEL EPDM', 'ExxonMobil Vistalon'],
    topApplications: ['Automotive door/window weatherstrip seals & radiator coolant hoses', 'Single-ply roofing waterproofing membranes', 'Electrical cable insulation & appliance vibration dampers'],
    curriculumLessonUrl: '/subjects/rubber-technology',
    aiPrompt: 'Explain why EPDM has superior ozone and UV oxidation resistance compared to Natural Rubber and SBR.'
  },
  m27: {
    id: 'm27',
    name: 'Nitrile Butadiene Rubber (NBR)',
    abbreviation: 'NBR / Nitrile / Buna-N',
    category: 'Molecule',
    model_type: 'molecule_nbr',
    iupacName: 'Poly(acrylonitrile-co-1,4-butadiene)',
    casNumber: '9003-18-3',
    formula: '(C₄H₆)ₓ·(C₃H₃N)ᵧ',
    cru: 'Random copolymer of Acrylonitrile (18–50%) and 1,3-Butadiene',
    monomer: 'Acrylonitrile (ACN) + 1,3-Butadiene',
    polymerizationType: 'Free-Radical Emulsion Polymerization at 5–30°C',
    classification: 'Oil- & Fuel-Resistant Specialty Elastomer',
    functionalGroup: 'Polar Nitrile Groups (–C≡N) on Polyene Chain',
    howFormed: 'Acrylonitrile and butadiene are copolymerized in water with persulfate initiators. The polar nitrile groups repel non-polar hydrocarbon fuels, mineral oils, and hydraulic fluids, preventing swelling.',
    tg: '–40°C (18% ACN) to –10°C (50% ACN)',
    tm: 'Amorphous Synthetic Rubber',
    density: '0.980 – 1.020 g/cm³',
    tensileStrength: '15 – 25 MPa (Reinforced)',
    indianBrands: ['Apcotex Industries Nitrile', 'Arlanxeo Perbunan', 'Zeon Nipol'],
    topApplications: ['Automotive fuel lines, O-rings & hydraulic seals', 'Disposable medical examination gloves (powder-free)', 'Industrial printing rollers & oil-resistant footwear'],
    curriculumLessonUrl: '/subjects/rubber-technology',
    aiPrompt: 'Analyze the trade-off between Acrylonitrile (ACN) content, oil swelling resistance, and low-temperature glass transition (Tg) in NBR.'
  },
  m28: {
    id: 'm28',
    name: 'Polychloroprene (Neoprene / CR)',
    abbreviation: 'CR / Neoprene / Baypren',
    category: 'Molecule',
    model_type: 'molecule_neoprene',
    iupacName: 'Poly(2-chlorobuta-1,3-diene) / Poly(chloroprene)',
    casNumber: '9010-98-4',
    formula: '(C₄H₅Cl)ₙ',
    cru: '–[CH₂–C(Cl)=CH–CH₂]ₙ– (Predominantly trans-1,4)',
    monomer: 'Chloroprene (2-Chloro-1,3-butadiene), CH₂=C(Cl)–CH=CH₂',
    polymerizationType: 'Free-Radical Aqueous Emulsion Polymerization with Metal Oxide Cure',
    classification: 'Flame-Retardant Specialty Synthetic Rubber (Cured with ZnO / MgO)',
    functionalGroup: 'Allylic Chlorine Atom on Unsaturated Alkene Backbone',
    howFormed: 'Chloroprene is emulsion-polymerized at 40°C. Unlike other rubbers, crosslinking is achieved by heating with zinc oxide and magnesium oxide (metal oxides) that abstract reactive allylic chlorines.',
    tg: '–40°C to –45°C',
    tm: '40°C to 45°C (Strain crystallizes rapidly for high green strength)',
    density: '1.230 – 1.250 g/cm³',
    tensileStrength: '20 – 30 MPa (Unfilled tensile is high due to strain crystallization)',
    indianBrands: ['Denka Neoprene', 'Arlanxeo Baypren', 'Showa Denko Chloroprene'],
    topApplications: ['Closed-cell thermal wetsuits & diving gear', 'Automotive timing belts & CV joint bellows', 'Industrial contact adhesives & cable jacketing'],
    curriculumLessonUrl: '/subjects/rubber-technology',
    aiPrompt: 'Explain why polychloroprene is vulcanized using metal oxides (ZnO / MgO) rather than conventional elemental sulfur systems.'
  },
  m29: {
    id: 'm29',
    name: 'Polyvinylidene Fluoride (PVDF)',
    abbreviation: 'PVDF / Kynar',
    category: 'Molecule',
    model_type: 'molecule_pvdf',
    iupacName: 'Poly(1,1-difluoroethylene)',
    casNumber: '24937-79-9',
    formula: '(C₂H₂F₂)ₙ',
    cru: '–[CH₂–CF₂]ₙ–',
    monomer: 'Vinylidene Fluoride (VDF), CH₂=CF₂',
    polymerizationType: 'Free-Radical Aqueous Suspension / Emulsion Addition',
    classification: 'Fluoropolymer with Piezoelectric β-Phase, Extreme Chemical & UV Resistance',
    functionalGroup: 'Alternating Hydrogen (–CH₂–) and Fluorine (–CF₂–) Dipoles',
    howFormed: 'VDF is polymerized under high pressure (10–100 bar) in water. Mechanical stretching of alpha-phase crystal spherulites transforms them into all-trans beta-phase, aligning dipoles to generate strong piezoelectric and pyroelectric properties.',
    tg: '–40°C to –35°C',
    tm: '165°C to 175°C',
    density: '1.750 – 1.780 g/cm³',
    tensileStrength: '45 – 60 MPa',
    indianBrands: ['Gujarat Fluorochemicals (Inoflon PVDF)', 'Arkema Kynar', 'Solvay Solef'],
    topApplications: ['Lithium-ion battery cathode binders (NMC/LFP cells)', 'Ultrafiltration water purification hollow-fiber membranes', 'Architectural long-life fluoropolymer exterior coatings'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain how mechanical stretching transforms non-polar α-phase PVDF into ferroelectric all-trans β-phase for pressure sensor applications.'
  },
  m30: {
    id: 'm30',
    name: 'Polyether Block Amide (PEBA)',
    abbreviation: 'PEBA / PEBAX',
    category: 'Molecule',
    model_type: 'molecule_peba',
    iupacName: 'Poly(tetramethylene oxide-block-caprolactam)',
    casNumber: '77402-38-1',
    formula: 'Block copolymer: [PA]ₓ–[PE]ᵧ',
    cru: 'Hard Polyamide blocks (PA12 or PA6) linked via ester bonds to Soft Polyether blocks (PTMO/PEG)',
    monomer: 'Dicarboxylic Polyamide + Dihydroxylated Polyether diol',
    polymerizationType: 'Melt Polycondensation of Preformed Functionalized Telechelic Oligomers',
    classification: 'High-Energy-Return Thermoplastic Elastomer (TPE-A)',
    functionalGroup: 'Amide Crystallites (Hard Phase) + Polyether Soft Matrix',
    howFormed: 'Telechelic dicarboxylic acid polyamide oligomers and dihydroxy polyether segments react in the melt with titanate catalysts. Phase separation creates crystalline polyamide physical crosslinks inside an elastic polyether matrix.',
    tg: '–60°C to –40°C (Soft phase)',
    tm: '135°C to 175°C (Hard phase melting)',
    density: '1.010 – 1.040 g/cm³',
    tensileStrength: '35 – 55 MPa (Energy return >85%)',
    indianBrands: ['Arkema Pebax', 'Evonik Vestamid E'],
    topApplications: ['Marathon super-shoe nitrogen-infused midsole foam (85%+ energy return)', 'Cardiovascular angiographic catheter balloon tubing', 'High-performance ski boots & athletic sports gear'],
    curriculumLessonUrl: '/subjects/polymer-chemistry',
    aiPrompt: 'Explain how the microphase-separated block morphology of Pebax produces extreme resilience (>85% energy return) in marathon racing shoes.'
  },
}
