// src/lib/predefined_projects.ts

export interface PredefinedProject {
  id: string;
  title: string;
  description: string;
  category: 'foundation' | 'intermediate' | 'advanced' | 'expert';
  difficulty: 'Beginner' | 'Medium' | 'Hard' | 'Expert';
  duration: string;
  skills: string[];
  equipment: string[];
  deliverable: string;
  why_matters: string;
  real_world_app: string;
  curriculum_match: string;
}

export const PREDEFINED_PROJECTS: PredefinedProject[] = [
  // Level 1: Foundation (10)
  {
    id: 'F1',
    title: 'PCR Content Optimization in Blow Molding',
    description: 'Optimize the let-down ratio of Post-Consumer Resin (PCR) in extrusion blow molding to maximize recycled content while maintaining physical bottle performance.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '3-4 weeks',
    skills: ['Blow molding', 'Material blending', 'Property testing'],
    equipment: ['Extrusion blow molder', 'Tensile tester', 'Drop impact tester'],
    deliverable: 'Optimal PCR let-down ratio with cost analysis report.',
    curriculum_match: 'Polymer Processing; Recycling Technology',
    why_matters: 'Meeting industry and environmental mandates to maximize PCR content without losing structural bottle integrity.',
    real_world_app: 'Fast-Moving Consumer Goods (FMCG) packaging design.'
  },
  {
    id: 'F2',
    title: 'Tensile Testing & Stress-Strain Analysis (ASTM D638)',
    description: 'Conduct standard tensile tests on various polymer specimens (PP, PE, PS) and analyze the resulting stress-strain curves.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '1-2 weeks',
    skills: ['Specimen prep', 'Tensile testing', 'Data analysis'],
    equipment: ['Universal testing machine (UTM)', 'Specimen cutter', 'Calipers'],
    deliverable: 'Stress-strain curve mapping Young\'s modulus, yield, and elongation.',
    curriculum_match: 'Polymer Testing',
    why_matters: 'Tensile testing is the primary mechanical quality check in polymer processing.',
    real_world_app: 'Quality control labs in manufacturing facilities.'
  },
  {
    id: 'F3',
    title: 'MFI Measurement & Processability Correlation',
    description: 'Determine Melt Flow Index (MFI) of polymer resins and correlate findings with molecular weight and molecular weight distribution.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '1 week',
    skills: ['MFI testing', 'Melt flow behavior', 'Molecular weight correlation'],
    equipment: ['Melt flow indexer', 'Analytical balance'],
    deliverable: 'Melt flow index profile and processing window estimation.',
    curriculum_match: 'Polymer Testing',
    why_matters: 'MFI controls the flow and processing temperature targets of plastic extrusion plants.',
    real_world_app: 'Resin manufacturing batch release and incoming resin validation.'
  },
  {
    id: 'F4',
    title: 'Natural Rubber Compounding & Vulcanization',
    description: 'Formulate natural rubber compound with vulcanizing agents and measure cure properties using Mooney viscometer.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '2-3 weeks',
    skills: ['Compounding', 'Two-roll milling', 'Vulcanization analysis'],
    equipment: ['Two-roll mill', 'Mooney viscometer', 'Hydraulic press'],
    deliverable: 'Curing curves showing optimum vulcanization times and physical samples.',
    curriculum_match: 'Rubber Technology',
    why_matters: 'Vulcanization transitions elastomer compounds from plastic to highly elastic solids.',
    real_world_app: 'Tire manufacturing, seals, gaskets, and shock absorbers.'
  },
  {
    id: 'F5',
    title: 'Starch-Based Bioplastic Synthesis & Film Casting',
    description: 'Synthesize starch-based biodegradable plastics using glycerol plasticizers and evaluate biodegradation rates under soil burial conditions.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '2 weeks',
    skills: ['Biopolymer synthesis', 'Film casting', 'Biodegradability testing'],
    equipment: ['Hot plate stirrer', 'Glass molds', 'Soil burial chamber'],
    deliverable: 'Film samples with mapped tensile strength and biodegradation timeline.',
    curriculum_match: 'Sustainable Plastics',
    why_matters: 'Bioplastics address environmental packaging waste and rely on renewable starch feedstocks.',
    real_world_app: 'Single-use biodegradable carry bags and agro-mulch films.'
  },
  {
    id: 'F6',
    title: 'Design of a Simple Injection Mold (CAD)',
    description: 'Create a 3D CAD design for a single-cavity injection mold including gate, runner, and basic cooling lines.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '2-3 weeks',
    skills: ['CAD design', 'Mold flow principles', 'Tooling draft analysis'],
    equipment: ['CAD software (SolidWorks/NX)', 'Moldflow advisor'],
    deliverable: '3D CAD assembly files and draft analysis reports.',
    curriculum_match: 'Mould Design',
    why_matters: 'Accurate draft and runner design prevent part ejection failures and minimize defects.',
    real_world_app: 'Injection molding tool design and die-making industry.'
  },
  {
    id: 'F7',
    title: 'Shore Hardness Testing & Material Identification',
    description: 'Determine hardness of rubbers, elastomers, and rigid plastics using Shore A and Shore D durometers.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '1 week',
    skills: ['Hardness testing', 'Durometer operation', 'Material classification'],
    equipment: ['Shore A durometer', 'Shore D durometer', 'Calipers'],
    deliverable: 'Hardness spectrum database of commonly processed engineering polymers.',
    curriculum_match: 'Polymer Testing',
    why_matters: 'Hardness correlates with elastic modulus and surface durability.',
    real_world_app: 'QC testing for seals, O-rings, shoe soles, and automotive dashboard trims.'
  },
  {
    id: 'F8',
    title: 'Blown Film Extrusion Process Observation',
    description: 'Observe blown film line dynamics, analyze bubble stability, and evaluate the effect of blow-up ratio (BUR) on film orientation.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '2 weeks',
    skills: ['Film extrusion', 'Bubble stability analysis', 'Anisotropy check'],
    equipment: ['Blown film line', 'Thickness micrometer', 'Polariscope'],
    deliverable: 'Processing checklist and film orientation study under varying BUR values.',
    curriculum_match: 'Polymer Processing',
    why_matters: 'Blown film extrusion is the primary method for high-volume plastic film manufacturing.',
    real_world_app: 'Packaging industry producing grocery sacks and food laminates.'
  },
  {
    id: 'F9',
    title: 'Single Screw Extruder Operation & Screw Design',
    description: 'Study feeding, compression, and metering zones of an extruder screw and determine throughput changes under varying back pressures.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '2 weeks',
    skills: ['Extrusion operation', 'Screw metering calculations', 'Melt quality evaluation'],
    equipment: ['Single screw extruder', 'Pressure transducers', 'Die orifice'],
    deliverable: 'Output vs screw RPM curves mapping shear-heating effects.',
    curriculum_match: 'Polymer Processing',
    why_matters: 'Understanding extrusion limits is key to maintaining dimensional control in profiles.',
    real_world_app: 'Extruding window profiles, pipes, and wire coatings.'
  },
  {
    id: 'F10',
    title: 'FTIR Polymer Identification',
    description: 'Identify unknown polymer samples (HDPE, LDPE, PP, PS, PET) by analyzing vibrational spectrum peaks via FTIR.',
    category: 'foundation',
    difficulty: 'Beginner',
    duration: '1-2 weeks',
    skills: ['Spectrometer operation', 'FTIR spectrum analysis', 'Functional group mapping'],
    equipment: ['FTIR Spectrometer', 'ATR accessory'],
    deliverable: 'Polymer identification report with peak matching indexes.',
    curriculum_match: 'Polymer Testing',
    why_matters: 'FTIR is the primary chemical identification test for forensic failure analysis.',
    real_world_app: 'Recycled plastics sorting and incoming materials quality control.'
  },

  // Level 2: Intermediate (15)
  {
    id: 'I1',
    title: 'Injection Molding Process Optimization (Design of Experiments)',
    description: 'Apply Design of Experiments (DOE) to determine optimum injection speed, hold pressure, and cooling times for PP flat plaque production.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Design of Experiments (DOE)', 'Scientific molding', 'Defect mitigation'],
    equipment: ['Injection molding machine', 'Melt temp sensors', 'Part dimensions jig'],
    deliverable: 'DOE statistical analysis sheets and optimized processing window card.',
    curriculum_match: 'Polymer Processing',
    why_matters: 'Minimizes cooling cycles and eliminates common molding defects like warpage and sink marks.',
    real_world_app: 'High-volume production lines for automotive and consumer parts.'
  },
  {
    id: 'I2',
    title: 'PLA/PBS Blend Formulation for Ductility Improvement',
    description: 'Blend Poly(lactic acid) (PLA) with Poly(butylene succinate) (PBS) via twin-screw compounding to improve impact resistance and elongation.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Melt compounding', 'Ductilizing blends', 'Mechanical analysis'],
    equipment: ['Twin-screw extruder', 'Injection molder', 'Izod impact tester'],
    deliverable: 'Mechanical property graphs detailing blend composition optimization.',
    curriculum_match: 'Sustainable Plastics; Composites',
    why_matters: 'PLA has excellent stiffness but is brittle; PBS blending expands its packaging applications.',
    real_world_app: 'Durable bioplastic cutlery and flexible eco-friendly packaging.'
  },
  {
    id: 'I3',
    title: 'PET Chemical Recycling via Glycolysis',
    description: 'Depolymerize post-consumer PET bottles using ethylene glycol and a zinc acetate catalyst to recover bis(2-hydroxyethyl) terephthalate (BHET) monomer.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Chemical recycling', 'Monomer crystallization', 'Yield calculation'],
    equipment: ['Stirred reactor', 'Reflux condenser', 'Filtration setup'],
    deliverable: 'Crystalline BHET monomer sample with FTIR confirmation.',
    curriculum_match: 'Recycling Technology',
    why_matters: 'Glycolysis enables true closed-loop recycling of color-contaminated PET back to virgin purity.',
    real_world_app: 'Chemical upcycling plants producing textile fibers and rPET resin.'
  },
  {
    id: 'I4',
    title: 'Composite Manufacturing (Compression Molding)',
    description: 'Fabricate glass-fiber reinforced epoxy composites using hand lay-up followed by hot compression molding, and measure fiber volume fraction.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Compression molding', 'Resin infusion', 'Composite testing'],
    equipment: ['Hot hydraulic press', 'Steel frame molds', 'Tensile tester'],
    deliverable: 'GFRP composite laminates with mechanical properties report.',
    curriculum_match: 'Polymer Composites',
    why_matters: 'Polymer composites provide high strength-to-weight ratios essential for structure replacements.',
    real_world_app: 'Wind turbine blades, boat hulls, and automotive hoods.'
  },
  {
    id: 'I5',
    title: 'Injection Molding Simulation (Moldflow) & Experimental Validation',
    description: 'Run numerical gate location and fill simulations for a plastic box, mold the physical part, and compare actual fill patterns with simulation predictions.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['CAE simulation', 'Molding trials', 'Model validation'],
    equipment: ['Moldflow/Moldex3D', 'Injection molder', 'Short shot trials'],
    deliverable: 'Comparison report detailing gate pressure discrepancies.',
    curriculum_match: 'Mould Design; Polymer Processing',
    why_matters: 'Simulation validation reduces tooling modification costs and accelerates product launch.',
    real_world_app: 'CAE engineering firms advising product developers.'
  },
  {
    id: 'I6',
    title: 'Graphene-Reinforced ABS Nanocomposite',
    description: 'Incorporate graphene nanoplatelets into acrylonitrile butadiene styrene (ABS) to improve mechanical strength and electrical conductivity.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Nanocomposite blending', 'Dispersive mixing check', 'UTM analysis'],
    equipment: ['Ultrasonicator', 'Twin-screw extruder', 'Four-point probe tester'],
    deliverable: 'Conductive ABS composite sample with mechanical tensile profiles.',
    curriculum_match: 'Polymer Composites; Additives',
    why_matters: 'Graphene nanoplates provide conductivity and reinforce matrices at low loading percentages.',
    real_world_app: 'ESD protective housings and lightweight EMI shielding packaging.'
  },
  {
    id: 'I7',
    title: 'Blow Molding Process: Effect of PCR on Bottle Properties',
    description: 'Blow mold HDPE bottles with varying ratios of PCR (0-50%) and test environmental stress cracking resistance (ESCR) and top-load strength.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Blow molding', 'ESCR testing', 'Quality inspection'],
    equipment: ['Extrusion blow molder', 'Top load tester', 'ESCR bath'],
    deliverable: 'Property mapping report outlining PCR impact on shelf life.',
    curriculum_match: 'Polymer Processing; Recycling Technology',
    why_matters: 'Ensures bottles do not leak or rupture when containing household chemicals.',
    real_world_app: 'Shampoo and liquid detergent container design.'
  },
  {
    id: 'I8',
    title: 'Rotational Molding Process & Sintering Kinetics',
    description: 'Manufacture LLDPE hollow shapes via rotomolding and determine the effect of oven residence time on bubble removal and sintering kinetics.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Rotomolding operation', 'Bubble morphology', 'Sintering kinetics'],
    equipment: ['Rotomolding oven', 'Optical microscope', 'Part impact tester'],
    deliverable: 'Sintering timeline window mapping impact performance.',
    curriculum_match: 'Polymer Processing',
    why_matters: 'Eliminating voids in rotomolded parts is critical to avoiding environmental stress failures.',
    real_world_app: 'Large chemical storage tanks and septic systems.'
  },
  {
    id: 'I9',
    title: '3D Printing Filament Characterization & Optimization',
    description: 'Extrude customized PLA/starch filament and optimize print parameters (nozzle temp, layer thickness) to minimize part delamination.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Filament extrusion', 'FDM 3D printing', 'Interlayer adhesion check'],
    equipment: ['Desktop filament extruder', 'FDM 3D printer', 'UTM tester'],
    deliverable: 'Optimal print setting cards for custom bioplastic filament.',
    curriculum_match: 'Advanced Processing',
    why_matters: 'Filament diameter tolerances and moisture directly control layer adhesion strength.',
    real_world_app: 'Rapid prototyping and customized additive manufacturing.'
  },
  {
    id: 'I10',
    title: 'Polymer Waste to Fuel via Pyrolysis',
    description: 'Convert mixed plastic waste (PE/PP) into liquid hydrocarbons via thermal cracking in an anaerobic pyrolysis reactor.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '4-6 weeks',
    skills: ['Pyrolysis process', 'Fractional distillation', 'Fuel property analysis'],
    equipment: ['Pyrolysis reactor', 'Distillation column', 'GC-MS'],
    deliverable: 'Liquid fuel sample with GC-MS composition report.',
    curriculum_match: 'Recycling Technology',
    why_matters: 'Provides energy recovery pathway for non-recyclable multi-layered packaging films.',
    real_world_app: 'Waste-to-energy conversion systems.'
  },
  {
    id: 'I11',
    title: 'Glass Fiber Reinforced Polymer (GFRP) Pipe Corrosion Study',
    description: 'Expose GFRP pipe sections to acids, bases, and hydrocarbons and evaluate changes in hoop tensile strength over time.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Chemical aging', 'Hoop stress testing', 'Microscopic inspection'],
    equipment: ['Chemical baths', 'Pipe burst tester', 'Stereo microscope'],
    deliverable: 'Chemical compatibility and degradation charts.',
    curriculum_match: 'Polymer Composites',
    why_matters: 'Ensures composite pipelines do not rupture under harsh oilfield or chemical transit settings.',
    real_world_app: 'Corrosive chemical transit pipelines and sewer lining.'
  },
  {
    id: 'I12',
    title: 'Capillary & Rotational Rheometry Characterization',
    description: 'Characterize LLDPE melt using both capillary and rotational rheometers, compiling a master viscosity curve mapping shear rates from 0.1 to 10,000 s⁻¹.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Capillary testing', 'Dynamic shear testing', 'Cox-Merz rule checking'],
    equipment: ['Capillary rheometer', 'Rotational plate-plate rheometer'],
    deliverable: 'Master flow curve mapping zero-shear viscosity and power-law indexes.',
    curriculum_match: 'Polymer Rheology',
    why_matters: 'Viscosity curves dictate processing pressures and shear-heating limits in processing dies.',
    real_world_app: 'Raw resin specification sheets and process control setups.'
  },
  {
    id: 'I13',
    title: 'EPDM Rubber Compounding for Automotive Seals',
    description: 'Compound EPDM rubber with carbon black, paraffinic oil, and sulfur/accelerator systems to optimize compression set properties.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Rubber compounding', 'Curing chemistry', 'Compression set check'],
    equipment: ['Two-roll mill', 'Compression set fixture', 'Hot vulcanizer press'],
    deliverable: 'Compounded EPDM sample meeting automotive seal standards.',
    curriculum_match: 'Rubber Technology',
    why_matters: 'Automotive door seals must maintain elastic recovery across extreme heat and cold.',
    real_world_app: 'Automotive weatherstrip manufacturing.'
  },
  {
    id: 'I14',
    title: 'Sustainable TPS/PBAT Biocomposite Film',
    description: 'Produce Thermoplastic Starch (TPS) blended with Polybutylene adipate terephthalate (PBAT) films and determine water vapor transmission rates (WVTR).',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Starch modification', 'Film extrusion', 'WVTR testing'],
    equipment: ['Twin-screw extruder', 'Blown film line', 'WVTR testing cup'],
    deliverable: 'Compostable film sample with mapped water barrier performance.',
    curriculum_match: 'Sustainable Plastics',
    why_matters: 'Combining TPS (low cost) with PBAT (high toughness) creates biodegradable retail bags.',
    real_world_app: 'Compostable carry bags and food packaging wraps.'
  },
  {
    id: 'I15',
    title: 'CAD Mold Design with Cooling System Analysis',
    description: 'Design a multi-cavity injection mold featuring conformal cooling channels and run thermal analysis to optimize cycle time.',
    category: 'intermediate',
    difficulty: 'Medium',
    duration: '3-4 weeks',
    skills: ['Conformal cooling CAD', 'Mold heat transfer', 'Tooling analysis'],
    equipment: ['CAD software', 'Moldflow thermal solver'],
    deliverable: 'Mold assembly drawing showing cooling layouts and cycle time savings.',
    curriculum_match: 'Mould Design',
    why_matters: 'Proper cooling channel placement reduces cycle times by up to 30% and prevents warp.',
    real_world_app: 'Tooling design departments inside manufacturing firms.'
  },

  // Level 3: Advanced (15)
  {
    id: 'A1',
    title: 'AI-Integrated Injection Molding Process Optimization',
    description: 'Build a machine learning algorithm in Python (Random Forest/ANN) using sensor pressure data to predict molded part weight and defects in real-time.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Machine learning', 'Python data science', 'Scientific molding'],
    equipment: ['Cavity pressure sensors', 'Molding machine', 'Python IDE'],
    deliverable: 'Predictive algorithm code and dashboard showing defect prediction rates.',
    curriculum_match: 'Polymer Processing; Industry 4.0',
    why_matters: 'Enables smart manufacturing lines to auto-eject defective components without inspection.',
    real_world_app: 'Smart injection molding plants (Industry 4.0).'
  },
  {
    id: 'A2',
    title: 'Carbon Fiber Reinforced Polymer (CFRP) for Aerospace',
    description: 'Fabricate unidirectional carbon fiber/epoxy composites using vacuum bagging in autoclave/oven and evaluate interlaminar shear strength.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Vacuum bagging', 'Autoclave curing', 'Shear strength testing'],
    equipment: ['Vacuum bag system', 'Composite curing oven', 'Short-beam shear UTM'],
    deliverable: 'CFRP laminates with shear stress failure analysis reports.',
    curriculum_match: 'Polymer Composites',
    why_matters: 'Aerospace structural parts require maximum strength-to-weight ratios and defect-free curing.',
    real_world_app: 'Aircraft wings, fuselages, and satellite structures.'
  },
  {
    id: 'A3',
    title: 'Self-Healing Polymer Synthesis & Characterization',
    description: 'Synthesize a cross-linked polyurethane network containing reversible Diels-Alder bonds, and evaluate scratch-healing efficiency under thermal stimulus.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Diels-Alder synthesis', 'Dynamic chemistries', 'Crack healing analysis'],
    equipment: ['Chemical synthesis reactor', 'DSC analyzer', 'Hot stage microscope'],
    deliverable: 'Self-healing polymer samples and microscopic healing rate logs.',
    curriculum_match: 'Polymer Chemistry; Advanced Materials',
    why_matters: 'Extends material lifetime, reducing repair needs in high-value components.',
    real_world_app: 'Scratch-resistant automotive coatings and durable electronics housings.'
  },
  {
    id: 'A4',
    title: 'Chemical Recycling of PET via Depolymerization',
    description: 'Depolymerize post-consumer PET bottles using glycolysis under varying catalyst conditions and evaluate BHET purity.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '6-8 weeks',
    skills: ['Depolymerization', 'Monomer purification', 'HPLC calibration'],
    equipment: ['Reaction vessel', 'Rotary evaporator', 'HPLC system'],
    deliverable: 'BHET crystals with detailed purity analysis chromatograms.',
    curriculum_match: 'Recycling Technology',
    why_matters: 'Provides feedstocks for repolymerization to produce food-grade recycled PET.',
    real_world_app: 'Industrial recycling facilities producing circular packaging.'
  },
  {
    id: 'A5',
    title: 'Electrospun Nanofiber Membrane for Biomedical Application',
    description: 'Fabricate polycaprolactone (PCL) nanofiber scaffolds using electrospinning and characterize fiber diameter distribution for tissue engineering.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Electrospinning setup', 'Nanofiber morphology', 'Porosity optimization'],
    equipment: ['Electrospinning unit', 'Scanning Electron Microscope (SEM)', 'UTM'],
    deliverable: 'Nanofiber scaffold membranes with SEM fiber size analysis.',
    curriculum_match: 'Medical Plastics; Nanotechnology',
    why_matters: 'Electrospun scaffolds mimic extracellular matrices, supporting cell growth and wound healing.',
    real_world_app: 'Artificial skin scaffolds and tissue repair matrices.'
  },
  {
    id: 'A6',
    title: 'Injection Molding Defect Analysis & Resolution Guide',
    description: 'Investigate causes of weld lines, flash, warpage, and silver streaks in ABS molding trials, detailing root-cause fixes.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '6-8 weeks',
    skills: ['Failure troubleshooting', 'Root cause study', 'Melt front analysis'],
    equipment: ['Injection molder', 'Optical microscope', 'Polarized light viewer'],
    deliverable: 'Defect diagnostics handbook covering processing parameter remedies.',
    curriculum_match: 'Polymer Processing; Quality Management',
    why_matters: 'Troubleshooting defects on the plant floor is a key engineering operational requirement.',
    real_world_app: 'QC and molding plant operations.'
  },
  {
    id: 'A7',
    title: 'Design & Build an Injection Mold (Advanced)',
    description: 'Design a two-plate mold for a plastic cover featuring side cores/slides, machine the cavity inserts on CNC, and conduct test molding trials.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Mold machining', 'CNC milling', 'Molding tryouts'],
    equipment: ['CAD/CAM software', 'CNC milling machine', 'Injection molder'],
    deliverable: 'Machined mold core/cavity inserts and physical molded samples.',
    curriculum_match: 'Mould Design',
    why_matters: 'Hands-on mold construction links design theory directly with machining limits.',
    real_world_app: 'Toolmaking and contract molding houses.'
  },
  {
    id: 'A8',
    title: 'Frontal Polymerization-Enabled 3D Printing',
    description: 'Formulate dicyclopentadiene (DCPD) resin with Grubbs catalyst to enable low-energy frontal polymerization 3D printing of thermoset shapes.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Ring-opening polymerization', 'Thermoset 3D printing', 'Reaction fronts control'],
    equipment: ['Modified 3D printer', 'Infrared camera', 'Chemical hood'],
    deliverable: 'Printed thermoset samples with frontal velocity characterization.',
    curriculum_match: 'Advanced Processing; Composites',
    why_matters: 'Saves energy compared to traditional thermal curing methods in autoclaves.',
    real_world_app: 'Low-energy manufacturing of wind turbine parts.'
  },
  {
    id: 'A9',
    title: 'Sustainable Packaging: Smart Polymers',
    description: 'Develop low-density polyethylene (LDPE) packaging films incorporating natural pH-indicator dyes that change color when food spoilage occurs.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Extrusion coating', 'Active dye blending', 'Spoilage validation'],
    equipment: ['Cast film line', 'UV-Vis spectrophotometer', 'pH testing bath'],
    deliverable: 'Smart indicator film samples with color change mapping tables.',
    curriculum_match: 'Packaging Engineering; Sustainable Plastics',
    why_matters: 'Reduces food waste by visually indicating packaging integrity and freshness.',
    real_world_app: 'Active smart packaging solutions for meats and dairy.'
  },
  {
    id: 'A10',
    title: 'Polyurethane Foam Synthesis (Flexible vs Rigid)',
    description: 'Synthesize polyurethane foams by reacting polyols with diisocyanates, adjusting blowing agent content to control density and stiffness.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '6-8 weeks',
    skills: ['Polyurethane chemistry', 'Foam structure optimization', 'Cell morphology check'],
    equipment: ['Chemical fume hood', 'Compressive strength UTM', 'Microscope'],
    deliverable: 'Foam samples with density and compressive modulus evaluations.',
    curriculum_match: 'Polymer Chemistry',
    why_matters: 'Controls the production parameters of insulating foams vs cushioning foams.',
    real_world_app: 'Building insulation boards and furniture cushions.'
  },
  {
    id: 'A11',
    title: 'Geopolymer Synthesis from Industrial Waste',
    description: 'Synthesize fly-ash based inorganic geopolymers and evaluate their thermal insulation and mechanical properties.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '6-8 weeks',
    skills: ['Geopolymer formulation', 'Waste recycling', 'Compressive testing'],
    equipment: ['Muffle furnace', 'Compressive testing machine', 'pH meter'],
    deliverable: 'Geopolymer concrete samples with compressive strength data.',
    curriculum_match: 'Sustainable Plastics; Composites',
    why_matters: 'Reduces CO₂ emissions compared to conventional Portland cement.',
    real_world_app: 'Eco-friendly building blocks and refractory linings.'
  },
  {
    id: 'A12',
    title: 'Polymer Electrolyte for Battery Applications',
    description: 'Synthesize poly(ethylene oxide) (PEO) based solid polymer electrolytes complexed with lithium salts, and measure ionic conductivity.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Polymer electrolyte prep', 'Impedance spectroscopy', 'Anhydrous glove box use'],
    equipment: ['Glove box', 'Potentiostat/EIS', 'Hot press'],
    deliverable: 'Electrolyte film with ionic conductivity vs temperature plots.',
    curriculum_match: 'Advanced Materials',
    why_matters: 'Enables safer solid-state batteries, replacing flammable liquid organic electrolytes.',
    real_world_app: 'Next-generation electric vehicle batteries.'
  },
  {
    id: 'A13',
    title: 'Microplastic Detection & Characterization',
    description: 'Develop sampling and extraction protocols to isolate microplastics from local water bodies and identify them via FTIR microscopy.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '6-8 weeks',
    skills: ['Environmental sampling', 'Density separation', 'FTIR microscopy'],
    equipment: ['FTIR microscope', 'Microscopes', 'Sieving tower'],
    deliverable: 'Microplastic concentration reports mapping polymer types.',
    curriculum_match: 'Polymer Testing; Recycling Technology',
    why_matters: 'Quantifying microplastic contamination is critical for environmental remediation.',
    real_world_app: 'Environmental monitoring agencies.'
  },
  {
    id: 'A14',
    title: 'Polymer Upcycling (Waste to Value-Added Products)',
    description: 'Blend post-consumer PP waste with compatibilizers and glass fiber reinforcements to formulate automotive-grade compounds.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['PCR compatibilization', 'Reinforcing extrusion', 'QC testing'],
    equipment: ['Twin-screw extruder', 'Injection molder', 'Tensile/Impact UTM'],
    deliverable: 'Upcycled compound granules with performance comparisons.',
    curriculum_match: 'Recycling Technology; Entrepreneurship',
    why_matters: 'Upcycling redirects waste from landfills into durable engineering parts.',
    real_world_app: 'Circular plastic parts manufacturing.'
  },
  {
    id: 'A15',
    title: 'DCPD-Based Thermoset for High-Performance Composites',
    description: 'Formulate dicyclopentadiene (DCPD) resin systems and determine curing profiles and glass transition temperatures.',
    category: 'advanced',
    difficulty: 'Hard',
    duration: '8-10 weeks',
    skills: ['Thermoset formulation', 'Curing chemistry', 'Thermal transition check'],
    equipment: ['Chemical fume hood', 'DSC analyzer', 'TGA analyzer'],
    deliverable: 'DCPD resin formulation with cure property database.',
    curriculum_match: 'Polymer Composites; Advanced Materials',
    why_matters: 'DCPD produces high-toughness, chemical-resistant thermosets for heavy-duty composite structures.',
    real_world_app: 'Agricultural machinery body panels and marine hulls.'
  },

  // Level 4: Expert (10)
  {
    id: 'E1',
    title: 'Sustainable TPE Nanocomposite for Wearable Electronics',
    description: 'Synthesize bio-based thermoplastic polyurethane (TPU) filled with carbon nanotubes to print flexible, piezoresistive stretch sensors.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Conductive nanocomposites', 'Flexible sensor design', '3D printing TPU'],
    equipment: ['Twin-screw compounding extruder', 'FDM 3D printer', 'Piezoresistive measurement rig'],
    deliverable: 'Working flexible wearable sensor assembly with conductivity charts.',
    curriculum_match: 'Medical Plastics; Nanotechnology',
    why_matters: 'Enables continuous physiological monitoring via lightweight, flexible electronics.',
    real_world_app: 'Smart athletic wear and medical rehabilitation monitors.'
  },
  {
    id: 'E2',
    title: 'Full CDIO Polymer Engineering Project',
    description: 'Complete a full Conceive-Design-Implement-Operate project, developing a functional consumer product from recycled engineering plastics.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '12-16 weeks',
    skills: ['CDIO workflow', 'Product development', 'Tooling & molding trials'],
    equipment: ['CAD/CAE tools', 'Tooling machines', 'Molding line', 'Quality lab'],
    deliverable: 'Operational product assembly and technical engineering paper.',
    curriculum_match: 'All',
    why_matters: 'CDIO integrates all curriculum pillars into a single engineering experience.',
    real_world_app: 'Product engineering teams launching consumer products.'
  },
  {
    id: 'E3',
    title: 'Vitrimer Synthesis & Recycling',
    description: 'Synthesize epoxy vitrimers utilizing transesterification dynamic covalent chemistry, and evaluate mechanical recovery after recycling.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Vitrimer synthesis', 'Dynamic networks', 'Reprocessing validation'],
    equipment: ['Chemical synthesis lab', 'Compression hot press', 'DMA analyzer'],
    deliverable: 'Vitrimer samples and tensile property comparisons after 3 recycling rounds.',
    curriculum_match: 'Advanced Materials; Sustainable Plastics',
    why_matters: 'Vitrimers combine the high performance of thermosets with the recyclability of thermoplastics.',
    real_world_app: 'Recyclable wind turbine blade laminates and epoxy composites.'
  },
  {
    id: 'E4',
    title: 'AI-Driven Polymer Material Design',
    description: 'Implement machine learning models (QSPR) to predict polymer glass transition temperatures and moduli based on monomer chemical structure inputs.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '12-16 weeks',
    skills: ['Cheminformatics', 'QSPR modelling', 'Machine learning'],
    equipment: ['High-performance computing core', 'Python ML packages'],
    deliverable: 'Property prediction codebase and validation dataset comparison tables.',
    curriculum_match: 'Polymer Chemistry; Industry 4.0',
    why_matters: 'QSPR modeling accelerates new polymer formulation discovery by simulating structures before synthesis.',
    real_world_app: 'Materials genome design groups in R&D firms.'
  },
  {
    id: 'E5',
    title: 'Enzymatic PET Recycling Optimization',
    description: 'Isolate or purchase cutinase enzymes and optimize reaction parameters (temperature, pH, particle size) to depolymerize PET water bottles.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Enzymatic hydrolysis', 'Bioreactor optimization', 'HPLC monomer testing'],
    equipment: ['Stirred bioreactor', 'HPLC system', 'Particle milling system'],
    deliverable: 'Hydrolysis yield optimization curves and recovered terephthalic acid sample.',
    curriculum_match: 'Recycling Technology',
    why_matters: 'Provides low-energy, green biochemical recycling pathway for PET packaging.',
    real_world_app: 'Biochemical recycling companies.'
  },
  {
    id: 'E6',
    title: 'Polymer-Grafted Nanoparticle Self-Assembly',
    description: 'Synthesize silica nanoparticles grafted with PMMA brushes and analyze their self-assembled structure inside polymer matrices.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '12-14 weeks',
    skills: ['Nanoparticle grafting', 'Controlled radical polymerization', 'Self-assembly mapping'],
    equipment: ['Chemical synthesis reactor', 'Transmission Electron Microscope (TEM)', 'SAXS'],
    deliverable: 'Grafted nanoparticle composites with TEM dispersion profiles.',
    curriculum_match: 'Polymer Composites; Nanotechnology',
    why_matters: 'Controls the dispersion of inorganic nanoparticles to avoid agglomeration in composites.',
    real_world_app: 'High-performance barrier materials and aerospace parts.'
  },
  {
    id: 'E7',
    title: 'Smart, Self-Healing, Bio-Inspired Medical Plastics',
    description: 'Synthesize biocompatible chitosan-based hydrogels displaying self-healing properties under physiological conditions.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Biomaterial synthesis', 'Rheology of hydrogels', 'Biocompatibility validation'],
    equipment: ['Chemical synthesis lab', 'Rotational rheometer', 'Biocompatibility testing rig'],
    deliverable: 'Self-healing hydrogel samples with viscoelastic recovery charts.',
    curriculum_match: 'Medical Plastics; Advanced Materials',
    why_matters: 'Self-healing biomaterials increase implant reliability in tissue engineering.',
    real_world_app: 'Next-generation drug delivery coatings and injectable tissue scaffolds.'
  },
  {
    id: 'E8',
    title: '4D Printing of Shape-Memory Polymers',
    description: 'Synthesize shape-memory polycaprolactone networks and 3D print dynamic structures that actuate when exposed to temperature changes.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Shape-memory networks', '4D printing parameters', 'Actuation testing'],
    equipment: ['FDM 3D printer', 'Curing oven', 'Thermal chamber'],
    deliverable: '4D printed smart actuator and thermal cycle recovery graphs.',
    curriculum_match: 'Advanced Processing; Medical Plastics',
    why_matters: '4D printing enables deployable space structures and minimally invasive medical implants.',
    real_world_app: 'Smart aerospace hinges and self-expanding stents.'
  },
  {
    id: 'E9',
    title: 'Low-Cost PET-to-Filament Extruder for Developing Countries',
    description: 'Design and assemble a low-cost, open-source filament extruder that converts shredded post-consumer PET bottles into print filament.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Extruder design', 'Arduino temperature control', 'Machine assembly'],
    equipment: ['Lathe/Mill workshop', 'Arduino/microcontrollers', 'Filament gauge'],
    deliverable: 'Working filament extrusion machine with assembly manual.',
    curriculum_match: 'Entrepreneurship; Recycling Technology',
    why_matters: 'Supports distributed recycling, providing economic opportunities in plastic-waste heavy areas.',
    real_world_app: 'Local circular economy startups.'
  },
  {
    id: 'E10',
    title: 'Sustainable Composite from Industrial Waste',
    description: 'Develop a composite system utilizing recycled HDPE binder and fly ash filler, conducting structural characterization for construction use.',
    category: 'expert',
    difficulty: 'Expert',
    duration: '10-12 weeks',
    skills: ['Composite design', 'Waste valorization', 'Mechanical testing'],
    equipment: ['Compounding press', 'Universal testing machine', 'SEM microscope'],
    deliverable: 'Sustainable composite tiles with compressive strength database.',
    curriculum_match: 'Polymer Composites; Recycling Technology',
    why_matters: 'Valorizes fly ash waste and locks up post-consumer PE in durable, long-life products.',
    real_world_app: 'Recycled outdoor decking and plastic-lumber building products.'
  }
];
