'use client'

import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { 
  Clock, 
  Trophy, 
  Brain, 
  CheckCircle, 
  XCircle, 
  AlertTriangle, 
  BookOpen, 
  Sparkles, 
  Compass, 
  Flag,
  PlayCircle
} from 'lucide-react'

// ─── GATE Questions (30 questions mapped to 155 lessons) ───────────────────────

const GATE_QUESTIONS = [
  // Polymer Chemistry (6 questions)
  {
    id: 'gc1', subject: 'Polymer Chemistry', lessonSlug: 'polymerization-mechanisms-addition-vs-condensation',
    question: 'In free radical addition polymerization, the rate-determining step is:',
    options: ['Initiation', 'Propagation', 'Termination', 'Chain transfer'],
    correct: 0,
    explanation: 'Initiation is the slowest step in free radical polymerization — it involves homolytic dissociation of the initiator (e.g., BPO) and addition of the first radical to a monomer. Despite being rate-determining, propagation consumes most of the monomer because each initiation event adds thousands of monomer units.',
    marks: 1,
  },
  {
    id: 'gc2', subject: 'Polymer Chemistry', lessonSlug: 'glass-transition-temperature-tg-the-most-important-polymer-property',
    question: 'The glass transition temperature (Tg) of a polymer is best described as:',
    options: [
      'The temperature at which the polymer melts',
      'The temperature below which chain segment mobility ceases and the polymer becomes glassy',
      'The temperature at which crystallization begins',
      'The temperature at which polymer chains break',
    ],
    correct: 1,
    explanation: 'Tg marks the transition of amorphous polymer regions from a rubbery, mobile state to a rigid, glassy state upon cooling. Below Tg, backbone segment motion is frozen — the polymer is hard and brittle. Above Tg, segments can rotate freely — the material is soft and flexible. This governs nearly every end-use property.',
    marks: 1,
  },
  {
    id: 'gc3', subject: 'Polymer Chemistry', lessonSlug: 'molecular-weight-and-molecular-weight-distribution',
    question: 'The polydispersity index (PDI) of an ideal living anionic polymerization approaches:',
    options: ['0', '1.0', '2.0', '∞'],
    correct: 1,
    explanation: 'In living polymerization (e.g., anionic polymerization of styrene with n-BuLi), all chains initiate simultaneously and there is no termination. Every chain grows at the same rate and to the same length — giving a very narrow MWD with PDI (Mw/Mn) approaching 1.0. Commercial polymers typically have PDI 1.5–20 depending on the polymerization mechanism.',
    marks: 2,
  },
  {
    id: 'gc4', subject: 'Polymer Chemistry', lessonSlug: 'polymer-degradation-and-stabilization',
    question: 'Hindered amine light stabilizers (HALS) protect polyolefins from UV degradation by:',
    options: [
      'Absorbing UV radiation and converting it to heat',
      'Acting as chain scavengers — intercepting peroxy radicals to break the oxidative degradation cycle',
      'Increasing the crystallinity of the polymer',
      'Forming a UV-opaque surface film',
    ],
    correct: 1,
    explanation: 'HALS (e.g., Tinuvin 770) work by a radical scavenging mechanism — the hindered amine is oxidized to a nitroxyl radical that traps peroxy radicals (ROO•) generated by UV-induced oxidation. The nitroxyl radical is regenerated in a catalytic cycle, making HALS very efficient at low concentrations (0.1-0.5%). They do not absorb UV themselves — that is the role of UV absorbers like benzotriazoles.',
    marks: 2,
  },
  {
    id: 'gc5', subject: 'Polymer Chemistry', lessonSlug: 'copolymers-blends-and-alloys',
    question: 'ABS (Acrylonitrile-Butadiene-Styrene) is a terpolymer where the butadiene component primarily contributes:',
    options: ['Chemical resistance', 'Impact strength and toughness', 'Rigidity and modulus', 'Heat resistance'],
    correct: 1,
    explanation: 'In ABS, each monomer contributes distinct properties: Acrylonitrile → chemical resistance and heat resistance; Butadiene rubber phase → impact strength and toughness (the rubber particles cavitate and absorb energy during impact); Styrene → processability, rigidity, and surface finish. The dispersed rubber phase is the critical component that makes ABS the preferred material for high-impact applications like automotive dashboards.',
    marks: 1,
  },
  {
    id: 'gc6', subject: 'Polymer Chemistry', lessonSlug: 'crystallinity-and-morphology-in-polymers',
    question: 'Isotactic polypropylene has a higher melting point than atactic PP because:',
    options: [
      'It has higher molecular weight',
      'Regular spatial arrangement of methyl groups allows efficient chain packing into crystalline lamellae',
      'It contains more double bonds',
      'It has lower density',
    ],
    correct: 1,
    explanation: 'Isotactic PP has all methyl substituents on the same side of the backbone — this regular stereoregularity allows chains to pack into helical crystalline structures (3/1 helix, Tm ~165°C). Atactic PP has random methyl placement — cannot crystallize, remains amorphous with no distinct Tm, behaving as a sticky wax at room temperature. Ziegler-Natta catalysis produces isotactic PP; radical polymerization produces mostly atactic PP.',
    marks: 2,
  },

  // Polymer Processing (5 questions)
  {
    id: 'pp1', subject: 'Polymer Processing', lessonSlug: 'injection-moulding-process-parameters-and-defects',
    question: 'In injection moulding, the V-P (velocity-pressure) switchover is typically set at:',
    options: ['50% of cavity fill', '75% of cavity fill', '95-98% of cavity fill', '100% of cavity fill'],
    correct: 2,
    explanation: 'V-P switchover at 95-98% fill transitions from velocity-controlled filling to pressure-controlled packing. Switching too early (at 90%) leaves the cavity underfilled before pressure control begins. Switching too late (at 100%) causes flash as velocity drives melt past complete fill. The optimum leaves a small cushion for pressure to complete packing without overpacking.',
    marks: 1,
  },
  {
    id: 'pp2', subject: 'Polymer Processing', lessonSlug: 'extrusion-fundamentals-the-backbone-of-plastic-processing',
    question: 'The output rate of a single-screw extruder is primarily controlled by:',
    options: ['Barrel temperature only', 'Screw speed (RPM) — the primary variable for output control', 'Die pressure only', 'Feed hopper level'],
    correct: 1,
    explanation: 'In single-screw extrusion, screw speed is the primary output control variable — doubling RPM approximately doubles output (within the stable operating range). Barrel temperature primarily controls melt quality and viscosity. Die pressure is a consequence of output rate and die resistance. Feed hopper level affects output only if the extruder becomes starve-fed, which is abnormal operation.',
    marks: 1,
  },
  {
    id: 'pp3', subject: 'Polymer Processing', lessonSlug: 'melt-flow-index-mfi-measurement-significance-and-indian-standards',
    question: 'MFI is measured at 230°C/2.16kg for PP. A PP grade with MFI = 30 g/10min is most suitable for:',
    options: [
      'HDPE pressure pipe (requires high MW for strength)',
      'Thin-wall injection moulded parts and fibres (requires easy flow)',
      'Blow moulded containers (requires high melt strength)',
      'Rotational moulding (requires powder form)',
    ],
    correct: 1,
    explanation: 'High MFI (30 g/10min) indicates low molecular weight and low viscosity at 230°C — exactly what is needed to fill thin-walled containers (0.4-0.8 mm) at rapid cycle times without excessive injection pressure. Extrusion and blow moulding require low MFI (0.2-2.0 g/10min) for sufficient parison/melt strength to resist sagging.',
    marks: 1,
  },
  {
    id: 'pp4', subject: 'Polymer Processing', lessonSlug: 'blow-moulding-processes-extrusion-injection-and-stretch-blow',
    question: 'In PET stretch blow moulding (ISBM), biaxial orientation improves bottle properties primarily by:',
    options: [
      'Increasing polymer density only',
      'Inducing strain crystallization in both hoop and axial directions — increasing tensile strength and CO₂/O₂ barrier',
      'Reducing the glass transition temperature',
      'Decreasing wall thickness uniformity',
    ],
    correct: 1,
    explanation: 'Biaxial stretch (stretch rod gives axial orientation; blow air gives hoop/radial orientation) stretches PET chains near Tg (~90-100°C), inducing strain crystallization (up to ~30%). This aligns chains in both planes — increasing tensile strength by 3-4× and dramatically reducing gas permeability (permeation path becomes tortuous). This is why lightweight PET bottles can hold 4-6 bar carbonation pressure.',
    marks: 2,
  },
  {
    id: 'pp5', subject: 'Polymer Processing', lessonSlug: 'thermoforming-techniques-and-applications',
    question: 'In vacuum thermoforming, the maximum theoretical forming pressure available is:',
    options: ['0.1 MPa (1 bar — atmospheric pressure)', '1.0 MPa (10 bar)', '10 MPa', 'Infinite with high-capacity pump'],
    correct: 0,
    explanation: 'Vacuum thermoforming works by evacuating air from between the heated sheet and the mold cavity — atmospheric pressure (1 bar / 0.1 MPa) then pushes the sheet against the mold. The maximum differential pressure cannot exceed 1 atmosphere (14.7 psi / 100 kPa), regardless of pump size. For deeper draws or fine detail, pressure forming uses compressed air (3-6 bar) on the upper sheet surface to exceed atmospheric limits.',
    marks: 1,
  },

  // Testing & Characterization (5 questions)
  {
    id: 'pt1', subject: 'Polymer Testing', lessonSlug: 'tensile-testing-astm-d638-is-13360-stress-strain-curves-decoded',
    question: 'In an ASTM D638 tensile test of an unreinforced thermoplastic, the point where stress reaches a local maximum and necking begins is called:',
    options: ['Proportional limit', 'Yield point', 'Ultimate tensile strength', 'Fracture point'],
    correct: 1,
    explanation: 'The yield point on an engineering stress-strain curve marks the onset of plastic (permanent) deformation and localized cross-sectional reduction (necking). Beyond yield, polymer chains begin to slide past one another and align in the draw direction (strain hardening). Engineering yield strength is calculated as peak yield load divided by original cross-sectional area.',
    marks: 1,
  },
  {
    id: 'pt2', subject: 'Polymer Testing', lessonSlug: 'differential-scanning-calorimetry-dsc-thermal-fingerprints',
    question: 'In a DSC thermogram of a semi-crystalline polymer, an exothermic peak observed during heating (between Tg and Tm) corresponds to:',
    options: ['Melting', 'Glass transition', 'Cold crystallization', 'Thermal degradation'],
    correct: 2,
    explanation: 'Cold crystallization is an exothermic process (heat released) that occurs when amorphous chains quenched during rapid cooling gain sufficient thermal energy above Tg to reorganize into crystalline lamellae. Melting (Tm) is endothermic (heat absorbed) at higher temperature. Tg is a baseline shift (step change in heat capacity), not a peak.',
    marks: 2,
  },
  {
    id: 'pt3', subject: 'Polymer Testing', lessonSlug: 'impact-testing-izod-vs-charpy-energy-absorption-mechanisms',
    question: 'The notch in an Izod or Charpy impact specimen serves primarily to:',
    options: [
      'Reduce the required pendulum energy',
      'Create a severe stress concentration (triaxial stress state) that suppresses shear yielding and promotes brittle fracture',
      'Measure the surface hardness of the specimen',
      'Allow easy alignment in the specimen vice',
    ],
    correct: 1,
    explanation: 'The standard V-notch (radius 0.25 mm) creates a triaxial tensile stress state at the notch root during high-rate impact loading. Triaxial tension suppresses shear yielding (which requires shear stress) and forces the material to dissipate energy via brittle crack propagation. Notched impact tests measure notch sensitivity — how vulnerable the polymer is to surface scratches, sharp corners, and weld lines in service.',
    marks: 1,
  },
  {
    id: 'pt4', subject: 'Polymer Testing', lessonSlug: 'thermogravimetric-analysis-tga-thermal-stability-and-composition',
    question: 'TGA is used to determine the carbon black content in a filled polyolefin by heating:',
    options: [
      'In pure oxygen from 0°C to 1000°C',
      'First in nitrogen to 600°C (pyrolyzes polymer), then switching to air/O₂ to 800°C (burns carbon black)',
      'In helium only up to 400°C',
      'In steam atmosphere to 500°C',
    ],
    correct: 1,
    explanation: 'ASTM D6370 / E1131 two-atmosphere method: Under N₂ up to 600°C, the polymer pyrolyzes and volatilizes completely (weight loss 1 = polymer fraction). Switching to air/O₂ at 600°C combusts carbon black to CO₂ (weight loss 2 = carbon black fraction). Any remaining weight at 800°C is inorganic ash/filler (talc, CaCO₃, glass fibre). This is the standard compositional analysis method in masterbatch and compounding quality control.',
    marks: 2,
  },
  {
    id: 'pt5', subject: 'Polymer Testing', lessonSlug: 'heat-deflection-temperature-hdt-and-vicat-softening-point',
    question: 'HDT (ASTM D648) measures the temperature at which a 3-point bend specimen deflects 0.25 mm under a specific fiber stress of:',
    options: ['0.05 MPa only', '0.455 MPa or 1.82 MPa', '10.0 MPa', '50.0 MPa'],
    correct: 1,
    explanation: 'ASTM D648 specifies two standard fiber stress levels: 0.455 MPa (66 psi) for low-stress or unfilled materials, and 1.82 MPa (264 psi) for engineering resins and reinforced grades. HDT is the single most referenced thermal specification in automotive and appliance material datasheets for defining maximum short-term load-bearing temperature.',
    marks: 1,
  },

  // Rubber Technology (4 questions)
  {
    id: 'rt1', subject: 'Rubber Technology', lessonSlug: 'natural-rubber-vs-synthetic-rubbers-chemistry-and-properties',
    question: 'Natural rubber consists predominantly of:',
    options: [
      'trans-1,4-polyisoprene (gutta-percha)',
      'cis-1,4-polyisoprene',
      '1,2-polybutadiene',
      'cis-1,4-polybutadiene',
    ],
    correct: 1,
    explanation: 'Natural rubber is >99.9% cis-1,4-polyisoprene from Hevea brasiliensis latex. The all-cis configuration gives natural rubber its low Tg (−70°C), exceptional elasticity, and unique ability to undergo strain-induced crystallization (giving high gum tensile strength >25 MPa without fillers). Gutta-percha is trans-1,4-polyisoprene — crystalline and hard at room temperature.',
    marks: 1,
  },
  {
    id: 'rt2', subject: 'Rubber Technology', lessonSlug: 'vulcanization-chemistry-sulfur-peroxide-and-accelerators',
    question: 'In sulfur vulcanization of unsaturated rubbers, zinc oxide (ZnO) and stearic acid act as:',
    options: [
      'Primary crosslinking agents (substitute for sulfur)',
      'Activator system — reacting to form zinc stearate, which solubilizes zinc to accelerate polysulfide intermediate formation',
      'Fillers to increase hardness only',
      'Anti-degradants to prevent ozonolysis',
    ],
    correct: 1,
    explanation: 'ZnO + stearic acid forms zinc stearate in the rubber matrix. Zinc ions coordinate with accelerators (e.g., CBS, TBBS) and sulfur rings, generating reactive sulfurating complexes that crosslink allylic positions on the rubber backbone rapidly at 140-160°C. Without the ZnO/stearic acid activator system, sulfur crosslinking is extremely slow (hours vs minutes) and gives inefficient polysulfidic crosslinks prone to reversion.',
    marks: 2,
  },
  {
    id: 'rt3', subject: 'Rubber Technology', lessonSlug: 'carbon-black-and-silica-reinforcement-in-elastomers',
    question: 'Silica reinforcement in passenger car tire treads (the "green tire" concept) reduces rolling resistance while improving wet grip because:',
    options: [
      'Silica has lower density than carbon black',
      'Silica/silane systems reduce hysteresis (tan δ at 60°C) while maintaining high hysteresis (tan δ at 0°C) for wet traction',
      'Silica eliminates the need for vulcanization',
      'Silica is cheaper than carbon black',
    ],
    correct: 1,
    explanation: 'The "magic triangle" of tire performance (rolling resistance, wet grip, wear resistance) was traditionally conflicting. Precipitated silica coupled with bifunctional organosilanes (e.g., TESPT) decouples this: at 60°C (rolling frequency ~10-100 Hz), tan δ is low → lower fuel consumption; at 0°C (wet braking frequency ~10⁴-10⁶ Hz), tan δ is high → high energy dissipation on wet roads. Carbon black cannot match this dual-frequency response.',
    marks: 2,
  },
  {
    id: 'rt4', subject: 'Rubber Technology', lessonSlug: 'rheometer-cure-curves-ts2-tc90-and-scorch-safety',
    question: 'On an MDR/ODR rheometer cure curve, tc90 represents:',
    options: [
      'The time to reach minimum torque (ML)',
      'The scorch time (onset of vulcanization)',
      'The optimum cure time — time to reach 90% of maximum crosslink density (MH − ML)',
      'The total cycle time including demoulding',
    ],
    correct: 2,
    explanation: 'tc90 = time to reach ML + 0.90 × (MH − ML). In production moulding, parts are vulcanized to tc90 rather than tc100 (100% cure) to avoid overcure, minimize cycle time, and prevent reversion of polysulfidic crosslinks in thick parts. tc90 is the primary parameter for programming press cure times.',
    marks: 1,
  },

  // Recycling & Sustainability (5 questions)
  {
    id: 'rc1', subject: 'Recycling Technology', lessonSlug: 'mechanical-recycling-sorting-washing-shredding-compounding',
    question: 'In mechanical recycling of mixed plastics, PVC contamination in a PET stream must be kept below ~50 ppm because:',
    options: [
      'PVC makes PET transparent',
      'PVC degrades at PET processing temperatures (260-280°C), releasing HCl gas that accelerates PET hydrolytic degradation and corrodes machinery',
      'PVC increases the melting point of PET',
      'PVC prevents crystallisation of PET',
    ],
    correct: 1,
    explanation: 'PET processes at 260-280°C; PVC begins dehydrochlorination (degradation) above 190°C. Even 50 ppm PVC in a PET melt stream generates HCl gas, which: (1) catalyzes hydrolytic/acid degradation of PET chains (IV drops drastically); (2) causes severe black specks and yellowing; (3) corrodes extruder screws, barrels, and blow moulds. Near-infrared (NIR) and optical sorting are critical to eliminate PVC flake from rPET.',
    marks: 2,
  },
  {
    id: 'rc2', subject: 'Sustainable Plastics', lessonSlug: 'biodegradable-polymers-pla-pha-pbs-and-starch-blends',
    question: 'Industrial composting (EN 13432 / ISO 17088) requires biodegradable plastics to achieve 90% biodegradation within:',
    options: ['30 days at room temperature', '90 days at 20°C', '180 days at 58°C (thermophilic composting)', '1 year in soil'],
    correct: 2,
    explanation: 'EN 13432 specifies: ≥90% carbon conversion to CO₂ within 180 days at 58°C ± 2°C under active composting conditions with microbial presence. Disintegration (>90% passing through 2 mm sieve) must occur within 12 weeks. PLA meets industrial composting standards because 58°C is above its Tg (~55°C), enabling hydrolytic chain scission; in soil or ambient water (20°C, below Tg), PLA does not biodegrade rapidly.',
    marks: 1,
  },
  {
    id: 'rc3', subject: 'Recycling Technology', lessonSlug: 'chemical-recycling-depolymerization-pyrolysis-and-gasification',
    question: 'Glycolysis of PET waste involves reacting PET with excess ethylene glycol at 180-220°C in the presence of a catalyst to produce:',
    options: [
      'Terephthalic acid (TPA) and ethylene glycol',
      'Bis(2-hydroxyethyl) terephthalate (BHET) monomer',
      'Monomeric styrene',
      'Pyrolysis oil / naphtha fraction',
    ],
    correct: 1,
    explanation: 'PET + ethylene glycol (EG) → BHET monomer via transesterification of ester bonds. BHET is purified (filtered, decolorized, recrystallized) to food-grade quality and repolymerized into virgin-equivalent rPET. This chemical recycling route avoids the downcycling of mechanical recycling and processes colored, contaminated, or textile (polyester fiber) waste streams.',
    marks: 2,
  },
  {
    id: 'rc4', subject: 'Sustainable Plastics', lessonSlug: 'extended-producer-responsibility-epr-regulations-in-india',
    question: 'Under the Indian Plastic Waste Management (PWM) Rules Amendment 2022, EPR Category I covers:',
    options: ['Flexible plastic packaging', 'Rigid plastic packaging', 'Multi-layered plastic packaging (MLP)', 'Plastic carry bags below 120 microns'],
    correct: 1,
    explanation: 'India PWM EPR categorization: Category I = Rigid plastic packaging (bottles, containers, crates); Category II = Flexible plastic packaging (single layer/multi-layer polyolefin); Category III = Multi-layered plastic packaging (at least one non-plastic layer like aluminium foil); Category IV = Plastic sheets and carry bags. Each category carries distinct mandatory recycling percentages and end-of-life disposal targets.',
    marks: 1,
  },
  {
    id: 'rc5', subject: 'Sustainable Plastics', lessonSlug: 'life-cycle-assessment-lca-of-plastics-cradle-to-grave',
    question: 'In a Cradle-to-Grave Life Cycle Assessment (LCA) of plastic packaging, the functional unit is:',
    options: [
      'The total weight of the plastic package (e.g., 25 g)',
      'The quantified performance of a product system for use as a reference unit (e.g., "delivering 1 liter of beverage to consumer with shelf life of 6 months")',
      'The total cost of production',
      'The energy consumed during injection moulding only',
    ],
    correct: 1,
    explanation: 'ISO 14040/14044 LCA requires comparison on a functional unit basis — not weight. Comparing a 25 g PET bottle to a 400 g glass bottle on a per-kg basis is invalid; comparing both on "packaging and protecting 1 liter of carbonated beverage from filling to consumption" captures the full lightweighting advantage, transport fuel savings, and recycling impact accurately.',
    marks: 1,
  },

  // Composites & Mould Design (5 questions)
  {
    id: 'cm1', subject: 'Polymer Composites', lessonSlug: 'fiber-matrix-interphase-sizing-and-coupling-agents',
    question: 'In glass-fiber reinforced polypropylene (PP-GF), maleic anhydride grafted polypropylene (PP-g-MAH) is added to:',
    options: [
      'Reduce the compound price',
      'Act as a compatibilizer — anhydride groups react with silane sizing on glass, while PP backbone entangles with the matrix, improving stress transfer',
      'Increase the melt flow index',
      'Prevent UV discoloration',
    ],
    correct: 1,
    explanation: 'Polypropylene is non-polar and chemically inert; glass fibers are polar and hydrophilic. Without coupling, fiber-matrix adhesion is purely frictional and poor — tensile strength of PP-GF without compatibilizer is barely higher than neat PP. PP-g-MAH (typically 1-3%) provides chemical bonds: anhydride rings open and react with amine/hydroxy groups on the glass fiber silane sizing, while the PP polymer chains co-crystallize with the bulk PP matrix. Tensile strength doubles (35 → 80+ MPa).',
    marks: 2,
  },
  {
    id: 'cm2', subject: 'Mould Design', lessonSlug: 'runner-and-gating-systems-hot-vs-cold-runner-design',
    question: 'In injection mould design, a "hot runner" system eliminates:',
    options: [
      'The need for mould cooling channels',
      'Solidified runner scrap and the need for runner regrind, reducing material waste and cycle time',
      'Clamping force requirements',
      'The need for cavity venting',
    ],
    correct: 1,
    explanation: 'Hot runner systems maintain polymer in a molten state inside manifold and nozzles up to the cavity gate. Only the part in the cavity solidifies — no cold runner or sprue is ejected. Benefits: (1) zero runner scrap (critical for high-volume automotive/packaging parts); (2) reduced cycle time (runner is often thicker than the part and governs cooling time); (3) lower injection pressure drops.',
    marks: 1,
  },
  {
    id: 'cm3', subject: 'Mould Design', lessonSlug: 'cooling-channel-design-conformal-cooling-and-cycle-time',
    question: 'In injection moulding of a typical 2 mm polypropylene part, cooling time accounts for approximately what percentage of total cycle time?',
    options: ['10-20%', '25-35%', '50-70% (the dominant portion of cycle time)', '90-95%'],
    correct: 2,
    explanation: 'In thermoplastic injection moulding, cooling time is governed by Fourier heat conduction: t_cool ∝ s² / (π² · α), where s is wall thickness and α is thermal diffusivity. Because polymers have low thermal conductivity (k ~0.15-0.35 W/m·K), removing heat through the steel mould takes 50-70% of the total cycle time. Optimizing cooling channels (conformal cooling via 3D printing, beryllium-copper inserts) is the most profitable mould engineering optimization.',
    marks: 1,
  },
  {
    id: 'cm4', subject: 'Polymer Composites', lessonSlug: 'short-vs-continuous-fiber-composites-mechanics-and-processing',
    question: 'The critical fiber length (l_c) in short-fiber composites is defined as:',
    options: [
      'The length of the fiber in the pellet before compounding',
      'The minimum fiber length required for fiber stress to build up to the fiber ultimate tensile strength (l_c = σ_f · d / 2τ)',
      'The diameter of the compounding extruder screw',
      'The length of the runner channel in the mould',
    ],
    correct: 1,
    explanation: 'Kelly-Tyson shear lag model: l_c = (σ_f · d) / (2 · τ_y), where σ_f is fiber tensile strength, d is fiber diameter, and τ_y is interfacial shear strength. If actual fiber length l < l_c, the fiber pulls out of the matrix before reaching its breaking strength (inefficient reinforcement). If l > l_c, the fiber fractures in the middle and carries maximum load. Injection moulding typically degrades fiber length to 0.2-0.5 mm, which must remain above l_c (~0.15-0.3 mm for E-glass in PP) for effective reinforcement.',
    marks: 2,
  },
  {
    id: 'cm5', subject: 'Mould Design', lessonSlug: 'ejection-systems-pins-sleeves-stripper-plates-and-air-ejection',
    question: 'Stripper plate ejection is preferred over ejector pins for:',
    options: [
      'Heavy automotive bumper mouldings',
      'Thin-walled, circular, or cylindrical parts (e.g., cups, caps, closures) to distribute ejection force uniformly and prevent pin push-through marks',
      'Moulds with side-core actions only',
      'Thermoset compression moulds',
    ],
    correct: 1,
    explanation: 'Ejector pins concentrate force on small contact areas (2-8 mm dia) and can punch through or distort thin-walled hot parts during ejection. A stripper plate acts on the entire perimeter of the part flange or rim, providing 360° uniform ejection force with zero pin witness marks. It is the standard ejection mechanism for beverage closures, thin-wall food containers, and medical syringes.',
    marks: 1,
  },
]

type QuizState = 'setup' | 'active' | 'submitted'
type AnswerMap = Record<string, number>

const SUBJECT_COLORS: Record<string, string> = {
  'Polymer Chemistry': '#2563EB',
  'Polymer Processing': '#EA580C',
  'Polymer Testing': '#7C3AED',
  'Rubber Technology': '#DC2626',
  'Recycling Technology': '#16A34A',
  'Sustainable Plastics': '#059669',
  'Polymer Composites': '#D97706',
  'Mould Design': '#4F46E5',
}

// ─── Timer Component ──────────────────────────────────────────────────────────

function Timer({ seconds, onTimeout }: { seconds: number; onTimeout: () => void }) {
  const [remaining, setRemaining] = useState(seconds)
  const intervalRef = useRef<NodeJS.Timeout | null>(null)

  useEffect(() => {
    intervalRef.current = setInterval(() => {
      setRemaining(prev => {
        if (prev <= 1) {
          clearInterval(intervalRef.current!)
          onTimeout()
          return 0
        }
        return prev - 1
      })
    }, 1000)
    return () => clearInterval(intervalRef.current!)
  }, [onTimeout])

  const mins = Math.floor(remaining / 60)
  const secs = remaining % 60
  const isUrgent = remaining < 300 // last 5 minutes

  return (
    <div
      className={`flex items-center gap-2 border-2 rounded-xl px-4 py-2 font-mono font-bold text-base ${
        isUrgent 
          ? 'border-red-500 bg-red-500 text-white animate-pulse' 
          : 'border-slate-900 bg-slate-900 text-[#F5C518]'
      }`}
    >
      <Clock className="w-4 h-4" />
      {String(mins).padStart(2, '0')}:{String(secs).padStart(2, '0')}
    </div>
  )
}

// ─── Score Report Component ───────────────────────────────────────────────────

function ScoreReport({ answers, timeTaken }: { answers: AnswerMap; timeTaken: number }) {
  const totalMarks = GATE_QUESTIONS.reduce((a, q) => a + q.marks, 0)
  let scored = 0
  let correct = 0
  let wrong = 0
  let unattempted = 0

  GATE_QUESTIONS.forEach(q => {
    if (answers[q.id] === undefined) {
      unattempted++
    } else if (answers[q.id] === q.correct) {
      scored += q.marks
      correct++
    } else {
      // GATE negative marking: -1/3 for 1-mark, -2/3 for 2-mark
      scored -= q.marks / 3
      wrong++
    }
  })

  const mins = Math.floor(timeTaken / 60)
  const secs = timeTaken % 60

  const subjects = GATE_QUESTIONS.map(q => q.subject).filter((value, index, self) => self.indexOf(value) === index)
  const subjectBreakdown = subjects.map(sub => {
    const subQs = GATE_QUESTIONS.filter(q => q.subject === sub)
    const subMarks = subQs.reduce((a, q) => a + q.marks, 0)
    let subScored = 0
    subQs.forEach(q => {
      if (answers[q.id] === q.correct) subScored += q.marks
      else if (answers[q.id] !== undefined) subScored -= q.marks / 3
    })
    return { subject: sub, scored: Math.max(0, subScored), total: subMarks, pct: Math.round((Math.max(0, subScored) / subMarks) * 100) }
  })

  return (
    <div className="space-y-6">
      {/* Main Score Banner */}
      <div className="border-2 border-slate-900 rounded-2xl bg-white shadow-xl overflow-hidden">
        <div className="bg-[#0A1628] text-white p-8 text-center space-y-2">
          <span className="text-xs font-mono font-bold tracking-widest text-[#F5C518] uppercase">Official GATE Scoring Breakdown</span>
          <div className="font-display text-5xl sm:text-6xl font-black">
            {Math.max(0, scored).toFixed(2)}
            <span className="text-2xl text-slate-400 font-light"> / {totalMarks} Marks</span>
          </div>
          <p className="text-xs text-slate-300">
            Negative marking included (&minus;1/3 mark per wrong 1-mark MCQ, &minus;2/3 mark per wrong 2-mark MCQ).
          </p>
        </div>

        <div className="p-6 space-y-6">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-200 text-center">
              <div className="font-display text-2xl font-bold text-emerald-800">{correct}</div>
              <div className="text-[10px] font-mono font-bold uppercase text-emerald-700 mt-1">Correct Answers</div>
            </div>
            <div className="p-4 bg-rose-50 rounded-xl border border-rose-200 text-center">
              <div className="font-display text-2xl font-bold text-rose-800">{wrong}</div>
              <div className="text-[10px] font-mono font-bold uppercase text-rose-700 mt-1">Wrong Answers</div>
            </div>
            <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-center">
              <div className="font-display text-2xl font-bold text-slate-800">{unattempted}</div>
              <div className="text-[10px] font-mono font-bold uppercase text-slate-500 mt-1">Unattempted</div>
            </div>
            <div className="p-4 bg-blue-50 rounded-xl border border-blue-200 text-center">
              <div className="font-display text-2xl font-bold text-blue-800">{mins}m {secs}s</div>
              <div className="text-[10px] font-mono font-bold uppercase text-blue-700 mt-1">Time Elapsed</div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 pt-2">
            <Link 
              href="/practice" 
              className="flex-1 py-3 text-center bg-[#F5C518] hover:bg-amber-400 text-slate-950 font-mono font-bold text-xs uppercase tracking-wider rounded-xl border-2 border-slate-900 shadow-sm"
            >
              Practice More Challenges &rarr;
            </Link>
            <Link 
              href="/ai-tutor?prompt=Explain%20how%20to%20improve%20GATE%20Polymer%20Science%20score%20and%20master%20free%20radical%20polymerization%20kinetics" 
              className="flex-1 py-3 text-center bg-slate-900 hover:bg-slate-800 text-white font-mono font-bold text-xs uppercase tracking-wider rounded-xl border-2 border-slate-900 shadow-sm"
            >
              <Brain className="w-3.5 h-3.5 inline mr-1.5" /> Ask AI GATE Coach
            </Link>
          </div>
        </div>
      </div>

      {/* Subject Breakdown */}
      <div className="bg-white border-2 border-slate-900 rounded-2xl p-6 shadow-xl space-y-4">
        <h3 className="font-display font-bold text-base uppercase text-slate-900">
          Subject-wise Score Analysis
        </h3>

        <div className="space-y-4">
          {subjectBreakdown.map(s => (
            <div key={s.subject} className="space-y-1.5">
              <div className="flex justify-between text-xs font-mono font-bold">
                <span className="text-slate-800">{s.subject}</span>
                <span className="text-blue-700">{s.scored.toFixed(1)} / {s.total} Marks ({s.pct}%)</span>
              </div>
              <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden border border-slate-200">
                <div 
                  className="h-full bg-blue-600 rounded-full transition-all duration-500" 
                  style={{ width: `${s.pct}%` }} 
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Detailed Question Review */}
      <div className="space-y-4">
        <h3 className="font-display font-bold text-base uppercase text-slate-900">
          Complete Answer Review ({GATE_QUESTIONS.length} Questions)
        </h3>

        {GATE_QUESTIONS.map((q, idx) => {
          const userAnswer = answers[q.id]
          const isCorrect = userAnswer === q.correct
          const isUnattempted = userAnswer === undefined

          return (
            <article key={q.id} className="border-2 border-slate-900 rounded-2xl bg-white p-6 shadow-sm space-y-3">
              <div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2">
                  {isUnattempted ? (
                    <span className="inline-flex items-center gap-1 text-slate-500 font-mono text-xs font-bold">
                      <AlertTriangle className="w-4 h-4 text-slate-400" /> Unattempted
                    </span>
                  ) : isCorrect ? (
                    <span className="inline-flex items-center gap-1 text-emerald-700 font-mono text-xs font-bold">
                      <CheckCircle className="w-4 h-4 text-emerald-600" /> Correct (+{q.marks})
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-rose-700 font-mono text-xs font-bold">
                      <XCircle className="w-4 h-4 text-rose-600" /> Wrong (&minus;{(q.marks / 3).toFixed(2)})
                    </span>
                  )}
                </div>
                <span className="font-mono text-[10px] font-bold text-slate-500 uppercase bg-slate-100 px-2 py-0.5 rounded-full">
                  {q.subject}
                </span>
              </div>

              <p className="font-display font-bold text-sm sm:text-base text-slate-900 leading-snug">
                Q{idx + 1}. {q.question}
              </p>

              <div className="space-y-2">
                {q.options.map((opt, optIdx) => {
                  const isCorrectOpt = optIdx === q.correct
                  const isUserChoice = optIdx === userAnswer

                  return (
                    <div 
                      key={optIdx} 
                      className={`p-3 rounded-xl border-2 text-xs font-medium flex items-center justify-between gap-3 ${
                        isCorrectOpt 
                          ? 'border-emerald-500 bg-emerald-50 text-emerald-950 font-bold'
                          : isUserChoice 
                          ? 'border-rose-500 bg-rose-50 text-rose-950 font-bold'
                          : 'border-slate-200 bg-slate-50 text-slate-700'
                      }`}
                    >
                      <div className="flex items-center gap-2.5">
                        <span className="font-mono font-bold w-5">{['A', 'B', 'C', 'D'][optIdx]}.</span>
                        <span>{opt}</span>
                      </div>
                      {isCorrectOpt && <CheckCircle className="w-4 h-4 text-emerald-600 flex-shrink-0" />}
                      {isUserChoice && !isCorrectOpt && <XCircle className="w-4 h-4 text-rose-600 flex-shrink-0" />}
                    </div>
                  )
                })}
              </div>

              <div className="p-3.5 bg-blue-50/70 rounded-xl border border-blue-200 text-xs text-blue-950 space-y-1">
                <span className="font-mono font-bold text-[10px] text-blue-800 uppercase tracking-wider block">Rationale &amp; Solution</span>
                <p className="leading-relaxed">{q.explanation}</p>
              </div>

              <div className="pt-1">
                <Link 
                  href={`/lessons/${q.lessonSlug}`}
                  className="font-mono text-xs font-bold text-blue-600 hover:text-blue-800 uppercase flex items-center gap-1"
                >
                  <BookOpen className="w-3.5 h-3.5" /> Read Lesson &rarr;
                </Link>
              </div>
            </article>
          )
        })}
      </div>
    </div>
  )
}

// ─── Main GATE Mock Page ──────────────────────────────────────────────────────

export default function GATEMockPage() {
  const [state, setState] = useState<QuizState>('setup')
  const [answers, setAnswers] = useState<AnswerMap>({})
  const [currentQ, setCurrentQ] = useState(0)
  const [startTime, setStartTime] = useState<number>(0)
  const [timeTaken, setTimeTaken] = useState(0)
  const [flagged, setFlagged] = useState<Set<string>>(new Set())

  const TOTAL_TIME = 60 * 60 // 60 minutes

  const handleStart = () => {
    setStartTime(Date.now())
    setAnswers({})
    setCurrentQ(0)
    setFlagged(new Set())
    setState('active')
  }

  const handleSubmit = () => {
    setTimeTaken(Math.round((Date.now() - startTime) / 1000))
    setState('submitted')
  }

  const handleSelect = (optIdx: number) => {
    setAnswers(prev => ({ ...prev, [GATE_QUESTIONS[currentQ].id]: optIdx }))
  }

  const toggleFlag = () => {
    const id = GATE_QUESTIONS[currentQ].id
    setFlagged(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  const answered = Object.keys(answers).length
  const currentQuestion = GATE_QUESTIONS[currentQ]
  const currentAnswer = answers[currentQuestion?.id]
  const isFlagged = flagged.has(currentQuestion?.id)

  return (
    <div className="min-h-screen bg-[#FAF8F5] text-slate-900 pb-20">

      {/* ── HERO SECTION: Midnight Navy with Indian Tricolor Accent ── */}
      <section className="bg-[#0A1628] text-white py-16 md:py-20 px-4 sm:px-6 border-b-2 border-slate-900 relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.15)_0%,transparent_70%)] pointer-events-none" />
        
        <div className="relative z-10 max-w-5xl mx-auto text-center space-y-4">
          <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-md border border-white/20 rounded-full px-4 py-1.5 mb-2">
            <Trophy className="w-4 h-4 text-amber-400" />
            <span className="text-xs font-mono font-bold tracking-widest uppercase text-white/90">
              GATE 2026 Polymer Science &middot; Timed Mock Arena
            </span>
          </div>

          <h1 className="font-display text-3xl sm:text-5xl md:text-6xl font-black leading-tight tracking-tight uppercase">
            GATE Polymer Science <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#FF8A00] via-[#FFFFFF] to-[#16A34A]">
              Mock Test Arena
            </span>
          </h1>

          <p className="text-sm sm:text-base md:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed font-light">
            Full-length timed simulation strictly aligned with GATE (XE-F / CY / CH) syllabus. Includes authentic negative marking (&minus;1/3) and instant rationale breakdown.
          </p>

          {/* Quick Metrics */}
          <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-white block">30</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">GATE Questions</span>
            </div>
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-amber-400 block">35</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Total Marks</span>
            </div>
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-emerald-400 block">60 Min</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Continuous Timer</span>
            </div>
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-rose-400 block">&minus;1/3</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Negative Marking</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── Main Workspace ── */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 -mt-8 relative z-20 space-y-8">
        
        {/* Setup Screen */}
        {state === 'setup' && (
          <div className="bg-white border-2 border-slate-900 rounded-2xl p-6 sm:p-8 shadow-xl space-y-6">
            <div>
              <h2 className="font-display font-bold text-xl uppercase text-slate-900">
                📋 Exam Protocol &amp; Instructions
              </h2>
              <p className="text-xs sm:text-sm text-slate-500 font-medium mt-1">
                Please read the official evaluation criteria before starting the mock session.
              </p>
            </div>

            <div className="p-4 bg-amber-50 rounded-xl border border-amber-200 space-y-2">
              <span className="font-mono text-xs font-bold text-amber-900 uppercase tracking-wide block">Evaluation Rules</span>
              <ul className="space-y-1.5 text-xs text-amber-950 font-medium">
                <li>&bull; 1-Mark Questions: +1.0 for correct, &minus;0.33 for incorrect.</li>
                <li>&bull; 2-Mark Questions: +2.0 for correct, &minus;0.67 for incorrect.</li>
                <li>&bull; Unattempted questions carry zero penalty.</li>
                <li>&bull; You can freely navigate, clear choices, or flag items for review.</li>
                <li>&bull; The 60-minute timer runs continuously upon clicking Start.</li>
              </ul>
            </div>

            <div>
              <span className="font-mono text-xs font-bold text-slate-500 uppercase tracking-wide block mb-2">Subjects Tested</span>
              <div className="flex flex-wrap gap-2">
                {Object.entries(SUBJECT_COLORS).map(([sub]) => (
                  <span key={sub} className="px-3 py-1 bg-slate-100 text-slate-800 text-xs font-mono font-bold rounded-lg border border-slate-200">
                    {sub}
                  </span>
                ))}
              </div>
            </div>

            <button
              onClick={handleStart}
              className="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white font-mono font-bold text-sm uppercase tracking-wider rounded-xl border-2 border-blue-700 shadow-md hover:translate-y-[-1px] transition-all flex items-center justify-center gap-2"
            >
              <PlayCircle className="w-5 h-5" /> Start GATE Mock Exam &mdash; 60 Minutes
            </button>
          </div>
        )}

        {/* Active Exam Mode */}
        {state === 'active' && currentQuestion && (
          <div className="space-y-6">
            
            {/* Top Toolbar with Timer & Flag */}
            <div className="bg-white border-2 border-slate-900 rounded-2xl p-4 sm:p-5 shadow-xl flex items-center justify-between gap-4 flex-wrap">
              <div className="flex items-center gap-3">
                <span className="font-display font-bold text-base text-slate-900">
                  Question {currentQ + 1} of {GATE_QUESTIONS.length}
                </span>
                <span className="font-mono text-xs text-slate-500 font-bold">
                  ({answered} answered)
                </span>
              </div>

              <div className="flex items-center gap-3">
                <button
                  onClick={toggleFlag}
                  className={`px-3 py-1.5 rounded-xl border-2 font-mono text-xs font-bold uppercase transition-all flex items-center gap-1.5 ${
                    isFlagged
                      ? 'border-amber-500 bg-amber-50 text-amber-800'
                      : 'border-slate-200 text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  <Flag className="w-3.5 h-3.5" />
                  {isFlagged ? 'Flagged' : 'Flag Question'}
                </button>

                <Timer seconds={TOTAL_TIME} onTimeout={handleSubmit} />
              </div>
            </div>

            {/* Question Workspace Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 items-start">
              
              {/* Question & Options (3 Columns) */}
              <div className="lg:col-span-3 bg-white border-2 border-slate-900 rounded-2xl p-6 sm:p-8 shadow-xl space-y-6">
                <div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3">
                  <span className="px-2.5 py-1 bg-blue-50 text-blue-700 text-xs font-mono font-bold rounded-lg border border-blue-200">
                    {currentQuestion.marks} Mark{currentQuestion.marks > 1 ? 's' : ''}
                  </span>
                  <span className="font-mono text-xs font-bold text-slate-500 uppercase">
                    {currentQuestion.subject}
                  </span>
                </div>

                <p className="font-display font-bold text-base sm:text-lg text-slate-900 leading-snug">
                  {currentQuestion.question}
                </p>

                <div className="space-y-3">
                  {currentQuestion.options.map((opt, optIdx) => {
                    const isSelected = currentAnswer === optIdx
                    return (
                      <button
                        key={optIdx}
                        onClick={() => handleSelect(optIdx)}
                        className={`w-full text-left p-4 rounded-xl border-2 transition-all flex items-center gap-3 ${
                          isSelected
                            ? 'border-blue-600 bg-blue-50 text-blue-950 font-bold shadow-sm'
                            : 'border-slate-200 bg-slate-50 hover:bg-white text-slate-800'
                        }`}
                      >
                        <span className={`w-6 h-6 rounded-lg font-mono text-xs font-bold flex items-center justify-center shrink-0 border ${
                          isSelected ? 'bg-blue-600 text-white border-blue-700' : 'bg-white text-slate-700 border-slate-300'
                        }`}>
                          {['A', 'B', 'C', 'D'][optIdx]}
                        </span>
                        <span className="text-xs sm:text-sm">{opt}</span>
                      </button>
                    )
                  })}
                </div>

                {/* Actions Bottom Bar */}
                <div className="flex justify-between items-center gap-3 pt-4 border-t border-slate-100 flex-wrap">
                  <button
                    onClick={() => setAnswers(prev => {
                      const copy = { ...prev }
                      delete copy[currentQuestion.id]
                      return copy
                    })}
                    className="px-3.5 py-2 border-2 border-slate-200 hover:border-slate-400 text-slate-600 font-mono text-xs font-bold uppercase rounded-xl transition-all"
                  >
                    Clear Choice
                  </button>

                  <div className="flex gap-2">
                    <button
                      disabled={currentQ === 0}
                      onClick={() => setCurrentQ(prev => prev - 1)}
                      className="px-4 py-2 border-2 border-slate-200 text-slate-700 disabled:opacity-40 font-mono text-xs font-bold uppercase rounded-xl hover:bg-slate-50 transition-all"
                    >
                      &larr; Prev
                    </button>
                    {currentQ < GATE_QUESTIONS.length - 1 ? (
                      <button
                        onClick={() => setCurrentQ(prev => prev + 1)}
                        className="px-5 py-2 bg-slate-900 hover:bg-slate-800 text-white font-mono text-xs font-bold uppercase rounded-xl transition-all"
                      >
                        Next &rarr;
                      </button>
                    ) : (
                      <button
                        onClick={handleSubmit}
                        className="px-6 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-mono text-xs font-bold uppercase rounded-xl transition-all"
                      >
                        Submit Test
                      </button>
                    )}
                  </div>
                </div>
              </div>

              {/* Question Palette Sidebar (1 Column) */}
              <div className="bg-white border-2 border-slate-900 rounded-2xl p-5 shadow-xl space-y-4">
                <span className="font-mono text-xs font-bold text-slate-400 uppercase tracking-wider block border-b border-slate-100 pb-2">
                  Question Palette
                </span>

                <div className="grid grid-cols-5 gap-1.5">
                  {GATE_QUESTIONS.map((q, idx) => {
                    const isQAnswered = answers[q.id] !== undefined
                    const isQFlagged = flagged.has(q.id)
                    const isQCurrent = idx === currentQ
                    
                    let bg = 'bg-slate-50 text-slate-700 border-slate-200'
                    if (isQCurrent) {
                      bg = 'bg-blue-600 text-white border-blue-700 font-black ring-2 ring-blue-300'
                    } else if (isQFlagged) {
                      bg = 'bg-amber-400 text-slate-950 border-amber-500 font-bold'
                    } else if (isQAnswered) {
                      bg = 'bg-emerald-600 text-white border-emerald-700 font-bold'
                    }
                    
                    return (
                      <button
                        key={q.id}
                        onClick={() => setCurrentQ(idx)}
                        className={`h-8 rounded-lg border text-xs font-mono flex items-center justify-center transition-all ${bg}`}
                      >
                        {idx + 1}
                      </button>
                    )
                  })}
                </div>

                <div className="space-y-1.5 pt-2 border-t border-slate-100 text-[11px] font-mono">
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-emerald-600 rounded-sm" />
                    <span>Answered ({answered})</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-amber-400 rounded-sm" />
                    <span>Flagged ({flagged.size})</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-slate-100 border border-slate-300 rounded-sm" />
                    <span>Unattempted ({GATE_QUESTIONS.length - answered})</span>
                  </div>
                </div>

                <button
                  onClick={handleSubmit}
                  className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-mono text-xs font-bold uppercase rounded-xl transition-all shadow-sm"
                >
                  Submit Exam
                </button>
              </div>

            </div>

          </div>
        )}

        {/* Submitted Score Summary */}
        {state === 'submitted' && (
          <ScoreReport answers={answers} timeTaken={timeTaken} />
        )}

      </div>

      {/* ── BOTTOM AI GATE COUNSELOR CTA ── */}
      <section className="max-w-5xl mx-auto px-4 sm:px-6 mt-16">
        <div className="bg-[#0A1628] text-white rounded-3xl p-8 sm:p-12 border-2 border-slate-900 shadow-2xl text-center space-y-6">
          <div className="inline-flex items-center gap-2 font-mono text-xs font-bold text-amber-400 bg-white/10 px-4 py-1.5 rounded-full uppercase tracking-widest border border-white/20">
            <Sparkles className="w-3.5 h-3.5 text-amber-400" /> AI GATE Coach &middot; Gemini RAG
          </div>

          <h2 className="font-display text-3xl sm:text-4xl font-black uppercase">
            Need detailed problem walkthroughs? <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#FF8A00] via-[#FFFFFF] to-[#16A34A]">
              Ask the AI GATE Coach.
            </span>
          </h2>

          <p className="text-slate-300 text-sm max-w-xl mx-auto leading-relaxed font-light">
            Review numerical formula steps for single screw output, Carothers equation degree of polymerization, or shear lag critical fiber length.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-2">
            <Link
              href="/ai-tutor?prompt=Explain%20how%20to%20solve%20Kelly-Tyson%20critical%20fiber%20length%20problems%20for%20GATE%20Polymer%20Engineering"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-[#F5C518] hover:bg-amber-400 text-slate-950 font-mono font-bold text-xs uppercase tracking-wider px-8 py-4 rounded-xl border-2 border-slate-900 shadow-[4px_4px_0px_0px_#000] hover:shadow-[2px_2px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all"
            >
              <Brain className="w-4 h-4" /> Ask GATE Coach &rarr;
            </Link>

            <Link
              href="/practice"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white font-mono font-bold text-xs uppercase tracking-wider px-8 py-4 rounded-xl border-2 border-white/30 hover:border-white transition-all"
            >
              <Compass className="w-4 h-4" /> 19-Subject Quiz Engine
            </Link>
          </div>
        </div>
      </section>

    </div>
  )
}
