'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { 
  Clock, 
  Trophy, 
  Brain, 
  CheckCircle, 
  XCircle, 
  AlertTriangle, 
  BookOpen, 
  Sparkles, 
  Compass, 
  Flag,
  PlayCircle
} from 'lucide-react'

// ─── GATE Questions (30 questions mapped to 216 lessons) ───────────────────────

const GATE_QUESTIONS = [
  // Polymer Chemistry (6 questions)
  {
    id: 'gc1', subject: 'Polymer Chemistry', lessonSlug: 'polymerization-mechanisms-addition-vs-condensation',
    question: 'In free radical addition polymerization, the rate-determining step is:',
    options: ['Initiation', 'Propagation', 'Termination', 'Chain transfer'],
    correct: 0,
    explanation: 'Initiation is the slowest step in free radical polymerization — it involves homolytic dissociation of the initiator (e.g., BPO) and addition of the first radical to a monomer. Despite being rate-determining, propagation consumes most of the monomer because each initiation event adds thousands of monomer units.',
    marks: 1,
  },
  {
    id: 'gc2', subject: 'Polymer Chemistry', lessonSlug: 'glass-transition-temperature-tg-the-most-important-polymer-property',
    question: 'The glass transition temperature (Tg) of a polymer is best described as:',
    options: [
      'The temperature at which the polymer melts',
      'The temperature below which chain segment mobility ceases and the polymer becomes glassy',
      'The temperature at which crystallization begins',
      'The temperature at which polymer chains break',
    ],
    correct: 1,
    explanation: 'Tg marks the transition of amorphous polymer regions from a rubbery, mobile state to a rigid, glassy state upon cooling. Below Tg, backbone segment motion is frozen — the polymer is hard and brittle. Above Tg, segments can rotate freely — the material is soft and flexible. This governs nearly every end-use property.',
    marks: 1,
  },
  {
    id: 'gc3', subject: 'Polymer Chemistry', lessonSlug: 'molecular-weight-and-molecular-weight-distribution',
    question: 'The polydispersity index (PDI) of an ideal living anionic polymerization approaches:',
    options: ['0', '1.0', '2.0', '∞'],
    correct: 1,
    explanation: 'In living polymerization (e.g., anionic polymerization of styrene with n-BuLi), all chains initiate simultaneously and there is no termination. Every chain grows at the same rate and to the same length — giving a very narrow MWD with PDI (Mw/Mn) approaching 1.0. Commercial polymers typically have PDI 1.5–20 depending on the polymerization mechanism.',
    marks: 2,
  },
  {
    id: 'gc4', subject: 'Polymer Chemistry', lessonSlug: 'polymer-degradation-and-stabilization',
    question: 'Hindered amine light stabilizers (HALS) protect polyolefins from UV degradation by:',
    options: [
      'Absorbing UV radiation and converting it to heat',
      'Acting as chain scavengers — intercepting peroxy radicals to break the oxidative degradation cycle',
      'Increasing the crystallinity of the polymer',
      'Forming a UV-opaque surface film',
    ],
    correct: 1,
    explanation: 'HALS (e.g., Tinuvin 770) work by a radical scavenging mechanism — the hindered amine is oxidized to a nitroxyl radical that traps peroxy radicals (ROO•) generated by UV-induced oxidation. The nitroxyl radical is regenerated in a catalytic cycle, making HALS very efficient at low concentrations (0.1-0.5%). They do not absorb UV themselves — that is the role of UV absorbers like benzotriazoles.',
    marks: 2,
  },
  {
    id: 'gc5', subject: 'Polymer Chemistry', lessonSlug: 'copolymers-blends-and-alloys',
    question: 'ABS (Acrylonitrile-Butadiene-Styrene) is a terpolymer where the butadiene component primarily contributes:',
    options: ['Chemical resistance', 'Impact strength and toughness', 'Rigidity and modulus', 'Heat resistance'],
    correct: 1,
    explanation: 'In ABS, each monomer contributes distinct properties: Acrylonitrile → chemical resistance and heat resistance; Butadiene rubber phase → impact strength and toughness (the rubber particles cavitate and absorb energy during impact); Styrene → processability, rigidity, and surface finish. The dispersed rubber phase is the critical component that makes ABS the preferred material for high-impact applications like automotive dashboards.',
    marks: 1,
  },
  {
    id: 'gc6', subject: 'Polymer Chemistry', lessonSlug: 'crystallinity-and-morphology-in-polymers',
    question: 'Isotactic polypropylene has a higher melting point than atactic PP because:',
    options: [
      'It has higher molecular weight',
      'Regular spatial arrangement of methyl groups allows efficient chain packing into crystalline lamellae',
      'It contains more double bonds',
      'It has lower density',
    ],
    correct: 1,
    explanation: 'Isotactic PP has all methyl substituents on the same side of the backbone — this regular stereoregularity allows chains to pack into helical crystalline structures (3/1 helix, Tm ~165°C). Atactic PP has random methyl placement — cannot crystallize, remains amorphous with no distinct Tm, behaving as a sticky wax at room temperature. Ziegler-Natta catalysis produces isotactic PP; radical polymerization produces mostly atactic PP.',
    marks: 2,
  },

  // Polymer Processing (5 questions)
  {
    id: 'pp1', subject: 'Polymer Processing', lessonSlug: 'injection-moulding-process-parameters-and-defects',
    question: 'In injection moulding, the V-P (velocity-pressure) switchover is typically set at:',
    options: ['50% of cavity fill', '75% of cavity fill', '95-98% of cavity fill', '100% of cavity fill'],
    correct: 2,
    explanation: 'V-P switchover at 95-98% fill transitions from velocity-controlled filling to pressure-controlled packing. Switching too early (at 90%) leaves the cavity underfilled before pressure control begins. Switching too late (at 100%) causes flash as velocity drives melt past complete fill. The optimum leaves a small cushion for pressure to complete packing without overpacking.',
    marks: 1,
  },
  {
    id: 'pp2', subject: 'Polymer Processing', lessonSlug: 'extrusion-fundamentals-the-backbone-of-plastic-processing',
    question: 'The output rate of a single-screw extruder is primarily controlled by:',
    options: ['Barrel temperature only', 'Screw speed (RPM) — the primary variable for output control', 'Die pressure only', 'Feed hopper level'],
    correct: 1,
    explanation: 'In single-screw extrusion, screw speed is the primary output control variable — doubling RPM approximately doubles output (within the stable operating range). Barrel temperature primarily controls melt quality and viscosity. Die pressure is a consequence of output rate and die resistance. Feed hopper level affects output only if the extruder becomes starve-fed, which is abnormal operation.',
    marks: 1,
  },
  {
    id: 'pp3', subject: 'Polymer Processing', lessonSlug: 'melt-flow-index-mfi-measurement-significance-and-indian-standards',
    question: 'MFI is measured at 230°C/2.16kg for PP. A PP grade with MFI = 30 g/10min is most suitable for:',
    options: [
      'HDPE pressure pipe (requires high MW for strength)',
      'Thin-wall injection moulded parts and fibres (requires easy flow)',
      'Blow moulded containers (requires high melt strength)',
      'Rotational moulding (requires powder form)',
    ],
    correct: 1,
    explanation: 'High MFI (30 g/10min) indicates low molecular weight and low viscosity at 230°C — exactly what is needed to fill thin-walled containers (0.4-0.8 mm) at rapid cycle times without excessive injection pressure. Extrusion and blow moulding require low MFI (0.2-2.0 g/10min) for sufficient parison/melt strength to resist sagging.',
    marks: 1,
  },
  {
    id: 'pp4', subject: 'Polymer Processing', lessonSlug: 'blow-moulding-processes-extrusion-injection-and-stretch-blow',
    question: 'In PET stretch blow moulding (ISBM), biaxial orientation improves bottle properties primarily by:',
    options: [
      'Increasing polymer density only',
      'Inducing strain crystallization in both hoop and axial directions — increasing tensile strength and CO₂/O₂ barrier',
      'Reducing the glass transition temperature',
      'Decreasing wall thickness uniformity',
    ],
    correct: 1,
    explanation: 'Biaxial stretch (stretch rod gives axial orientation; blow air gives hoop/radial orientation) stretches PET chains near Tg (~90-100°C), inducing strain crystallization (up to ~30%). This aligns chains in both planes — increasing tensile strength by 3-4× and dramatically reducing gas permeability (permeation path becomes tortuous). This is why lightweight PET bottles can hold 4-6 bar carbonation pressure.',
    marks: 2,
  },
  {
    id: 'pp5', subject: 'Polymer Processing', lessonSlug: 'thermoforming-techniques-and-applications',
    question: 'In vacuum thermoforming, the maximum theoretical forming pressure available is:',
    options: ['0.1 MPa (1 bar — atmospheric pressure)', '1.0 MPa (10 bar)', '10 MPa', 'Infinite with high-capacity pump'],
    correct: 0,
    explanation: 'Vacuum thermoforming works by evacuating air from between the heated sheet and the mold cavity — atmospheric pressure (1 bar / 0.1 MPa) then pushes the sheet against the mold. The maximum differential pressure cannot exceed 1 atmosphere (14.7 psi / 100 kPa), regardless of pump size. For deeper draws or fine detail, pressure forming uses compressed air (3-6 bar) on the upper sheet surface to exceed atmospheric limits.',
    marks: 1,
  },

  // Testing & Characterization (5 questions)
  {
    id: 'pt1', subject: 'Polymer Testing', lessonSlug: 'tensile-testing-astm-d638-is-13360-stress-strain-curves-decoded',
    question: 'In an ASTM D638 tensile test of an unreinforced thermoplastic, the point where stress reaches a local maximum and necking begins is called:',
    options: ['Proportional limit', 'Yield point', 'Ultimate tensile strength', 'Fracture point'],
    correct: 1,
    explanation: 'The yield point on an engineering stress-strain curve marks the onset of plastic (permanent) deformation and localized cross-sectional reduction (necking). Beyond yield, polymer chains begin to slide past one another and align in the draw direction (strain hardening). Engineering yield strength is calculated as peak yield load divided by original cross-sectional area.',
    marks: 1,
  },
  {
    id: 'pt2', subject: 'Polymer Testing', lessonSlug: 'differential-scanning-calorimetry-dsc-thermal-fingerprints',
    question: 'In a DSC thermogram of a semi-crystalline polymer, an exothermic peak observed during heating (between Tg and Tm) corresponds to:',
    options: ['Melting', 'Cold crystallization', 'Thermal degradation', 'Glass transition'],
    correct: 1,
    explanation: 'Cold crystallization occurs when a rapidly quenched (mostly amorphous) polymer is heated above Tg. Above Tg, chain mobility is restored, allowing disordered chains to reorganize into lower-energy crystalline lamellae before reaching Tm. Because crystallization releases latent heat (exothermic), it appears as a dip/peak below the baseline (or above, depending on heat-flow sign convention). Melting is endothermic.',
    marks: 2,
  },
  {
    id: 'pt3', subject: 'Polymer Testing', lessonSlug: 'thermogravimetric-analysis-tga-thermal-stability-and-filler-content',
    question: 'TGA is used to determine the inorganic filler content (e.g. glass fiber, CaCO₃) in a polymer composite by:',
    options: [
      'Measuring thermal expansion up to 200°C',
      'Heating the sample in inert/oxidative atmosphere to ~600-800°C to pyrolyze the polymer matrix, leaving non-volatile filler residue',
      'Measuring dielectric loss vs temperature',
      'Determining the heat of fusion during melting',
    ],
    correct: 1,
    explanation: 'In TGA filler analysis, the sample is heated to 600-800°C in nitrogen/air. The organic polymer matrix completely pyrolyzes into volatile gases, producing a major mass drop step. The remaining mass percentage at 600-800°C represents the non-volatile inorganic filler (glass fiber, mineral filler, carbon black if atmosphere switched to oxygen). This is the standard method specified in ASTM E1131.',
    marks: 1,
  },
  {
    id: 'pt4', subject: 'Polymer Testing', lessonSlug: 'izod-and-charpy-impact-testing-astm-d256-notch-sensitivity',
    question: 'In Izod impact testing (ASTM D256), the specimen is mounted as a:',
    options: ['Simply supported beam (supported at both ends)', 'Vertical cantilever beam (clamped at one end, struck at free end)', 'Flat disc clamped along the circumference', 'Tension bar pulled at constant speed'],
    correct: 1,
    explanation: 'Izod testing (ASTM D256) clamps the notched specimen vertically as a cantilever beam — the pendulum strikes the free end above the notch on the same side as the notch facing the striker. Charpy testing (ISO 179 / ASTM E23) supports the specimen horizontally at both ends as a simple beam and strikes it in the middle directly behind the notch.',
    marks: 1,
  },
  {
    id: 'pt5', subject: 'Polymer Testing', lessonSlug: 'heat-deflection-temperature-hdt-and-vicat-softening-point',
    question: 'Heat Deflection Temperature (HDT, ASTM D648) measures the temperature at which a specimen deflects by 0.25 mm under a standard flexural load of:',
    options: ['0.455 MPa or 1.82 MPa', '5.0 MPa or 10.0 MPa', '0.01 MPa only', '100 MPa'],
    correct: 0,
    explanation: 'ASTM D648 specifies two standard flexural stress levels: Method A at 1.82 MPa (264 psi) for high-rigidity structural applications, and Method B at 0.455 MPa (66 psi) for lower-stress applications. HDT indicates short-term load-bearing capability at elevated temperatures, which is critical for automotive engine compartment parts.',
    marks: 2,
  },

  // Rubber & Composites (5 questions)
  {
    id: 'rc1', subject: 'Rubber Technology', lessonSlug: 'vulcanization-kinetics-sulfur-vs-peroxide-curing',
    question: 'In sulfur vulcanization of natural rubber, the addition of zinc oxide and stearic acid serves to:',
    options: [
      'Increase the solubility of sulfur only',
      'Form a zinc stearate complex that activates the sulfur-accelerator system, increasing vulcanization rate and crosslink efficiency',
      'Act as plasticizers to lower viscosity',
      'Prevent oxidative degradation during service',
    ],
    correct: 1,
    explanation: 'ZnO + stearic acid form a soluble zinc stearate complex that reacts with organic accelerators (e.g. CBS, TBTD) to generate active sulfurating species. This increases crosslinking efficiency — converting polysulfidic links (-S-S-S-) to more thermally stable mono- and disulfidic links (-S- and -S-S-), reducing cure time and improving reversion resistance.',
    marks: 2,
  },
  {
    id: 'rc2', subject: 'Rubber Technology', lessonSlug: 'elastomer-selection-guide-nr-sbr-epdm-nbr-fkm-silicone',
    question: 'Which elastomer is specifically selected for automotive fuel hoses due to its exceptional resistance to petroleum oils and fuels?',
    options: ['Natural Rubber (NR)', 'Ethylene Propylene Diene Monomer (EPDM)', 'Nitrile Butadiene Rubber (NBR)', 'Silicone Rubber (VMQ)'],
    correct: 2,
    explanation: 'NBR (Nitrile Rubber) contains polar acrylonitrile (-C≡N) groups that provide excellent resistance to non-polar petroleum fuels, oils, and greases. Higher acrylonitrile content (33-50%) increases fuel resistance and tensile strength, though it reduces low-temperature flexibility. EPDM has zero oil resistance due to its non-polar polyolefin backbone, making it unsuitable for fuel contact.',
    marks: 1,
  },
  {
    id: 'rc3', subject: 'Composites', lessonSlug: 'carbon-fiber-reinforced-polymers-cfrp-manufacturing-and-properties',
    question: 'The specific strength (strength-to-weight ratio) of carbon fiber composite (CFRP) compared to structural steel (FE 410) is approximately:',
    options: ['Same', '2× higher', '5-8× higher', '20× higher'],
    correct: 2,
    explanation: 'CFRP has a density of ~1.5-1.6 g/cm³ and tensile strength of 1500-2500 MPa, giving a specific strength of ~1000-1600 kN·m/kg. Structural steel has density ~7.85 g/cm³ and strength ~410-550 MPa, giving specific strength of ~50-70 kN·m/kg. CFRP is 5-8× higher in specific strength, making it indispensable for weight-critical aerospace and automotive applications.',
    marks: 2,
  },
  {
    id: 'rc4', subject: 'Composites', lessonSlug: 'resin-transfer-moulding-rtm-and-vacuum-assisted-processes',
    question: 'In Resin Transfer Moulding (RTM), Darcy\'s Law governs liquid resin flow through the dry fiber preform. Flow velocity (v) is proportional to:',
    options: [
      'Preform permeability (K) and pressure gradient (dP/dx), inversely proportional to resin viscosity (μ)',
      'Resin viscosity squared',
      'Fiber diameter only',
      'Mold temperature only',
    ],
    correct: 0,
    explanation: 'Darcy\'s Law for flow through porous media states: v = -(K / μ) · (dP/dx). Higher preform permeability (K) and higher injection pressure gradient (dP/dx) increase fill speed. Lower resin viscosity (μ, typically <500 mPa·s at injection temperature) is critical to prevent dry spots and achieve complete preform wet-out before resin gelation.',
    marks: 2,
  },
  {
    id: 'rc5', subject: 'Recycling', lessonSlug: 'mechanical-recycling-sorting-washing-re-granulation',
    question: 'In post-consumer PET bottle recycling, automated optical sorting uses NIR (Near-Infrared) spectroscopy to distinguish PET from PVC because:',
    options: [
      'PET and PVC have different colors under visible light',
      'PET and PVC have distinct overtone absorption spectra in the 1000-1700 nm NIR region',
      'PVC is magnetic while PET is non-magnetic',
      'PET floats in water while PVC sinks',
    ],
    correct: 1,
    explanation: 'NIR spectroscopy identifies polymers by their unique C-H, O-H, and N-H vibrational overtone absorptions in the 1000-1700 nm wavelength range. NIR sensors detect the chemical signature of incoming bottles on a high-speed conveyor (2-3 m/s) in milliseconds, triggering air jets to blast PVC bottles out of the PET stream. This prevents PVC contamination (>50 ppm causes acid degradation during rPET processing).',
    marks: 1,
  },

  // Mould Design & Sustainability (4 questions)
  {
    id: 'ms1', subject: 'Mould Design', lessonSlug: 'injection-mould-runner-systems-cold-vs-hot-runner-design',
    question: 'In hot runner mold design, the primary advantage of valve-gated hot runners over open-tip hot runners is:',
    options: [
      'Lower mold manufacturing cost',
      'Elimination of gate vestige (leaves a flush surface) and independent control of gate open/close timing for sequential filling',
      'Reduced heating power requirement',
      'Compatibility with PVC processing',
    ],
    correct: 1,
    explanation: 'Valve-gated hot runners use hydraulic/pneumatic pin actuators to mechanically shut off the gate orifice at the end of holding phase. This leaves a virtually invisible, flush gate mark (no vestige/drooling) and allows sequential valve gating (SVG) to eliminate weld lines in large automotive parts like bumpers by opening gates sequentially as the melt front advances.',
    marks: 2,
  },
  {
    id: 'ms2', subject: 'Mould Design', lessonSlug: 'conformal-cooling-in-injection-moulds-3d-metal-printing',
    question: '3D metal printed conformal cooling channels improve injection moulding productivity primarily by:',
    options: [
      'Reducing mold steel cost',
      'Following the exact 3D contour of the cavity to provide uniform heat extraction, reducing cooling time by 20-40% and minimizing warpage',
      'Eliminating the need for mold temperature controllers',
      'Increasing clamping force capacity',
    ],
    correct: 1,
    explanation: 'Conventional cooling channels are straight holes drilled into mold steel — they cannot follow complex curved cavity geometry, creating hot spots that dictate long cooling times and cause non-uniform thermal shrinkage (warpage). DMLS/SLM 3D metal printing enables curved channels positioned at constant distance from cavity walls, maximizing cooling rate and dimensional stability.',
    marks: 2,
  },
  {
    id: 'ms3', subject: 'Sustainability', lessonSlug: 'life-cycle-assessment-lca-of-polymers-cradle-to-grave-carbon-footprint',
    question: 'In ISO 14040 Life Cycle Assessment (LCA), Global Warming Potential (GWP) is expressed in units of:',
    options: ['kg SO₂ equivalent', 'kg CO₂ equivalent per functional unit', 'MJ of primary energy', 'ppm of VOC'],
    correct: 1,
    explanation: 'GWP measures the total radiative forcing of greenhouse gas emissions (CO₂, CH₄, N₂O, HFCs) integrated over a 100-year time horizon, normalized to kg CO₂ equivalent per functional unit (e.g. 1 kg of polymer resin or 1,000 beverage containers). SimaPro and GaBi software calculate GWP using IPCC characterization factors.',
    marks: 1,
  },
  {
    id: 'ms4', subject: 'Sustainability', lessonSlug: 'extended-producer-responsibility-epr-for-plastics-in-india',
    question: 'Under India\'s MoEFCC Extended Producer Responsibility (EPR) Guidelines 2022, Category I plastics refer to:',
    options: [
      'Flexible plastic packaging (single layer or multilayer)',
      'Rigid plastic packaging',
      'Multilayered plastic packaging (having at least one layer of plastic and at least one layer of material other than plastic)',
      'Plastic sheet or like used for packaging and compostable plastic',
    ],
    correct: 1,
    explanation: 'India\'s EPR Guidelines 2022 classify plastic packaging into 4 categories: Category I = Rigid plastic packaging; Category II = Flexible plastic packaging (single or multilayer); Category III = Multilayered plastic packaging (plastic + non-plastic like aluminum foil); Category IV = Plastic sheet/film used for packaging and compostable plastics. Obligated entities must register on the CPCB portal and fulfill minimum recycling targets for each category.',
    marks: 1,
  },
]

const SUBJECT_COLORS: Record<string, string> = {
  'Polymer Chemistry': 'bg-[#2563EB] text-white',
  'Polymer Processing': 'bg-[#EA580C] text-white',
  'Polymer Testing': 'bg-[#EF4444] text-white',
  'Rubber Technology': 'bg-[#8B5CF6] text-white',
  'Composites': 'bg-[#0284C7] text-white',
  'Recycling': 'bg-[#059669] text-white',
  'Mould Design': 'bg-[#059669] text-white',
  'Sustainability': 'bg-[#16A34A] text-white',
}

type QuizState = 'setup' | 'active' | 'submitted'
type AnswerMap = Record<string, number>

// ─── Dynamic Color-Changing Timer ─────────────────────────────────────────────

function DynamicTimer({ seconds, onTimeout }: { seconds: number; onTimeout: () => void }) {
  const [remaining, setRemaining] = useState(seconds)

  useEffect(() => {
    if (remaining <= 0) {
      onTimeout()
      return
    }
    const timer = setInterval(() => {
      setRemaining(prev => prev - 1)
    }, 1000)
    return () => clearInterval(timer)
  }, [remaining, onTimeout])

  const mins = Math.floor(remaining / 60)
  const secs = remaining % 60

  // Dynamic timer color thresholds
  let timerStyle = 'border-slate-800 bg-slate-900 text-[#F5C518]' // Default 10+ mins
  if (remaining < 120) {
    timerStyle = 'border-red-600 bg-red-600 text-white font-black animate-pulse shadow-md' // <2 mins Red Alert
  } else if (remaining < 600) {
    timerStyle = 'border-amber-500/50 bg-amber-500/20 text-amber-300 font-bold' // <10 mins Amber Warning
  }

  return (
    <div className={`flex items-center gap-2 border-2 rounded-xl px-4 py-2 font-mono text-sm transition-all ${timerStyle}`}>
      <Clock className="w-4 h-4" />
      <span>{String(mins).padStart(2, '0')}:{String(secs).padStart(2, '0')}</span>
    </div>
  )
}

// ─── Score Report Component ───────────────────────────────────────────────────

function ScoreReport({ answers, timeTaken }: { answers: AnswerMap; timeTaken: number }) {
  const totalMarks = GATE_QUESTIONS.reduce((a, q) => a + q.marks, 0)
  let scored = 0
  let correct = 0
  let wrong = 0
  let unattempted = 0

  GATE_QUESTIONS.forEach(q => {
    if (answers[q.id] === undefined) {
      unattempted++
    } else if (answers[q.id] === q.correct) {
      scored += q.marks
      correct++
    } else {
      // GATE negative marking: -1/3 for 1-mark, -2/3 for 2-mark
      scored -= q.marks / 3
      wrong++
    }
  })

  const mins = Math.floor(timeTaken / 60)
  const secs = timeTaken % 60

  const subjects = GATE_QUESTIONS.map(q => q.subject).filter((value, index, self) => self.indexOf(value) === index)
  const subjectBreakdown = subjects.map(sub => {
    const subQs = GATE_QUESTIONS.filter(q => q.subject === sub)
    const subMarks = subQs.reduce((a, q) => a + q.marks, 0)
    let subScored = 0
    subQs.forEach(q => {
      if (answers[q.id] === q.correct) subScored += q.marks
      else if (answers[q.id] !== undefined) subScored -= q.marks / 3
    })
    return { subject: sub, scored: Math.max(0, subScored), total: subMarks, pct: Math.round((Math.max(0, subScored) / subMarks) * 100) }
  })

  return (
    <div className="space-y-6">
      {/* Main Score Banner */}
      <div className="border-2 border-slate-900 rounded-2xl bg-white shadow-xl overflow-hidden">
        <div className="bg-[#0A1628] text-white p-8 text-center space-y-2">
          <span className="text-xs font-mono font-bold tracking-widest text-[#F5C518] uppercase">Official GATE Scoring Breakdown</span>
          <div className="font-display text-5xl sm:text-6xl font-black">
            {Math.max(0, scored).toFixed(2)}
            <span className="text-2xl text-slate-400 font-light"> / {totalMarks} Marks</span>
          </div>
          <p className="text-xs text-slate-300">
            Negative marking included (&minus;1/3 mark per wrong 1-mark MCQ, &minus;2/3 mark per wrong 2-mark MCQ).
          </p>
        </div>

        <div className="p-6 space-y-6">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-200 text-center">
              <div className="font-display text-2xl font-bold text-emerald-800">{correct}</div>
              <div className="text-[10px] font-mono font-bold uppercase text-emerald-700 mt-1">Correct Answers</div>
            </div>
            <div className="p-4 bg-rose-50 rounded-xl border border-rose-200 text-center">
              <div className="font-display text-2xl font-bold text-rose-800">{wrong}</div>
              <div className="text-[10px] font-mono font-bold uppercase text-rose-700 mt-1">Wrong Answers</div>
            </div>
            <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-center">
              <div className="font-display text-2xl font-bold text-slate-800">{unattempted}</div>
              <div className="text-[10px] font-mono font-bold uppercase text-slate-500 mt-1">Unattempted</div>
            </div>
            <div className="p-4 bg-blue-50 rounded-xl border border-blue-200 text-center">
              <div className="font-display text-2xl font-bold text-blue-800">{mins}m {secs}s</div>
              <div className="text-[10px] font-mono font-bold uppercase text-blue-700 mt-1">Time Elapsed</div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 pt-2">
            <Link 
              href="/practice" 
              className="flex-1 py-3 text-center bg-[#F5C518] hover:bg-amber-400 text-slate-950 font-mono font-bold text-xs uppercase tracking-wider rounded-xl border-2 border-slate-900 shadow-sm"
            >
              Practice More Challenges &rarr;
            </Link>
            <Link 
              href="/ai-tutor?prompt=Explain%20how%20to%20improve%20GATE%20Polymer%20Science%20score%20and%20master%20free%20radical%20polymerization%20kinetics" 
              className="flex-1 py-3 text-center bg-slate-900 hover:bg-slate-800 text-white font-mono font-bold text-xs uppercase tracking-wider rounded-xl border-2 border-slate-900 shadow-sm"
            >
              <Brain className="w-3.5 h-3.5 inline mr-1.5" /> Ask AI GATE Coach
            </Link>
          </div>
        </div>
      </div>

      {/* Subject Breakdown */}
      <div className="bg-white border-2 border-slate-900 rounded-2xl p-6 shadow-xl space-y-4">
        <h3 className="font-display font-bold text-base uppercase text-slate-900">
          Subject-wise Score Analysis
        </h3>

        <div className="space-y-4">
          {subjectBreakdown.map(s => (
            <div key={s.subject} className="space-y-1.5">
              <div className="flex justify-between text-xs font-mono font-bold">
                <span className="text-slate-800">{s.subject}</span>
                <span className="text-blue-700">{s.scored.toFixed(1)} / {s.total} Marks ({s.pct}%)</span>
              </div>
              <div className="w-full h-2 bg-slate-100 rounded-full overflow-hidden border border-slate-200">
                <div 
                  className="h-full bg-blue-600 rounded-full transition-all duration-500" 
                  style={{ width: `${s.pct}%` }} 
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Detailed Question Review */}
      <div className="space-y-4">
        <h3 className="font-display font-bold text-base uppercase text-slate-900">
          Complete Answer Review ({GATE_QUESTIONS.length} Questions)
        </h3>

        {GATE_QUESTIONS.map((q, idx) => {
          const userAnswer = answers[q.id]
          const isCorrect = userAnswer === q.correct
          const isUnattempted = userAnswer === undefined

          return (
            <article key={q.id} className="border-2 border-slate-900 rounded-2xl bg-white p-6 shadow-sm space-y-3">
              <div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3">
                <div className="flex items-center gap-2">
                  {isUnattempted ? (
                    <span className="inline-flex items-center gap-1 text-slate-500 font-mono text-xs font-bold">
                      <AlertTriangle className="w-4 h-4 text-slate-400" /> Unattempted
                    </span>
                  ) : isCorrect ? (
                    <span className="inline-flex items-center gap-1 text-emerald-700 font-mono text-xs font-bold">
                      <CheckCircle className="w-4 h-4 text-emerald-600" /> Correct (+{q.marks})
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-rose-700 font-mono text-xs font-bold">
                      <XCircle className="w-4 h-4 text-rose-600" /> Wrong (&minus;{(q.marks / 3).toFixed(2)})
                    </span>
                  )}
                </div>
                <span className="font-mono text-[10px] font-bold text-slate-500 uppercase bg-slate-100 px-2 py-0.5 rounded-full">
                  {q.subject}
                </span>
              </div>

              <p className="font-display font-bold text-sm sm:text-base text-slate-900 leading-snug">
                Q{idx + 1}. {q.question}
              </p>

              <div className="space-y-2">
                {q.options.map((opt, optIdx) => {
                  const isCorrectOpt = optIdx === q.correct
                  const isUserChoice = optIdx === userAnswer

                  return (
                    <div 
                      key={optIdx} 
                      className={`p-3 rounded-xl border-2 text-xs font-medium flex items-center justify-between gap-3 ${
                        isCorrectOpt 
                          ? 'border-emerald-500 bg-emerald-50 text-emerald-950 font-bold'
                          : isUserChoice 
                          ? 'border-rose-500 bg-rose-50 text-rose-950 font-bold'
                          : 'border-slate-200 bg-slate-50 text-slate-700'
                      }`}
                    >
                      <div className="flex items-center gap-2.5">
                        <span className="font-mono font-bold w-5">{['A', 'B', 'C', 'D'][optIdx]}.</span>
                        <span>{opt}</span>
                      </div>
                      {isCorrectOpt && <CheckCircle className="w-4 h-4 text-emerald-600 flex-shrink-0" />}
                      {isUserChoice && !isCorrectOpt && <XCircle className="w-4 h-4 text-rose-600 flex-shrink-0" />}
                    </div>
                  )
                })}
              </div>

              <div className="p-3.5 bg-blue-50/70 rounded-xl border border-blue-200 text-xs text-blue-950 space-y-1">
                <span className="font-mono font-bold text-[10px] text-blue-800 uppercase tracking-wider block">Rationale &amp; Solution</span>
                <p className="leading-relaxed">{q.explanation}</p>
              </div>

              <div className="pt-1">
                <Link 
                  href={`/lessons/${q.lessonSlug}`}
                  className="font-mono text-xs font-bold text-blue-600 hover:text-blue-800 uppercase flex items-center gap-1"
                >
                  <BookOpen className="w-3.5 h-3.5" /> Read Lesson &rarr;
                </Link>
              </div>
            </article>
          )
        })}
      </div>
    </div>
  )
}

// ─── Main GATE Mock Page ──────────────────────────────────────────────────────

export default function GATEMockPage() {
  const [state, setState] = useState<QuizState>('setup')
  const [answers, setAnswers] = useState<AnswerMap>({})
  const [currentQ, setCurrentQ] = useState(0)
  const [startTime, setStartTime] = useState<number>(0)
  const [timeTaken, setTimeTaken] = useState(0)
  const [flagged, setFlagged] = useState<Set<string>>(new Set())
  const [isSubmitModalOpen, setIsSubmitModalOpen] = useState(false)

  const TOTAL_TIME = 60 * 60 // 60 minutes

  const handleStart = () => {
    setStartTime(Date.now())
    setAnswers({})
    setCurrentQ(0)
    setFlagged(new Set())
    setIsSubmitModalOpen(false)
    setState('active')
  }

  const confirmSubmit = () => {
    setIsSubmitModalOpen(false)
    setTimeTaken(Math.round((Date.now() - startTime) / 1000))
    setState('submitted')
  }

  const handleSelect = (optIdx: number) => {
    setAnswers(prev => ({ ...prev, [GATE_QUESTIONS[currentQ].id]: optIdx }))
  }

  const toggleFlag = () => {
    const id = GATE_QUESTIONS[currentQ].id
    setFlagged(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  const answered = Object.keys(answers).length
  const currentQuestion = GATE_QUESTIONS[currentQ]
  const currentAnswer = answers[currentQuestion?.id]
  const isFlagged = flagged.has(currentQuestion?.id)

  return (
    <div className="min-h-screen bg-[#FAF8F5] text-slate-900 pb-20">

      {/* ── HERO SECTION: Midnight Navy with Indian Tricolor Accent ── */}
      <section className="bg-[#0A1628] text-white py-16 md:py-20 px-4 sm:px-6 border-b-2 border-slate-900 relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.15)_0%,transparent_70%)] pointer-events-none" />
        
        <div className="relative z-10 max-w-5xl mx-auto text-center space-y-4">
          <div className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-md border border-white/20 rounded-full px-4 py-1.5 mb-2">
            <Trophy className="w-4 h-4 text-amber-400" />
            <span className="text-xs font-mono font-bold tracking-widest uppercase text-white/90">
              GATE XE-F Polymer Science &amp; Engineering &middot; Timed Practice Mock
            </span>
          </div>

          <h1 className="font-display text-3xl sm:text-5xl md:text-6xl font-black leading-tight tracking-tight uppercase">
            GATE Polymer Science <br />
            <span className="inline-block text-transparent bg-clip-text bg-gradient-to-r from-[#FF8A00] via-[#FFFFFF] to-[#16A34A] pb-2.5 pt-0.5 leading-[1.15]">
              Mock Test Arena
            </span>
          </h1>

          <p className="text-sm sm:text-base md:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed font-light">
            Timed practice simulation strictly aligned with GATE (XE-F / CY / CH) syllabus standards. Includes authentic negative marking (&minus;1/3 &amp; &minus;2/3) and instant rationale breakdown.
          </p>

          {/* Quick Metrics */}
          <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-white block">30</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">GATE Questions</span>
            </div>
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-amber-400 block">35</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Total Marks</span>
            </div>
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-emerald-400 block">60 Min</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">Continuous Timer</span>
            </div>
            <div className="bg-white/10 border border-white/15 px-4 py-2 rounded-xl text-center">
              <span className="font-display text-xl font-bold text-rose-400 block">&minus;1/3 / &minus;2/3</span>
              <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">MCQ Negative Marking</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── Main Workspace ── */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 -mt-8 relative z-20 space-y-8">
        
        {/* Setup Screen */}
        {state === 'setup' && (
          <div className="bg-white border-2 border-slate-900 rounded-2xl p-6 sm:p-8 shadow-xl space-y-6">
            <div>
              <h2 className="font-display font-bold text-xl uppercase text-slate-900">
                📋 Exam Protocol &amp; Instructions
              </h2>
              <p className="text-xs sm:text-sm text-slate-500 font-medium mt-1">
                Please read the official evaluation criteria before starting the practice session.
              </p>
            </div>

            <div className="p-4 bg-amber-50 rounded-xl border border-amber-200 space-y-2">
              <span className="font-mono text-xs font-bold text-amber-900 uppercase tracking-wide block">Evaluation Rules</span>
              <ul className="space-y-1.5 text-xs text-amber-950 font-medium">
                <li>&bull; 1-Mark MCQ: +1.0 for correct, &minus;0.33 for incorrect.</li>
                <li>&bull; 2-Mark MCQ: +2.0 for correct, &minus;0.67 for incorrect.</li>
                <li>&bull; Unattempted questions carry zero penalty.</li>
                <li>&bull; You can freely navigate, clear choices, or flag items for review.</li>
                <li>&bull; The 60-minute timer runs continuously upon clicking Start.</li>
              </ul>
            </div>

            <div>
              <span className="font-mono text-xs font-bold text-slate-500 uppercase tracking-wide block mb-2">Subjects Tested</span>
              <div className="flex flex-wrap gap-2">
                {Object.entries(SUBJECT_COLORS).map(([sub]) => (
                  <span key={sub} className="px-3 py-1 bg-slate-100 text-slate-800 text-xs font-mono font-bold rounded-lg border border-slate-200">
                    {sub}
                  </span>
                ))}
              </div>
            </div>

            <button
              onClick={handleStart}
              className="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white font-mono font-bold text-sm uppercase tracking-wider rounded-xl border-2 border-blue-700 shadow-md hover:translate-y-[-1px] transition-all flex items-center justify-center gap-2"
            >
              <PlayCircle className="w-5 h-5" /> Start GATE Timed Practice Mock &mdash; 60 Minutes
            </button>
            <p className="text-[11px] font-mono text-slate-500 text-center">
              * Educational simulation aligned with GATE XE-F Polymer Science &amp; Engineering syllabus standards.
            </p>
          </div>
        )}

        {/* Active Exam Mode */}
        {state === 'active' && currentQuestion && (
          <div className="space-y-6">
            
            {/* Top Toolbar with Timer & Flag */}
            <div className="bg-white border-2 border-slate-900 rounded-2xl p-4 sm:p-5 shadow-xl flex items-center justify-between gap-4 flex-wrap">
              <div className="flex items-center gap-3">
                <span className="font-display font-bold text-base text-slate-900">
                  Question {currentQ + 1} of {GATE_QUESTIONS.length}
                </span>
              </div>

              <div className="flex items-center gap-3">
                {/* Prominent Flag for Review Button */}
                <button
                  onClick={toggleFlag}
                  className={`px-4 py-2 rounded-xl font-mono text-xs font-bold flex items-center gap-1.5 transition-all border-2 ${
                    isFlagged
                      ? 'bg-amber-400 text-slate-950 border-amber-500 shadow-sm'
                      : 'bg-slate-100 hover:bg-slate-200 text-slate-700 border-slate-300'
                  }`}
                >
                  <Flag className="w-3.5 h-3.5 fill-current" />
                  {isFlagged ? '🚩 Flagged for Review' : '🚩 Flag for Review'}
                </button>

                {/* Dynamic Color Changing Timer */}
                <DynamicTimer seconds={TOTAL_TIME} onTimeout={confirmSubmit} />
              </div>
            </div>

            {/* Question Workspace Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 items-start">
              
              {/* Question & Options (3 Columns) */}
              <div className="lg:col-span-3 bg-white border-2 border-slate-900 rounded-2xl p-6 sm:p-8 shadow-xl space-y-6">
                
                <div className="flex items-center justify-between border-b border-slate-100 pb-3 gap-2">
                  <span className={`px-3 py-1 rounded-lg text-xs font-mono font-bold ${SUBJECT_COLORS[currentQuestion.subject] || 'bg-slate-900 text-white'}`}>
                    {currentQuestion.subject}
                  </span>
                  <span className="text-xs font-mono font-bold text-slate-500 bg-slate-100 px-2.5 py-0.5 rounded-full">
                    {currentQuestion.marks} {currentQuestion.marks === 1 ? 'Mark' : 'Marks'}
                  </span>
                </div>

                <p className="font-display font-bold text-base sm:text-lg text-slate-900 leading-snug">
                  {currentQuestion.question}
                </p>

                <div className="space-y-3">
                  {currentQuestion.options.map((opt, optIdx) => {
                    const isSelected = currentAnswer === optIdx
                    return (
                      <button
                        key={optIdx}
                        onClick={() => handleSelect(optIdx)}
                        className={`w-full text-left p-4 rounded-xl border-2 transition-all flex items-center gap-3 ${
                          isSelected
                            ? 'border-blue-600 bg-blue-50 text-blue-950 font-bold shadow-sm'
                            : 'border-slate-200 bg-slate-50 hover:bg-white text-slate-800'
                        }`}
                      >
                        <span className={`w-6 h-6 rounded-lg font-mono text-xs font-bold flex items-center justify-center shrink-0 border ${
                          isSelected ? 'bg-blue-600 text-white border-blue-700' : 'bg-white text-slate-700 border-slate-300'
                        }`}>
                          {['A', 'B', 'C', 'D'][optIdx]}
                        </span>
                        <span className="text-xs sm:text-sm">{opt}</span>
                      </button>
                    )
                  })}
                </div>

                {/* Actions Bottom Bar */}
                <div className="flex justify-between items-center gap-3 pt-4 border-t border-slate-100 flex-wrap">
                  <button
                    onClick={() => setAnswers(prev => {
                      const copy = { ...prev }
                      delete copy[currentQuestion.id]
                      return copy
                    })}
                    className="px-3.5 py-2 border-2 border-slate-200 hover:border-slate-400 text-slate-600 font-mono text-xs font-bold uppercase rounded-xl transition-all"
                  >
                    Clear Choice
                  </button>

                  <div className="flex gap-2">
                    <button
                      disabled={currentQ === 0}
                      onClick={() => setCurrentQ(prev => prev - 1)}
                      className="px-4 py-2 border-2 border-slate-200 text-slate-700 disabled:opacity-40 font-mono text-xs font-bold uppercase rounded-xl hover:bg-slate-50 transition-all"
                    >
                      &larr; Prev
                    </button>
                    {currentQ < GATE_QUESTIONS.length - 1 ? (
                      <button
                        onClick={() => setCurrentQ(prev => prev + 1)}
                        className="px-5 py-2 bg-slate-900 hover:bg-slate-800 text-white font-mono text-xs font-bold uppercase rounded-xl transition-all"
                      >
                        Next &rarr;
                      </button>
                    ) : (
                      <button
                        onClick={() => setIsSubmitModalOpen(true)}
                        className="px-6 py-2 bg-red-600 hover:bg-red-700 text-white font-mono text-xs font-bold uppercase rounded-xl transition-all shadow-md"
                      >
                        Submit Test
                      </button>
                    )}
                  </div>
                </div>
              </div>

              {/* Question Palette Sidebar (1 Column) */}
              <div className="bg-white border-2 border-slate-900 rounded-2xl p-5 shadow-xl space-y-4">
                <span className="font-mono text-xs font-bold text-slate-400 uppercase tracking-wider block border-b border-slate-100 pb-2">
                  Question Palette
                </span>

                <div className="grid grid-cols-5 gap-1.5">
                  {GATE_QUESTIONS.map((q, idx) => {
                    const isQAnswered = answers[q.id] !== undefined
                    const isQFlagged = flagged.has(q.id)
                    const isQCurrent = idx === currentQ
                    
                    let bg = 'bg-slate-50 text-slate-700 border-slate-200'
                    if (isQCurrent) {
                      bg = 'bg-blue-600 text-white border-blue-700 font-black ring-2 ring-blue-300'
                    } else if (isQFlagged) {
                      bg = 'bg-amber-400 text-slate-950 border-amber-500 font-bold'
                    } else if (isQAnswered) {
                      bg = 'bg-emerald-600 text-white border-emerald-700 font-bold'
                    }
                    
                    return (
                      <button
                        key={q.id}
                        onClick={() => setCurrentQ(idx)}
                        className={`h-8 rounded-lg border text-xs font-mono flex items-center justify-center transition-all ${bg}`}
                      >
                        {idx + 1}
                      </button>
                    )
                  })}
                </div>

                <div className="space-y-1.5 pt-2 border-t border-slate-100 text-[11px] font-mono">
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-emerald-600 rounded-sm" />
                    <span>Answered ({answered})</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-amber-400 rounded-sm" />
                    <span>Flagged ({flagged.size})</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 bg-slate-100 border border-slate-300 rounded-sm" />
                    <span>Unattempted ({GATE_QUESTIONS.length - answered})</span>
                  </div>
                </div>

                {/* Submit Exam Button - Red Alert Style */}
                <button
                  onClick={() => setIsSubmitModalOpen(true)}
                  className="w-full py-2.5 bg-red-600 hover:bg-red-700 text-white font-mono text-xs font-bold uppercase rounded-xl transition-all shadow-md"
                >
                  Submit Exam
                </button>
              </div>

            </div>

          </div>
        )}

        {/* Submitted Score Summary */}
        {state === 'submitted' && (
          <ScoreReport answers={answers} timeTaken={timeTaken} />
        )}

      </div>

      {/* ── SUBMISSION CONFIRMATION MODAL ── */}
      {isSubmitModalOpen && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white border-2 border-slate-900 rounded-3xl p-6 sm:p-8 max-w-md w-full shadow-2xl space-y-5 animate-in fade-in zoom-in duration-200">
            <div className="flex items-center gap-3 text-red-600">
              <AlertTriangle className="w-8 h-8 shrink-0" />
              <div>
                <h3 className="font-display font-black text-lg text-slate-900 uppercase">Confirm Exam Submission</h3>
                <span className="text-[11px] font-mono text-slate-500 font-bold uppercase">Irreversible Action</span>
              </div>
            </div>

            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed font-medium">
              Are you sure you want to submit your exam now? Once submitted, your score will be calculated using official GATE negative marking.
            </p>

            <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-2xl space-y-1.5 text-xs font-mono">
              <div className="flex justify-between text-slate-700">
                <span>Answered Questions:</span>
                <strong className="text-emerald-700">{answered}</strong>
              </div>
              <div className="flex justify-between text-slate-700">
                <span>Flagged for Review:</span>
                <strong className="text-amber-700">{flagged.size}</strong>
              </div>
              <div className="flex justify-between text-slate-700">
                <span>Unattempted Questions:</span>
                <strong className="text-rose-700">{GATE_QUESTIONS.length - answered}</strong>
              </div>
            </div>

            <div className="flex items-center gap-3 pt-2">
              <button
                onClick={() => setIsSubmitModalOpen(false)}
                className="flex-1 py-3 bg-slate-100 hover:bg-slate-200 text-slate-800 font-mono text-xs font-bold uppercase rounded-xl border border-slate-300 transition-all"
              >
                Return to Test
              </button>
              <button
                onClick={confirmSubmit}
                className="flex-1 py-3 bg-red-600 hover:bg-red-700 text-white font-mono text-xs font-bold uppercase rounded-xl shadow-md transition-all"
              >
                Confirm &amp; Submit
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── BOTTOM AI GATE COUNSELOR CTA ── */}
      <section className="max-w-5xl mx-auto px-4 sm:px-6 mt-16">
        <div className="bg-[#0A1628] text-white rounded-3xl p-8 sm:p-12 border-2 border-slate-900 shadow-2xl text-center space-y-6">
          <div className="inline-flex items-center gap-2 font-mono text-xs font-bold text-amber-400 bg-white/10 px-4 py-1.5 rounded-full uppercase tracking-widest border border-white/20">
            <Sparkles className="w-3.5 h-3.5 text-amber-400" /> AI GATE Coach &middot; Gemini RAG
          </div>

          <h2 className="font-display text-3xl sm:text-4xl font-black uppercase">
            Need detailed problem walkthroughs? <br />
            <span className="inline-block text-transparent bg-clip-text bg-gradient-to-r from-[#FF8A00] via-[#FFFFFF] to-[#16A34A] pb-2.5 pt-0.5 leading-[1.15]">
              Ask the AI GATE Coach.
            </span>
          </h2>

          <div className="text-slate-300 text-xs sm:text-sm max-w-xl mx-auto leading-relaxed font-light text-left space-y-2 bg-white/5 border border-white/10 p-4 rounded-2xl">
            <span className="font-mono text-[10px] text-amber-400 font-bold uppercase tracking-wider block">Example Step-by-Step AI Prompts:</span>
            <p className="font-mono text-slate-200">&bull; Single screw extruder output &amp; pressure flow rate formula derivation</p>
            <p className="font-mono text-slate-200">&bull; Carothers equation degree of polymerization &amp; gel point math</p>
            <p className="font-mono text-slate-200">&bull; Kelly-Tyson critical fiber length &amp; shear lag stress transfer</p>
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-2">
            <Link
              href="/ai-tutor?prompt=Explain%20how%20to%20solve%20Kelly-Tyson%20critical%20fiber%20length%20problems%20for%20GATE%20Polymer%20Engineering"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-[#F5C518] hover:bg-amber-400 text-slate-950 font-mono font-bold text-xs uppercase tracking-wider px-8 py-4 rounded-xl border-2 border-slate-900 shadow-[4px_4px_0px_0px_#000] hover:shadow-[2px_2px_0px_0px_#000] hover:translate-x-0.5 hover:translate-y-0.5 transition-all"
            >
              <Brain className="w-4 h-4" /> Ask GATE Coach &rarr;
            </Link>

            <Link
              href="/practice"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 text-white font-mono font-bold text-xs uppercase tracking-wider px-8 py-4 rounded-xl border-2 border-white/30 hover:border-white transition-all"
            >
              <Compass className="w-4 h-4" /> 19-Subject Quiz Engine
            </Link>
          </div>
        </div>
      </section>

    </div>
  )
}
