require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

// Define 52 Indian Programs
const INDIAN_PROGRAMS = [
  // Tier 1: Premier (12 CAMPUSES/INSTITUTES)
  {
    slug: "cipet-chennai-btech-plastics-technology",
    name: "B.Tech in Plastics Technology",
    institution: "CIPET Chennai",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹85,000",
    ranking: "NBA Accredited, Tier-1 Center of Excellence",
    admission_process: "TNEA Counseling based on 12th Board marks / JEE Main",
    eligibility: "10+2 with Physics, Chemistry & Mathematics (min 50% aggregate)",
    curriculum_highlights: ["Polymer Chemistry", "Plastics Processing", "Mould Design & CAD/CAM", "Testing & Quality Control", "Additives & Compounding"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "cipet-chennai-mtech-plastics-technology",
    name: "M.Tech in Plastics Technology",
    institution: "CIPET Chennai",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,10,000",
    ranking: "Premier PG Research Hub under Anna University",
    admission_process: "GATE / TANCET Exam followed by Counseling",
    eligibility: "B.E./B.Tech in Polymer/Plastics/Chemical/Mechanical Engineering",
    curriculum_highlights: ["Advanced Polymer Blends", "Structure-Property Relationships", "Design of Moulds & Dies", "Rheology of Polymers"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "ict-mumbai-btech-polymer-engineering",
    name: "B.Tech in Polymer Engineering & Technology",
    institution: "ICT Mumbai",
    location: "Mumbai, Maharashtra",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹1,25,000",
    ranking: "NIRF Rank 5 in Pharmacy/Technology",
    admission_process: "MHT-CET / JEE Main State Counseling",
    eligibility: "10+2 with Physics, Chemistry & Mathematics (min 60% PCM)",
    curriculum_highlights: ["Polymer Synthesis", "Rubber Technology", "Paint & Coatings Technology", "Polymer Processing & Engineering"],
    website_url: "https://www.ictmumbai.edu.in",
    is_indian: true
  },
  {
    slug: "ict-mumbai-mtech-polymer-engineering",
    name: "M.Tech in Polymer Engineering & Technology",
    institution: "ICT Mumbai",
    location: "Mumbai, Maharashtra",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,40,000",
    ranking: "Top-Tier PG Research Department",
    admission_process: "GATE exam in Chemical/Engineering Sciences + Interview",
    eligibility: "B.Tech in Polymer/Chemical Technology / M.Sc Chemistry",
    curriculum_highlights: ["Advanced Polymerization Kinetics", "Polymer Characterization Techniques", "Product Design & Simulation"],
    website_url: "https://www.ictmumbai.edu.in",
    is_indian: true
  },
  {
    slug: "ict-mumbai-phd-polymer-technology",
    name: "Ph.D in Polymer Engineering & Technology",
    institution: "ICT Mumbai",
    location: "Mumbai, Maharashtra",
    country: "India",
    degree_type: "Ph.D",
    duration: "3-5 Years",
    fees_annual: "₹95,000",
    ranking: "World-Class Polymer Research Faculty",
    admission_process: "ICT Written Test followed by Research Interview (GATE/CSIR qualified direct)",
    eligibility: "M.Tech in Polymer/Chemical Technology with min 60% marks",
    curriculum_highlights: ["Advanced Smart Polymers", "Polymer Nanocomposites Research", "Biomedical Polymeric Systems"],
    website_url: "https://www.ictmumbai.edu.in",
    is_indian: true
  },
  {
    slug: "cipet-bhubaneswar-btech-plastics-technology",
    name: "B.Tech in Plastics Engineering & Technology",
    institution: "CIPET Bhubaneswar",
    location: "Bhubaneswar, Odisha",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹78,000",
    ranking: "Leading East-Zone Technical Hub",
    admission_process: "OJEE State Counseling / JEE Main ranking",
    eligibility: "10+2 with PCM subjects (min 45% aggregate)",
    curriculum_highlights: ["Mould Manufacturing & Machining", "Plastics Materials Selector", "CAD/CAM Laboratory"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "cipet-bhubaneswar-mtech-plastics-technology",
    name: "M.Tech in Plastics Technology",
    institution: "CIPET Bhubaneswar",
    location: "Bhubaneswar, Odisha",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹98,000",
    ranking: "East India PG Specialization Center",
    admission_process: "GATE / OJEE Graduate counseling",
    eligibility: "B.Tech in Mechanical, Production, Chemical, or Polymer",
    curriculum_highlights: ["Finite Element Analysis in Plastics", "Die and Mould Design Parameters", "Failure Analysis of Plastics"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "cipet-ahmedabad-btech-plastics-technology",
    name: "B.Tech in Plastics Technology",
    institution: "CIPET Ahmedabad",
    location: "Ahmedabad, Gujarat",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹82,000",
    ranking: "Key Processing Training Institute in Western Zone",
    admission_process: "ACP counseling (Gujarat State Board/JEE)",
    eligibility: "10+2 PCM with min 50% board aggregate",
    curriculum_highlights: ["Injection Moulding Technology", "Extrusion and Blow Moulding", "Plastics Evaluation & Testing"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "ld-engineering-college-btech-plastic-technology",
    name: "B.Tech in Plastic Technology",
    institution: "L.D. College of Engineering",
    location: "Ahmedabad, Gujarat",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹1,500",
    ranking: "Oldest Government Tech Institute in Gujarat",
    admission_process: "ACPC Counseling based on Board + GUJCET marks",
    eligibility: "10+2 Science with PCM (45% for general, 40% reserved)",
    curriculum_highlights: ["Introduction to Polymer Science", "Machinery Design & Hydraulics", "Polymer Chemistry Laboratory"],
    website_url: "https://ldce.ac.in",
    is_indian: true
  },
  {
    slug: "ld-engineering-college-mtech-plastic-technology",
    name: "M.Tech in Plastic Technology",
    institution: "L.D. College of Engineering",
    location: "Ahmedabad, Gujarat",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹25,000",
    ranking: "Accredited Government Research Facility",
    admission_process: "GATE score-based allocation / ACPC Gujarat PGCET",
    eligibility: "B.Tech in Plastic / Polymer Technology with min 50% marks",
    curriculum_highlights: ["Processing Technology Optimization", "Polymeric Blends and Composites", "Bio-degradable Polymers Research"],
    website_url: "https://ldce.ac.in",
    is_indian: true
  },
  {
    slug: "anna-university-btech-rubber-plastic-tech",
    name: "B.Tech in Rubber & Plastics Technology",
    institution: "Anna University (MIT Campus)",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹65,000",
    ranking: "NIRF Rank 13 Engineering University",
    admission_process: "TNEA Tamil Nadu State Counseling",
    eligibility: "10+2 with Physics, Chemistry & Math (50% PCM average)",
    curriculum_highlights: ["Elastomer Science & Chemistry", "Tyre Design & Manufacturing", "Plastics Engineering Principles"],
    website_url: "https://www.annauniv.edu",
    is_indian: true
  },
  {
    slug: "anna-university-mtech-rubber-technology",
    name: "M.Tech in Rubber Technology",
    institution: "Anna University (MIT Campus)",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹80,000",
    ranking: "Premier Rubber Technology Center in India",
    admission_process: "GATE / TANCET PG Counseling",
    eligibility: "B.E./B.Tech in Rubber, Plastics, Chemical, Mechanical or Polymer",
    curriculum_highlights: ["Advanced Tyre Technology", "Rubber Compounding & Formulations", "Elastomer Blend Science"],
    website_url: "https://www.annauniv.edu",
    is_indian: true
  },
  // Tier 2: State Universities (20 items)
  {
    slug: "vjti-mumbai-btech-polymer-science",
    name: "B.Tech in Polymer Technology",
    institution: "VJTI Mumbai",
    location: "Mumbai, Maharashtra",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹85,000",
    ranking: "Top-Tier State Autonomous Institute",
    admission_process: "MHT-CET State Counseling selection",
    eligibility: "10+2 PCM with min 55% marks",
    curriculum_highlights: ["Polymer Testing Standards", "Fibre Reinforced Composites", "Rheological Analytics"],
    website_url: "https://vjti.ac.in",
    is_indian: true
  },
  {
    slug: "mgu-kottayam-msc-polymer-chemistry",
    name: "M.Sc in Polymer Chemistry",
    institution: "Mahatma Gandhi University",
    location: "Kottayam, Kerala",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹22,000",
    ranking: "Revered Polymer Chemistry Center",
    admission_process: "MGU CAT Entrance Exam",
    eligibility: "B.Sc Chemistry (main) with Physics/Math subsidiary (55% min)",
    curriculum_highlights: ["Synthetic Organic Chemistry", "Kinetics of Polymerization", "Thermodynamics of Polymers"],
    website_url: "https://www.mgu.ac.in",
    is_indian: true
  },
  {
    slug: "cusat-kochi-btech-polymer-rubber-tech",
    name: "B.Tech in Polymer Science & Rubber Technology",
    institution: "CUSAT Kochi",
    location: "Kochi, Kerala",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹65,000",
    ranking: "NIRF Rank 37 University",
    admission_process: "CUSAT CAT Entrance Exam",
    eligibility: "10+2 with 50% marks in Math & 50% in PCM average",
    curriculum_highlights: ["Latex Technology", "Rubber Vulcanization Principles", "Tyre Manufacture & Testing"],
    website_url: "https://www.cusat.ac.in",
    is_indian: true
  },
  {
    slug: "bcas-delhi-bsc-polymer-science",
    name: "B.Sc (Hons) in Polymer Science",
    institution: "Bhaskaracharya College of Applied Sciences (DU)",
    location: "Dwarka, New Delhi",
    country: "India",
    degree_type: "B.Sc",
    duration: "3 Years",
    fees_annual: "₹28,000",
    ranking: "Premier Applied Science Undergrad Hub under Delhi University",
    admission_process: "CUET UG Entrance Test allocation",
    eligibility: "10+2 Science stream with PCM (min board eligibility)",
    curriculum_highlights: ["Polymer Synthesis Methods", "Packaging Science", "Recycling Tech", "Polymer Characterization"],
    website_url: "https://bcas.du.ac.in",
    is_indian: true
  },
  {
    slug: "gujarat-university-bsc-polymer-chemistry",
    name: "B.Sc in Polymer Chemistry",
    institution: "Gujarat University",
    location: "Ahmedabad, Gujarat",
    country: "India",
    degree_type: "B.Sc",
    duration: "3 Years",
    fees_annual: "₹18,000",
    ranking: "Established State University",
    admission_process: "Merit-based admission from 12th Board marks",
    eligibility: "10+2 Science with Chemistry",
    curriculum_highlights: ["Inorganic Polymers", "Spectroscopy of Polymers", "Compounding and Moulding Labs"],
    website_url: "https://www.gujaratuniversity.ac.in",
    is_indian: true
  },
  {
    slug: "lucknow-university-msc-polymer-science",
    name: "M.Sc in Polymer Science",
    institution: "Lucknow University",
    location: "Lucknow, Uttar Pradesh",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹35,000",
    ranking: "A++ NAAC Accredited State University",
    admission_process: "Lucknow University PG Entrance Test (LUPGET)",
    eligibility: "B.Sc Chemistry (hons) / General B.Sc with Chemistry (50% min)",
    curriculum_highlights: ["Physical Chemistry of Polymers", "High Performance Plastics", "Plastic Additive Formulations"],
    website_url: "https://lkouniv.ac.in",
    is_indian: true
  },
  {
    slug: "calicut-university-msc-polymer-tech",
    name: "M.Sc in Polymer Technology",
    institution: "Calicut University",
    location: "Malappuram, Kerala",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹24,000",
    ranking: "State University Specialization Center",
    admission_process: "University Entrance Examination",
    eligibility: "B.Sc Chemistry / Applied Chemistry with Physics/Maths background",
    curriculum_highlights: ["Elastomer Science", "Biopolymeric Engineering", "Environmental Recycling Systems"],
    website_url: "https://uoc.ac.in",
    is_indian: true
  },
  {
    slug: "amravati-university-mtech-polymer-science",
    name: "M.Tech in Polymer & Plastic Technology",
    institution: "SGBAU Amravati",
    location: "Amravati, Maharashtra",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹48,000",
    ranking: "State University Technology Department",
    admission_process: "GATE exam in Chemical or Engineering Sciences",
    eligibility: "B.Tech in Chemical/Polymer/Petrochemical Tech",
    curriculum_highlights: ["Process Optimization Tools", "Industrial Extrusion Layouts", "Recyclability Audits"],
    website_url: "https://www.sgbau.ac.in",
    is_indian: true
  },
  {
    slug: "jalgaon-university-btech-polymer-tech",
    name: "B.Tech in Polymer & Plastic Technology",
    institution: "KBCNMU Jalgaon",
    location: "Jalgaon, Maharashtra",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹52,000",
    ranking: "Renowned State Technology Center",
    admission_process: "MHT-CET / JEE Main Counseling allocation",
    eligibility: "10+2 with PCM (min 45% board marks)",
    curriculum_highlights: ["Resin Synthesis", "Paints and Surface Coatings", "Mould Manufacturing Laboratory"],
    website_url: "https://nmu.ac.in",
    is_indian: true
  },
  {
    slug: "madras-university-msc-polymer-science",
    name: "M.Sc in Polymer Science",
    institution: "University of Madras",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹30,000",
    ranking: "NAAC A++ Grade Historical Center",
    admission_process: "Madras University Entrance Exam",
    eligibility: "B.Sc Chemistry/Industrial Chemistry with min 55% marks",
    curriculum_highlights: ["Bio-degradable Polymeric Networks", "Liquid Crystalline Systems", "Polymer Degradation Pathways"],
    website_url: "https://unom.ac.in",
    is_indian: true
  },
  {
    slug: "patna-university-msc-polymer-science",
    name: "M.Sc in Polymer Science",
    institution: "Patna University",
    location: "Patna, Bihar",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹18,000",
    ranking: "Legacy North-Eastern University",
    admission_process: "Patna University PG Admission Test",
    eligibility: "B.Sc Chemistry (hons) / General B.Sc (Chemistry main)",
    curriculum_highlights: ["Polymer Synthesis", "Industrial Coatings", "Plastic Testing & Characterization"],
    website_url: "https://patnauniversity.ac.in",
    is_indian: true
  },
  {
    slug: "jmi-delhi-msc-polymer-chemistry",
    name: "M.Sc in Chemistry (Polymer Specialization)",
    institution: "Jamia Millia Islamia",
    location: "New Delhi",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹26,000",
    ranking: "NIRF Rank 3 National University",
    admission_process: "JMI Admission Entrance Exam",
    eligibility: "B.Sc Chemistry/Applied Chemistry with min 50% marks",
    curriculum_highlights: ["Physical Chemistry of Polymers", "High Temperature Plastics", "Structure Diagnostics"],
    website_url: "https://www.jmi.ac.in",
    is_indian: true
  },
  {
    slug: "andhra-university-mtech-polymer-tech",
    name: "M.Tech in Polymer Technology",
    institution: "Andhra University",
    location: "Visakhapatnam, Andhra Pradesh",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹65,000",
    ranking: "A-Grade Government University Department",
    admission_process: "GATE / AP PGECET score allocation",
    eligibility: "B.Tech in Chemical / Polymer / Materials / Metallurgy",
    curriculum_highlights: ["Specialty High Polymers", "Corrosion Prevention by Polymers", "Composite Technology"],
    website_url: "https://andhrauniversity.edu.in",
    is_indian: true
  },
  {
    slug: "vellore-university-msc-chemistry-polymers",
    name: "M.Sc in Chemistry (Polymer Chemistry)",
    institution: "VIT University",
    location: "Vellore, Tamil Nadu",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹95,000",
    ranking: "Ranked 11 in NIRF Engineering",
    admission_process: "VIT Graduate Entrance Examination (VITGEE)",
    eligibility: "B.Sc Chemistry / Applied Chemistry with min 60% aggregate",
    curriculum_highlights: ["Organometallic Polymer Chemistry", "Nano-Composite Formulations", "Industrial Polymers"],
    website_url: "https://vit.ac.in",
    is_indian: true
  },
  {
    slug: "tezpur-university-msc-polymer-science",
    name: "M.Sc in Polymer Science",
    institution: "Tezpur University",
    location: "Tezpur, Assam",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹38,000",
    ranking: "NIRF Rank 59 Central University",
    admission_process: "CUET PG Entrance exam",
    eligibility: "B.Sc Chemistry with Mathematics background",
    curriculum_highlights: ["Resin Prep & Curing", "Elastomer Formulations", "Testing Standards"],
    website_url: "https://tezu.ernet.in",
    is_indian: true
  },
  {
    slug: "sardar-patel-university-msc-polymer-chemistry",
    name: "M.Sc in Polymer Chemistry",
    institution: "Sardar Patel University",
    location: "Vallabh Vidyanagar, Gujarat",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹26,000",
    ranking: "Esteemed State Research Center",
    admission_process: "SPU PG Entrance Test merit",
    eligibility: "B.Sc Chemistry with 50% board aggregate",
    curriculum_highlights: ["Conductive Polymeric Materials", "Specialty Pigments", "Mould Injection Labs"],
    website_url: "https://www.spuvvn.edu",
    is_indian: true
  },
  {
    slug: "cochin-university-mtech-polymer-science",
    name: "M.Tech in Polymer Technology",
    institution: "CUSAT Kochi",
    location: "Kochi, Kerala",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹85,000",
    ranking: "State Specialized Research Faculty",
    admission_process: "GATE Chemical / Materials Science selection",
    eligibility: "B.Tech in Polymer Technology / MSc Chemistry with 60%",
    curriculum_highlights: ["Rheological Measurement", "Functional Polymeric Networks", "Tyre Manufacture"],
    website_url: "https://cusat.ac.in",
    is_indian: true
  },
  {
    slug: "jiwaji-university-msc-polymer-chemistry",
    name: "M.Sc in Polymer Chemistry",
    institution: "Jiwaji University",
    location: "Gwalior, Madhya Pradesh",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹32,000",
    ranking: "A-Grade State University",
    admission_process: "Jiwaji PG Entrance Test",
    eligibility: "B.Sc with Chemistry / Applied Chemistry with 50% marks",
    curriculum_highlights: ["Polymerization Engineering", "Physical Properties Diagnostics", "Paints Formulation"],
    website_url: "https://jiwaji.edu",
    is_indian: true
  },
  {
    slug: "aligarh-university-mtech-polymer-coatings",
    name: "M.Tech in Polymer Science & Technology",
    institution: "Aligarh Muslim University",
    location: "Aligarh, Uttar Pradesh",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹45,000",
    ranking: "Ranked 11 in Indian Universities",
    admission_process: "AMU PG Entrance test / GATE ranking",
    eligibility: "B.Tech in Chemical, Polymer, Materials, or Petroleum Engineering",
    curriculum_highlights: ["Coatings & Corrosion Resistance", "Macromolecular Chemistry", "Polymer Extrusion Systems"],
    website_url: "https://amu.ac.in",
    is_indian: true
  },
  {
    slug: "south-gujarat-university-msc-polymer-science",
    name: "M.Sc in Polymer Science",
    institution: "VNSGU Surat",
    location: "Surat, Gujarat",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹32,000",
    ranking: "Surat Regional Technology University",
    admission_process: "VNSGU Entrance Test",
    eligibility: "B.Sc in Chemistry / Applied Chemistry",
    curriculum_highlights: ["Polymer Synthesis Methods", "Testing and Analytical Diagnostics", "Processing Optimization"],
    website_url: "https://vnsgu.ac.in",
    is_indian: true
  },
  // Tier 3: NITs & IITs (10 items)
  {
    slug: "iit-delhi-mtech-polymer-science",
    name: "M.Tech in Polymer Science & Technology",
    institution: "IIT Delhi",
    location: "Hauz Khas, New Delhi",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,80,000",
    ranking: "NIRF Rank 2 Engineering Institution",
    admission_process: "GATE Exam + COAP Counseling allocation + Interview",
    eligibility: "B.Tech in Chemical/Polymer/Materials / MSc Chemistry (min 60% / 6.0 CGPA)",
    curriculum_highlights: ["Polymer Engineering Chemistry", "Rheology of Polymers", "High Performance Polymeric Materials", "Mould Design & Simulation"],
    website_url: "https://home.iitd.ac.in",
    is_indian: true
  },
  {
    slug: "iit-delhi-phd-polymer-science",
    name: "Ph.D in Polymer Science & Engineering",
    institution: "IIT Delhi",
    location: "Hauz Khas, New Delhi",
    country: "India",
    degree_type: "Ph.D",
    duration: "3-5 Years",
    fees_annual: "₹1,10,000",
    ranking: "Premier Research Department in India",
    admission_process: "GATE/CSIR net followed by Departmental Research Interview",
    eligibility: "M.Tech in Polymer/Materials/Chemical/Mechanical Engineering",
    curriculum_highlights: ["Smart Biomaterials", "Nano-filler Elastomers", "Aerosol Polymeric Formulations"],
    website_url: "https://home.iitd.ac.in",
    is_indian: true
  },
  {
    slug: "iit-kharagpur-mtech-rubber-technology",
    name: "M.Tech in Rubber Technology",
    institution: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,75,000",
    ranking: "NIRF Rank 6 Engineering Institute",
    admission_process: "GATE Exam + COAP allocation",
    eligibility: "B.E./B.Tech in Chemical/Mechanical/Polymer / MSc Chemistry",
    curriculum_highlights: ["Elastomer Science & Formulations", "Tyre Design & Manufacturing", "Rubber Blends & Alloys"],
    website_url: "https://www.iitkgp.ac.in",
    is_indian: true
  },
  {
    slug: "iit-kharagpur-phd-rubber-science",
    name: "Ph.D in Rubber & Polymer Technology",
    institution: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    country: "India",
    degree_type: "Ph.D",
    duration: "3-5 Years",
    fees_annual: "₹95,000",
    ranking: "Globally Recognized Research Center",
    admission_process: "IIT Kharagpur Direct Interview / GATE/CSIR NET JRF",
    eligibility: "M.Tech in Rubber / Polymer / Chemical with min 6.5 CGPA",
    curriculum_highlights: ["Advanced Tyre Rheology", "Functional Elastomers", "Polymer Recycling Frontiers"],
    website_url: "https://www.iitkgp.ac.in",
    is_indian: true
  },
  {
    slug: "iit-madras-mtech-materials-engineering",
    name: "M.Tech in Materials Engineering (Polymer focus)",
    institution: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,90,000",
    ranking: "NIRF Rank 1 Engineering Institution",
    admission_process: "GATE score + COAP Counseling allocation",
    eligibility: "B.Tech in Metallurgical/Materials/Chemical/Mechanical / MSc Physics",
    curriculum_highlights: ["Polymeric Engineering Materials", "Mechanical Behaviour of Polymers", "High-Modulus Composites"],
    website_url: "https://www.iitm.ac.in",
    is_indian: true
  },
  {
    slug: "nit-rourkela-mtech-chemical-polymer",
    name: "M.Tech in Chemical Engineering (Polymer Tech)",
    institution: "NIT Rourkela",
    location: "Rourkela, Odisha",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,20,000",
    ranking: "NIRF Rank 19 Engineering Institute",
    admission_process: "GATE score + CCMT Counseling allocation",
    eligibility: "B.Tech in Chemical/Polymer/Petrochemical with min 6.5 CGPA",
    curriculum_highlights: ["Advanced Chemical Processing", "Polymeric Separation Systems", "Nanostructured Composites"],
    website_url: "https://www.nitrkl.ac.in",
    is_indian: true
  },
  {
    slug: "nit-calicut-mtech-polymer-science",
    name: "M.Tech in Polymer Science & Technology",
    institution: "NIT Calicut",
    location: "Kozhikode, Kerala",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,15,000",
    ranking: "NIRF Rank 23 Engineering Institute",
    admission_process: "GATE score + CCMT allocation",
    eligibility: "B.Tech in Chemical/Polymer/Materials Science (min 60% marks)",
    curriculum_highlights: ["Macromolecular Chemistry", "Polymer Testing & Diagnostics", "Composite Engineering Design"],
    website_url: "https://nitc.ac.in",
    is_indian: true
  },
  {
    slug: "iit-roorkee-mtech-polymer-science",
    name: "M.Tech in Polymer Science & Engineering",
    institution: "IIT Roorkee",
    location: "Roorkee, Uttarakhand",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,85,000",
    ranking: "NIRF Rank 8 Engineering Institution",
    admission_process: "GATE score + COAP Counseling",
    eligibility: "B.Tech in Chemical / Polymer / Materials Engineering",
    curriculum_highlights: ["Polymeric Engineering Thermodynamics", "Mould Flow Rheology", "Functional Materials"],
    website_url: "https://iitr.ac.in",
    is_indian: true
  },
  {
    slug: "iit-guwahati-mtech-materials-engineering",
    name: "M.Tech in Materials Engineering (Polymer Research)",
    institution: "IIT Guwahati",
    location: "Guwahati, Assam",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,65,000",
    ranking: "NIRF Rank 9 Engineering Institution",
    admission_process: "GATE score + COAP Counseling allocation",
    eligibility: "B.Tech in Materials/Chemical/Mechanical/Polymer",
    curriculum_highlights: ["Polymer Degradation & Stability", "Rheology Lab", "Advanced Filler Composites"],
    website_url: "https://iitg.ac.in",
    is_indian: true
  },
  {
    slug: "iit-kanpur-mtech-materials-science-polymer",
    name: "M.Tech in Materials Science (Polymer Science)",
    institution: "IIT Kanpur",
    location: "Kanpur, Uttar Pradesh",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,80,000",
    ranking: "NIRF Rank 4 Engineering Institution",
    admission_process: "GATE score + COAP selection",
    eligibility: "B.Tech in Materials/Chemical/Polymer Engineering",
    curriculum_highlights: ["Thermodynamics of Polymers", "High Strength Polymers", "Mould Flow Diagnostics"],
    website_url: "https://iitk.ac.in",
    is_indian: true
  },
  // Tier 4: Private & Deemed (10 items)
  {
    slug: "mitwpu-pune-btech-polymer-engineering",
    name: "B.Tech in Polymer Engineering",
    institution: "MIT World Peace University",
    location: "Pune, Maharashtra",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹2,40,000",
    ranking: "First Private Polymer Engineering Department in India",
    admission_process: "MHT-CET / JEE Main / MIT-WPU UGPET Entrance Test",
    eligibility: "10+2 Science with PCM (min 50% marks in PCM aggregate)",
    curriculum_highlights: ["Polymer Processing & Automation", "Mould and Die Design (SOLIDWORKS)", "Testing & Characterization", "Rubber Science & Compounding"],
    website_url: "https://mitwpu.edu.in",
    is_indian: true
  },
  {
    slug: "mitwpu-pune-msc-industrial-polymer-chemistry",
    name: "M.Sc in Industrial Polymer Chemistry",
    institution: "MIT World Peace University",
    location: "Pune, Maharashtra",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹1,10,000",
    ranking: "Excellent Industry Placement Network",
    admission_process: "MIT-WPU PGPET exam followed by Interview",
    eligibility: "B.Sc Chemistry / Applied Chemistry with min 50% aggregate",
    curriculum_highlights: ["Industrial Polymerization Kinetics", "Paints, Adhesives & Coatings", "Additive Curing Science"],
    website_url: "https://mitwpu.edu.in",
    is_indian: true
  },
  {
    slug: "bits-pilani-msc-polymer-science",
    name: "M.Sc in Chemistry (Polymer Specialization)",
    institution: "BITS Pilani",
    location: "Pilani, Rajasthan",
    country: "India",
    degree_type: "M.Sc",
    duration: "2 Years",
    fees_annual: "₹4,20,000",
    ranking: "Premier Private Deemed University",
    admission_process: "BITS HD Entrance Test / GATE score allocation",
    eligibility: "B.Sc Chemistry with minimum 60% aggregate score",
    curriculum_highlights: ["Polymer Material Synthesis", "Characterization of Polymers", "High Polymers in Packaging"],
    website_url: "https://www.bits-pilani.ac.in",
    is_indian: true
  },
  {
    slug: "srm-university-btech-polymer-science",
    name: "B.Tech in Polymer Technology",
    institution: "SRM IST Chennai",
    location: "Kattankulathur, Chennai",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹2,50,000",
    ranking: "A++ Grade NAAC Private Deemed University",
    admission_process: "SRMJEEE score counseling allocation",
    eligibility: "10+2 with PCM (min 50% board aggregate)",
    curriculum_highlights: ["Raw Material Polymer Formulation", "Plastics Engineering Machinery", "Composites Manufacturing"],
    website_url: "https://www.srmist.edu.in",
    is_indian: true
  },
  {
    slug: "sharda-university-btech-polymer-science",
    name: "B.Tech in Polymer Science",
    institution: "Sharda University",
    location: "Greater Noida, Uttar Pradesh",
    country: "India",
    degree_type: "B.Tech",
    duration: "4 Years",
    fees_annual: "₹1,85,000",
    ranking: "Global Private University Center",
    admission_process: "SUAT Entrance Test / JEE Main ranking",
    eligibility: "10+2 with PCM (min 50% board aggregate)",
    curriculum_highlights: ["Polymerization Processes", "Testing Laboratory", "Additives Compounding"],
    website_url: "https://www.sharda.ac.in",
    is_indian: true
  },
  {
    slug: "jss-university-mtech-polymer-tech",
    name: "M.Tech in Polymer Science & Technology",
    institution: "JSS Science & Technology University",
    location: "Mysuru, Karnataka",
    country: "India",
    degree_type: "M.Tech",
    duration: "2 Years",
    fees_annual: "₹1,25,000",
    ranking: "Well-Equipped Southern Research Hub",
    admission_process: "PGCET Karnataka State Counseling / GATE allocation",
    eligibility: "B.E./B.Tech in Polymer / Plastics / Chemical Engineering",
    curriculum_highlights: ["Functional Polymers", "Advanced Extrusion Techniques", "Product Design Engineering"],
    website_url: "https://jssstuniv.in",
    is_indian: true
  },
  {
    slug: "diploma-plastics-tech-chennai",
    name: "Diploma in Plastics Technology (DPT)",
    institution: "CIPET Chennai",
    location: "Chennai, Tamil Nadu",
    country: "India",
    degree_type: "Diploma",
    duration: "3 Years",
    fees_annual: "₹45,000",
    ranking: "Industry-Ready Technical Training",
    admission_process: "CIPET JEE Entrance Examination allocation",
    eligibility: "Class 10th pass with Science & Math subjects",
    curriculum_highlights: ["Machine Operation Practice", "Mould Fitting & Fabrication", "Safety Guidelines"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "diploma-plastics-mould-tech-ahmedabad",
    name: "Diploma in Plastics Mould Technology (DPMT)",
    institution: "CIPET Ahmedabad",
    location: "Ahmedabad, Gujarat",
    country: "India",
    degree_type: "Diploma",
    duration: "3 Years",
    fees_annual: "₹45,000",
    ranking: "Hands-on Workshop Specialization",
    admission_process: "CIPET JEE Examination score merit",
    eligibility: "Class 10th pass with Science and Maths",
    curriculum_highlights: ["Mould Manufacturing & Hand Fitting", "Plastics Component Testing", "CAD Lab Practice"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "diploma-plastics-tech-lucknow",
    name: "Diploma in Plastics Technology (DPT)",
    institution: "CIPET Lucknow",
    location: "Lucknow, Uttar Pradesh",
    country: "India",
    degree_type: "Diploma",
    duration: "3 Years",
    fees_annual: "₹45,000",
    ranking: "Excellent Placement in Northern Zone",
    admission_process: "CIPET JEE Entrance Test",
    eligibility: "Class 10th pass",
    curriculum_highlights: ["Plastics Materials Analysis", "Mould Assembly and Repair", "Extrusion Workshop Practice"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  },
  {
    slug: "diploma-plastics-mould-tech-lucknow",
    name: "Diploma in Plastics Mould Technology (DPMT)",
    institution: "CIPET Lucknow",
    location: "Lucknow, Uttar Pradesh",
    country: "India",
    degree_type: "Diploma",
    duration: "3 Years",
    fees_annual: "₹45,000",
    ranking: "Northern Precision Machining Center",
    admission_process: "CIPET JEE Selection",
    eligibility: "Class 10th pass",
    curriculum_highlights: ["Precision CNC Machining", "Mould Maintenance Guidelines", "Tool and Die Fabrication Practice"],
    website_url: "https://www.cipet.gov.in",
    is_indian: true
  }
];

// Define 32 Global Programs
const GLOBAL_PROGRAMS = [
  {
    slug: "umass-amherst-ms-polymer-science",
    name: "M.S. in Polymer Science & Engineering",
    institution: "University of Massachusetts Amherst",
    location: "Amherst, Massachusetts",
    country: "USA",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$35,000",
    ranking: "Ranked #1 Polymer Program in the United States",
    admission_process: "GRE general (recommended) + TOEFL/IELTS + Statement of Purpose + 3 Recommendation Letters",
    eligibility: "B.S. in Chemistry, Physics, Chemical Engineering or Materials Science (min 3.0 GPA)",
    curriculum_highlights: ["Polymer Synthesis", "Polymer Physics", "Polymer Characterization & Testing", "Macromolecular Structures"],
    website_url: "https://www.pse.umass.edu",
    is_indian: false
  },
  {
    slug: "umass-amherst-phd-polymer-science",
    name: "Ph.D. in Polymer Science & Engineering",
    institution: "University of Massachusetts Amherst",
    location: "Amherst, Massachusetts",
    country: "USA",
    degree_type: "Ph.D",
    duration: "4-5 Years",
    fees_annual: "$35,000 (Fully funded by research assistantships)",
    ranking: "Top Global Center for Macromolecular Research",
    admission_process: "Online Graduate Admission Application + Research Statement + 3 LORs",
    eligibility: "B.S. in Science/Engineering fields (strong physics and chemistry foundation)",
    curriculum_highlights: ["Advanced Polymer Thermodynamics", "Biomimetic Polymeric Arrays", "Semiconductor Polymers"],
    website_url: "https://www.pse.umass.edu",
    is_indian: false
  },
  {
    slug: "university-of-akron-ms-polymer-science",
    name: "M.S. in Polymer Engineering",
    institution: "University of Akron",
    location: "Akron, Ohio",
    country: "USA",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$28,500",
    ranking: "World-famous Polymer Science and Processing Hub",
    admission_process: "GRE + TOEFL/IELTS + Academic Transcripts + SOP",
    eligibility: "Undergraduate degree in Science or Engineering (min 3.0 GPA)",
    curriculum_highlights: ["Polymer Chemistry & Physics", "Processing Mechanics", "Rheology Laboratory", "Polymer Compounding Techniques"],
    website_url: "https://www.uakron.edu/polymer",
    is_indian: false
  },
  {
    slug: "university-of-akron-phd-polymer-engineering",
    name: "Ph.D. in Polymer Engineering",
    institution: "University of Akron",
    location: "Akron, Ohio",
    country: "USA",
    degree_type: "Ph.D",
    duration: "4 Years",
    fees_annual: "$28,500 (Covered by TA/RA Stipend)",
    ranking: "Globally Renowned Engineering Research Center",
    admission_process: "Direct research application + Faculty alignment",
    eligibility: "B.S./M.S. in Engineering or Polymer Science",
    curriculum_highlights: ["Rheology of Polymer Solutions", "Processing Optimization Algorithms", "Nano-Composite Membranes"],
    website_url: "https://www.uakron.edu/polymer",
    is_indian: false
  },
  {
    slug: "case-western-ms-macromolecular-science",
    name: "M.S. in Macromolecular Science & Engineering",
    institution: "Case Western Reserve University",
    location: "Cleveland, Ohio",
    country: "USA",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$42,000",
    ranking: "Historical Macromolecular Science Department",
    admission_process: "Academic Transcripts + SOP + CV + 3 LORs",
    eligibility: "Undergraduate degree in science/engineering",
    curriculum_highlights: ["Polymer Synthesis Methods", "Molecular Structure Properties", "Advanced Composites", "Rheological Analysis"],
    website_url: "https://macromolecular.case.edu",
    is_indian: false
  },
  {
    slug: "case-western-phd-macromolecular-science",
    name: "Ph.D. in Macromolecular Science & Engineering",
    institution: "Case Western Reserve University",
    location: "Cleveland, Ohio",
    country: "USA",
    degree_type: "Ph.D",
    duration: "4 Years",
    fees_annual: "$42,000 (Fully funded by research fellowships)",
    ranking: "Top-Tier Polymer Science Research Hub",
    admission_process: "Graduate school application + Interview",
    eligibility: "M.S. or B.S. in chemistry/materials/polymer engineering",
    curriculum_highlights: ["Advanced Polymer Blends", "Smart Polymeric Biomaterials", "Nano-composite Systems"],
    website_url: "https://macromolecular.case.edu",
    is_indian: false
  },
  {
    slug: "mit-ms-chemical-engineering-polymers",
    name: "M.S. in Chemical Engineering Practice (Polymers)",
    institution: "MIT",
    location: "Cambridge, Massachusetts",
    country: "USA",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$56,000",
    ranking: "NIRF Equivalent: #1 Engineering School globally",
    admission_process: "GRE general + IELTS/TOEFL + MIT graduate portfolio application",
    eligibility: "B.S. in Chemical/Materials Engineering with outstanding academics",
    curriculum_highlights: ["Macromolecular Chemistry", "Polymeric Fluids Rheology", "Applied Nanotechnology"],
    website_url: "https://cheme.mit.edu",
    is_indian: false
  },
  {
    slug: "mit-phd-polymer-materials-science",
    name: "Ph.D. in Materials Science (Polymer Research)",
    institution: "MIT",
    location: "Cambridge, Massachusetts",
    country: "USA",
    degree_type: "Ph.D",
    duration: "4-5 Years",
    fees_annual: "$56,000 (Fully funded by RA/Fellowships)",
    ranking: "Premier global research faculty",
    admission_process: "MIT Graduate Admissions + Research Statement + SOP",
    eligibility: "B.S./M.S. in engineering or physics with research background",
    curriculum_highlights: ["Macromolecular Assemblies", "Biomedical Polymeric Implants", "Polymers for Renewable Energy"],
    website_url: "https://cheme.mit.edu",
    is_indian: false
  },
  {
    slug: "university-of-freiburg-ms-molecular-materials",
    name: "M.Sc. in Molecular Medicine & Polymer Materials",
    institution: "University of Freiburg",
    location: "Freiburg, Baden-Württemberg",
    country: "Germany",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€1,500 (Admin fees)",
    ranking: "Highly Ranked German Excellence University",
    admission_process: "Freiburg Uni Entrance portal evaluation",
    eligibility: "B.Sc. in Chemistry / Polymer Chemistry or closely related fields",
    curriculum_highlights: ["Supramolecular Chemistry", "Advanced Synthesis & Catalysis", "Polymer Characterization Labs"],
    website_url: "https://www.cup.uni-freiburg.de",
    is_indian: false
  },
  {
    slug: "tu-darmstadt-ms-polymer-technology",
    name: "M.Sc. in Polymer Technology",
    institution: "TU Darmstadt",
    location: "Darmstadt, Hesse",
    country: "Germany",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€800 (Semester administrative contribution)",
    ranking: "Renowned Technical University in Germany (TU9 member)",
    admission_process: "German language proficiency test (DSH/TestDaF) + University evaluation",
    eligibility: "B.Sc. in Materials Science / Mechanical / Chemistry",
    curriculum_highlights: ["Polymer Processing Machinery", "Design of Plastics Parts", "Additive Manufacturing of Polymers"],
    website_url: "https://www.tu-darmstadt.de",
    is_indian: false
  },
  {
    slug: "university-of-manchester-msc-polymer-science",
    name: "M.Sc. in Polymer Science & Technology",
    institution: "University of Manchester",
    location: "Manchester, England",
    country: "UK",
    degree_type: "MS",
    duration: "1 Year",
    fees_annual: "£26,000",
    ranking: "Top 30 Global University",
    admission_process: "Online portal submission + Academic references",
    eligibility: "UK 2:1 Honours degree (or international equivalent) in chemistry/engineering",
    curriculum_highlights: ["Polymerization Techniques", "Fibre Reinforced Composites", "Rheological Characterization"],
    website_url: "https://www.manchester.ac.uk",
    is_indian: false
  },
  {
    slug: "imperial-college-london-msc-chemical-polymers",
    name: "M.Sc. in Chemical Engineering (Polymer Materials)",
    institution: "Imperial College London",
    location: "London, England",
    country: "UK",
    degree_type: "MS",
    duration: "1 Year",
    fees_annual: "£32,000",
    ranking: "QS World Rank #6 University",
    admission_process: "Imperial PG application + SOIP + References",
    eligibility: "First Class honours degree in engineering / chemical sciences",
    curriculum_highlights: ["Macromolecular Reaction Engineering", "Polymer Processing Thermodynamics", "Nano-Composite Membranes"],
    website_url: "https://www.imperial.ac.uk",
    is_indian: false
  },
  {
    slug: "tokyo-tech-ms-polymer-chemistry",
    name: "M.S. in Polymer Chemistry",
    institution: "Tokyo Institute of Technology",
    location: "Meguro, Tokyo",
    country: "Japan",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "¥635,400",
    ranking: "Top Technology Institute in Japan",
    admission_process: "Tokyo Tech International Graduate Program entrance exam",
    eligibility: "B.Sc in Chemistry/Engineering with strong academic records",
    curriculum_highlights: ["Polymer Synthesis Chemistry", "Physical Properties of Plastics", "Liquid Crystal polymers"],
    website_url: "https://www.titech.ac.jp",
    is_indian: false
  },
  {
    slug: "university-of-twente-ms-polymer-science",
    name: "M.Sc. in Materials Science (Polymer focus)",
    institution: "University of Twente",
    location: "Enschede, Overijssel",
    country: "Netherlands",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€16,500",
    ranking: "Top Dutch Technical University",
    admission_process: "Graduate application portal evaluation",
    eligibility: "B.Sc. in Chemical Engineering / Chemistry with min 3.0 GPA equivalent",
    curriculum_highlights: ["Membrane Science & Tech", "Polymer Processing Mechanics", "Rheology of Multi-phase systems"],
    website_url: "https://www.utwente.nl",
    is_indian: false
  },
  {
    slug: "university-of-strasbourg-ms-polymer-chemistry",
    name: "M.Sc. in Polymer Chemistry & Engineering",
    institution: "University of Strasbourg",
    location: "Strasbourg, Grand Est",
    country: "France",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€243 (State university registration)",
    ranking: "Historical Chemistry Department (Home of Nobel Laureates)",
    admission_process: "MonMaster France application evaluation",
    eligibility: "B.Sc. in Chemistry / Biochemistry with good academic standing",
    curriculum_highlights: ["Macromolecular Chemistry", "Polymer Surface Modification", "Bio-medical Polymers"],
    website_url: "https://www.unistra.fr",
    is_indian: false
  },
  {
    slug: "university-of-waterloo-ms-polymer-engineering",
    name: "M.Sc. in Chemical Engineering (Polymer focus)",
    institution: "University of Waterloo",
    location: "Waterloo, Ontario",
    country: "Canada",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$22,000",
    ranking: "Highly Ranked Canadian Cooperative Research Center",
    admission_process: "Waterloo Graduate portal + 3 Reference Letters",
    eligibility: "B.Tech/B.Sc. in Engineering with minimum 78% average",
    curriculum_highlights: ["Polymerization Reactors Design", "Mould Flow Simulation", "Extrusion Systems Research"],
    website_url: "https://uwaterloo.ca",
    is_indian: false
  },
  {
    slug: "university-of-sydney-ms-polymer-chemistry",
    name: "M.Sc. in Polymer Chemistry",
    institution: "University of Sydney",
    location: "Sydney, NSW",
    country: "Australia",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$44,000",
    ranking: "Group of Eight Premier Australian University",
    admission_process: "Sydney PG Entrance Portal submission",
    eligibility: "B.Sc. in chemistry or materials science with high credits",
    curriculum_highlights: ["Synthesis of Advanced Polymers", "Dynamic Rheology Analysis", "Biocompatible Coatings"],
    website_url: "https://www.sydney.edu.au",
    is_indian: false
  },
  {
    slug: "kth-royal-institute-ms-polymer-technology",
    name: "M.Sc. in Macromolecular Materials",
    institution: "KTH Royal Institute of Technology",
    location: "Stockholm, Uppland",
    country: "Sweden",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "SEK 155,000",
    ranking: "Leading Technical University in Scandinavia",
    admission_process: "University Admissions Sweden portal evaluation",
    eligibility: "B.Sc. in Chemistry / Chemical Engineering / Materials Science",
    curriculum_highlights: ["Polymer Chemistry & Physics", "Biopolymeric Materials", "Circular Plastics Economy"],
    website_url: "https://www.kth.se",
    is_indian: false
  },
  {
    slug: "ku-leuven-ms-materials-engineering",
    name: "M.Sc. in Materials Engineering (Polymer track)",
    institution: "KU Leuven",
    location: "Leuven, Flanders",
    country: "Belgium",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€6,600",
    ranking: "Most Innovative European University",
    admission_process: "KU Leuven online portal evaluation",
    eligibility: "B.Sc. in Engineering with strong materials science fundamentals",
    curriculum_highlights: ["Processing of Polymer Matrix Composites", "Mechanical Behaviour of Thermoplastics", "Dynamic Testing Labs"],
    website_url: "https://www.kuleuven.be",
    is_indian: false
  },
  {
    slug: "eth-zurich-ms-materials-science",
    name: "M.Sc. in Materials Science (Polymers)",
    institution: "ETH Zurich",
    location: "Zurich",
    country: "Switzerland",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "CHF 1,500",
    ranking: "Ranked Top 10 globally",
    admission_process: "ETH Zurich Graduate portal evaluation + Interview",
    eligibility: "B.Sc. in Chemistry, Physics, or Engineering (First class honors)",
    curriculum_highlights: ["Polymer Physics", "Advanced Composite Structures", "Additive Manufacturing of Resins"],
    website_url: "https://ethz.ch",
    is_indian: false
  },
  {
    slug: "nus-ms-polymer-science",
    name: "M.Sc. in Polymer Science & Engineering",
    institution: "National University of Singapore",
    location: "Singapore",
    country: "Singapore",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$38,000",
    ranking: "Ranked #1 in Asia",
    admission_process: "NUS Graduate portal submission",
    eligibility: "Undergraduate degree in Science or Engineering with high marks",
    curriculum_highlights: ["Biomedical Polymers", "Polymer Nanotechnology", "Smart Membranes Research"],
    website_url: "https://nus.edu.sg",
    is_indian: false
  },
  {
    slug: "seoul-national-ms-polymer-engineering",
    name: "M.S. in Polymer Engineering",
    institution: "Seoul National University",
    location: "Seoul",
    country: "South Korea",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "KRW 6,500,000",
    ranking: "Premier University in South Korea",
    admission_process: "SNU International Graduate Admissions portal",
    eligibility: "Bachelor's degree in chemistry / materials science",
    curriculum_highlights: ["Advanced Polymer Processing", "Rubber Mechanics", "Structure diagnostics"],
    website_url: "https://en.snu.ac.kr",
    is_indian: false
  },
  {
    slug: "kyoto-university-ms-polymer-chemistry",
    name: "M.S. in Polymer Chemistry",
    institution: "Kyoto University",
    location: "Kyoto",
    country: "Japan",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "¥635,400",
    ranking: "Highly Ranked Historical Japanese University",
    admission_process: "Kyoto AAO portal alignment + Entrance Examination",
    eligibility: "B.Sc. in Chemistry or Chemical Engineering",
    curriculum_highlights: ["Anionic Polymerization", "Living Radical Polymerization", "Polymer Rheology"],
    website_url: "https://www.kyoto-u.ac.jp",
    is_indian: false
  },
  {
    slug: "delft-university-ms-materials-science-polymers",
    name: "M.Sc. in Materials Science & Engineering (Polymers)",
    institution: "TU Delft",
    location: "Delft, South Holland",
    country: "Netherlands",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€19,500",
    ranking: "Leading Technical University in Europe",
    admission_process: "TU Delft Graduate Application portal + GRE",
    eligibility: "B.Sc. in Materials Science / Chemical Engineering (high GPA)",
    curriculum_highlights: ["Structure property relations", "Self-healing Polymers", "Composites Manufacturing"],
    website_url: "https://www.tudelft.nl",
    is_indian: false
  },
  {
    slug: "aalto-university-ms-polymer-technology",
    name: "M.Sc. in Chemical, Biochemical & Materials Engineering (Polymers)",
    institution: "Aalto University",
    location: "Espoo, Uusimaa",
    country: "Finland",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€15,000",
    ranking: "Top Finnish Research University",
    admission_process: "Aalto Graduate Admissions evaluation + Interview",
    eligibility: "B.Sc. in Chemistry / Chemical Engineering / Polymer Science",
    curriculum_highlights: ["Biomaterials & Composites", "Polymer Processing", "Polymer Chemistry Laboratory"],
    website_url: "https://aalto.fi",
    is_indian: false
  },
  {
    slug: "trento-university-ms-materials-engineering",
    name: "M.Sc. in Materials and Production Engineering (Polymers)",
    institution: "University of Trento",
    location: "Trento, Trentino",
    country: "Italy",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€3,000",
    ranking: "Top Italian Young University Research Rank",
    admission_process: "Trento Uni online application evaluation",
    eligibility: "B.Sc. in Engineering / Chemistry / Physics (min GPA)",
    curriculum_highlights: ["Mechanical Behaviour of Plastics", "Rheological Characterization", "Composite Structures"],
    website_url: "https://www.unitn.it",
    is_indian: false
  },
  {
    slug: "bordeaux-university-ms-polymer-science",
    name: "M.Sc. in Polymer Science & Formulation",
    institution: "University of Bordeaux",
    location: "Bordeaux, Aquitaine",
    country: "France",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€243 (State subsidized fee)",
    ranking: "Renowned French Macromolecular Center",
    admission_process: "Bordeaux Admissions Committee evaluation",
    eligibility: "B.Sc. in Chemistry / Formulation Science / Polymer Materials",
    curriculum_highlights: ["Advanced Polymer Formulations", "Industrial Mixing & Extrusion", "Bio-plastics Development"],
    website_url: "https://www.u-bordeaux.fr",
    is_indian: false
  },
  {
    slug: "penn-state-ms-polymer-science",
    name: "M.S. in Materials Science (Polymer Science Option)",
    institution: "Penn State University",
    location: "State College, Pennsylvania",
    country: "USA",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$36,000",
    ranking: "Top-Tier Materials Science Institution in USA",
    admission_process: "Penn State Graduate application + GRE + SOP",
    eligibility: "B.S. in Chemistry, Physics, or Engineering",
    curriculum_highlights: ["Physical Chemistry of Polymers", "Polymer Synthesis Laboratory", "Rheology Techniques"],
    website_url: "https://www.psu.edu",
    is_indian: false
  },
  {
    slug: "clemson-university-ms-polymer-science",
    name: "M.S. in Materials Science (Polymers & Fibres)",
    institution: "Clemson University",
    location: "Clemson, South Carolina",
    country: "USA",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$24,500",
    ranking: "Top Public Research University",
    admission_process: "Clemson portal evaluation",
    eligibility: "Undergraduate degree in Science / Engineering (min 3.0 GPA)",
    curriculum_highlights: ["Fibre Chemistry", "Polymer Extrusion Practice", "Materials Characterization"],
    website_url: "https://www.clemson.edu",
    is_indian: false
  },
  {
    slug: "dresden-university-ms-polymer-science",
    name: "M.Sc. in Organic and Molecular Electronics",
    institution: "TU Dresden",
    location: "Dresden, Saxony",
    country: "Germany",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "€600 (Semester administrative fee)",
    ranking: "TU9 German Excellence University member",
    admission_process: "TUD portal evaluation",
    eligibility: "B.Sc. in Physics / Chemistry / Materials Science / Nanotechnology",
    curriculum_highlights: ["Organic Semiconductors", "Polymer Electronic Arrays", "Advanced Physics Lab"],
    website_url: "https://tu-dresden.de",
    is_indian: false
  },
  {
    slug: "sheffield-university-msc-polymer-science",
    name: "M.Sc. in Polymers & Composites",
    institution: "University of Sheffield",
    location: "Sheffield, Yorkshire",
    country: "UK",
    degree_type: "MS",
    duration: "1 Year",
    fees_annual: "£28,000",
    ranking: "Top Russell Group University in UK",
    admission_process: "Sheffield online PG portal evaluation",
    eligibility: "UK 2:1 Honours degree in Materials Science / Chemistry",
    curriculum_highlights: ["Polymer Synthesis Methods", "Design of Composite Materials", "Processing Automation"],
    website_url: "https://www.sheffield.ac.uk",
    is_indian: false
  },
  {
    slug: "monash-university-ms-polymer-science",
    name: "M.Sc. in Green Chemical Technology (Polymers)",
    institution: "Monash University",
    location: "Melbourne, Victoria",
    country: "Australia",
    degree_type: "MS",
    duration: "2 Years",
    fees_annual: "$42,500",
    ranking: "Group of Eight Australian University",
    admission_process: "Monash PG portal evaluation",
    eligibility: "B.Sc. in Chemistry / Applied Chemical technology (min GPA)",
    curriculum_highlights: ["Green Polymer Chemistry", "Biomass Derived Plastics", "Life Cycle Assessment"],
    website_url: "https://www.monash.edu",
    is_indian: false
  }
];

// Define 17 Scholarships
const SCHOLARSHIPS = [
  // Indian Scholarships (9 items)
  {
    name: "GATE Post Graduate Scholarship",
    provider: "Ministry of Education (MoE) / AICTE",
    amount: "₹12,400 per month",
    eligibility: "Valid GATE Score card holder admitted in M.Tech/M.E. Polymer/Plastics programs in India",
    deadline: "December (Annual)",
    apply_url: "https://www.aicte-india.org",
    description: "Financial assistance provided by the Government of India to GATE qualified scholars to support their post-graduate research.",
    is_indian: true
  },
  {
    name: "CIPET Merit-cum-Means Scholarship",
    provider: "Central Institute of Petrochemicals Engineering & Technology (CIPET)",
    amount: "Partial to Full Tuition Fee Waiver",
    eligibility: "CIPET DPT/DPMT/B.Tech students with good academics and family income under ₹3 Lakhs/year",
    deadline: "October (Annual)",
    apply_url: "https://www.cipet.gov.in",
    description: "A institutional support scheme designed to assist meritorious students from economically weaker sections to complete their polymer courses.",
    is_indian: true
  },
  {
    name: "Prime Minister's Special Scholarship Scheme (PMSSS)",
    provider: "AICTE / Govt of India",
    amount: "Full Tuition Fee + Maintenance Allowance up to ₹1 Lakh/year",
    eligibility: "Students from J&K and Ladakh pursuing B.Tech in Polymer/Plastics in accredited institutions",
    deadline: "August (Annual)",
    apply_url: "https://www.aicte-india.org/bureaus/jk",
    description: "Government incentive supporting higher technical education for youth belonging to Jammu & Kashmir and Ladakh.",
    is_indian: true
  },
  {
    name: "OP Jindal Outstanding Merit Scholarship",
    provider: "O.P. Jindal Group",
    amount: "₹80,000 per year (for B.Tech students)",
    eligibility: "Top 10% of B.Tech students in Mechanical, Materials or Polymer Engineering at partner institutes",
    deadline: "September (Annual)",
    apply_url: "https://www.opjems.com",
    description: "Private industrial scholarship designed to identify and support future technological leaders in engineering.",
    is_indian: true
  },
  {
    name: "Reliance Foundation Undergraduate Scholarship",
    provider: "Reliance Industries / Reliance Foundation",
    amount: "Up to ₹2 Lakhs over the degree duration",
    eligibility: "First-year B.Tech students in Polymer/Chemical/Mechanical with family income under ₹15 Lakhs/year",
    deadline: "October (Annual)",
    apply_url: "https://www.reliancefoundation.org",
    description: "A scholarship cohort providing financial support and leadership development opportunities to undergraduate scholars.",
    is_indian: true
  },
  {
    name: "Supreme Industries Merit Scholarship",
    provider: "Supreme Industries Limited",
    amount: "₹30,000 per year",
    eligibility: "Meritorious Diploma/B.Tech plastics students with academic scores above 75%",
    deadline: "November (Annual)",
    apply_url: "https://www.supreme.co.in",
    description: "Corporate CSR initiative by India's leading plastics processor to incentivize academic excellence in plastics technology.",
    is_indian: true
  },
  {
    name: "AICTE National Doctoral Fellowship (NDF)",
    provider: "AICTE",
    amount: "₹31,000/month + HRA (Research Fellowship)",
    eligibility: "Ph.D. candidates admitted in AICTE approved departments with GATE/GPAT score card",
    deadline: "July (Annual)",
    apply_url: "https://www.aicte-india.org",
    description: "Government fellowship supporting high-quality doctoral research in technical domains including polymers and composites.",
    is_indian: true
  },
  {
    name: "UGC Junior Research Fellowship (JRF)",
    provider: "University Grants Commission (UGC)",
    amount: "₹37,000/month + HRA",
    eligibility: "Post-graduate scholars who have qualified in CSIR-UGC NET examination in Chemical Sciences",
    deadline: "June/December (Biannual)",
    apply_url: "https://www.ugc.ac.in",
    description: "Assistance to qualified candidates wishing to pursue full-time doctoral research in national labs and universities.",
    is_indian: true
  },
  {
    name: "Pragati Scholarship for Girls",
    provider: "AICTE / Govt of India",
    amount: "₹50,000 per year",
    eligibility: "Female students admitted to first-year B.Tech/Diploma programs in technical institutions",
    deadline: "November (Annual)",
    apply_url: "https://www.aicte-india.org",
    description: "Government scheme aiming to support and encourage women to pursue technical and engineering careers.",
    is_indian: true
  },
  // Global Scholarships (8 items)
  {
    name: "Fulbright-Nehru Master's Fellowships",
    provider: "United States-India Educational Foundation (USIEF)",
    amount: "Full Tuition + Living Stipend + Health Insurance + Round-trip Airfare",
    eligibility: "Indian citizens with 4-year Bachelor's degree and min 3 years of work experience aiming to study in USA",
    deadline: "May (Annual)",
    apply_url: "https://www.usief.org.in",
    description: "Highly prestigious scholarship supporting outstanding Indian scholars to pursue master's degrees in US institutions.",
    is_indian: false
  },
  {
    name: "DAAD Development-Related Postgraduate Courses (EPOS)",
    provider: "German Academic Exchange Service (DAAD)",
    amount: "Full Tuition fee waiver + €934/month stipend + Travel allowance",
    eligibility: "Academic graduates with min 2 years of professional experience in chemical/materials engineering",
    deadline: "October (Annual)",
    apply_url: "https://www.daad.de",
    description: "Germany's flagship scholarship program supporting academic specialization for international engineering candidates.",
    is_indian: false
  },
  {
    name: "Commonwealth Master's Scholarships",
    provider: "Commonwealth Scholarship Commission (CSC) UK",
    amount: "Full tuition fees + Monthly stipend (£1,347/month) + Airfare",
    eligibility: "Citizens of Commonwealth countries seeking 1-year Master's degree at a UK university",
    deadline: "October (Annual)",
    apply_url: "https://cscuk.fcdo.gov.uk",
    description: "Funding support aimed at mid-career professionals from developing countries to study in UK universities.",
    is_indian: false
  },
  {
    name: "Chevening Scholarships",
    provider: "Foreign, Commonwealth & Development Office (FCDO) UK",
    amount: "Full Tuition Fees + Flights + Monthly Living Allowance",
    eligibility: "Undergraduate degree holder with min 2 years of work experience targeting master's courses in UK",
    deadline: "November (Annual)",
    apply_url: "https://www.chevening.org",
    description: "UK Government's global scholarship program targeting prospective leaders and tech innovators.",
    is_indian: false
  },
  {
    name: "Erasmus Mundus Joint Masters Scholarships",
    provider: "European Commission / European Union",
    amount: "€1,400 per month + Full Tuition coverage + Travel expenses",
    eligibility: "Outstanding students globally seeking joint master's programs across multiple European universities",
    deadline: "January (Annual)",
    apply_url: "https://ec.europa.eu/programmes/erasmus-plus",
    description: "Prestigious joint master's funding enabling students to carry out coursework across at least two European countries.",
    is_indian: false
  },
  {
    name: "SPE Foundation Graduate Scholarship",
    provider: "Society of Plastics Engineers (SPE) Foundation",
    amount: "$5,000 per year",
    eligibility: "B.S. or M.S. students globally pursuing plastics/polymer engineering studies with high GPA",
    deadline: "March (Annual)",
    apply_url: "https://www.4spe.org/foundation",
    description: "Dedicated industrial scholarship program specifically supporting students specializing in plastics technology.",
    is_indian: false
  },
  {
    name: "ACS Division of Polymer Chemistry Fellowships",
    provider: "American Chemical Society (ACS)",
    amount: "$7,500 research grant + travel support",
    eligibility: "Graduate research scholars conducting thesis research in polymer synthesis or characterization",
    deadline: "April (Annual)",
    apply_url: "https://www.polyacs.org",
    description: "Academic fellowships recognizing research excellence in polymer synthesis and molecular macromolecular chemistry.",
    is_indian: false
  },
  {
    name: "Great Scholarships India",
    provider: "British Council & UK Government",
    amount: "£10,000 tuition fee waiver",
    eligibility: "Indian passport holders pursuing post-graduate engineering courses in the United Kingdom",
    deadline: "April (Annual)",
    apply_url: "https://www.britishcouncil.in",
    description: "Co-funded initiative supporting Indian students to pursue master's degrees in UK institutions.",
    is_indian: false
  }
];

async function seedEducationHub() {
  console.log('=== SEEDING EDUCATION HUB DATABASE ===');

  // 1. Seed programs
  console.log('Cleaning existing education_programs records...');
  await supabase.from('education_programs').delete().neq('id', '00000000-0000-0000-0000-000000000000');

  let progCount = 0;
  for (const prog of INDIAN_PROGRAMS) {
    const { error } = await supabase.from('education_programs').insert(prog);
    if (error) {
      console.error(`  Failed to insert Indian program "${prog.name}":`, error.message);
    } else {
      progCount++;
    }
  }

  for (const prog of GLOBAL_PROGRAMS) {
    const { error } = await supabase.from('education_programs').insert(prog);
    if (error) {
      console.error(`  Failed to insert Global program "${prog.name}":`, error.message);
    } else {
      progCount++;
    }
  }
  console.log(`✅ Seeded ${progCount} education programs successfully (52 Indian, 32 Global).`);

  // 2. Seed scholarships
  console.log('Cleaning existing scholarships records...');
  await supabase.from('scholarships').delete().neq('id', '00000000-0000-0000-0000-000000000000');

  let scholCount = 0;
  for (const schol of SCHOLARSHIPS) {
    const { error } = await supabase.from('scholarships').insert(schol);
    if (error) {
      console.error(`  Failed to insert scholarship "${schol.name}":`, error.message);
    } else {
      scholCount++;
    }
  }
  console.log(`✅ Seeded ${scholCount} scholarships successfully (9 Indian, 8 Global).`);
  console.log('=== SEEDING COMPLETED SUCCESSFULLY ===');
}

seedEducationHub();
